<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Material docence de Matemáticas para la Estadística Médica con R (Bioestadística) desarrollados por el autor en el Departamento de Estadística e Investigación Operativa, Unidad Docente de Bioestadística de la Universidad de Granada.">

<title>8&nbsp; Semana 8 — Contrastes de Hipótesis (Parte II) – Matemáticas para la Estadística Médica con R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/semana09.html" rel="next">
<link href="../chapters/semana07.html" rel="prev">
<link href="../figures/ugr-logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-b6a8276bf55561bdbc268162d41bd1f7.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-95edd58b3b27b9774827898c46d4f452.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script>
MathJax = {
  tex: {
    macros: {
      btheta: "\\boldsymbol{\\theta}",
      bbeta: "\\boldsymbol{\\beta}",
      bmu: "\\boldsymbol{\\mu}",
      bSigma: "\\boldsymbol{\\Sigma}",
      bx: "\\mathbf{x}",
      bX: "\\mathbf{X}",
      by: "\\mathbf{y}",
      bY: "\\mathbf{Y}",
      bU: "\\mathbf{U}",
      E: "\\mathbb{E}",
      Var: ["\\operatorname{Var}"],
      Cov: ["\\operatorname{Cov}"],
      Corr: ["\\operatorname{Corr}"],
      iid: "\\stackrel{\\text{i.i.d.}}{\\sim}",
      tendD: "\\stackrel{\\mathcal{D}}{\\longrightarrow}",
      reals: "\\mathbb{R}",
      PP: "\\mathbb{P}"
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/semana06.html">Parte III: Inferencia Estadística</a></li><li class="breadcrumb-item"><a href="../chapters/semana08.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Semana 8 — Contrastes de Hipótesis (Parte II)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Matemáticas para la Estadística Médica con R</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Matemáticas-para-la-Estadística-Médica-con-R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte I: Análisis Exploratorio de Datos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Semana 1 — Análisis Exploratorio de Datos (Parte I)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Semana 2 — Análisis Exploratorio de Datos (Parte II)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte II: Probabilidad y Variables Aleatorias</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Semana 3 — Fundamentos de la Teoría de la Probabilidad</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Semana 4 — Variables Aleatorias y Distribuciones de Probabilidad</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Semana 5 — Muestreo y Distribuciones Muestrales</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte III: Inferencia Estadística</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Semana 6 — Estimación de Parámetros</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Semana 7 — Contrastes de Hipótesis (Parte I)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana08.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Semana 8 — Contrastes de Hipótesis (Parte II)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte IV: Regresión Lineal</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Semana 9 — Regresión Lineal Simple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Semana 10 — Regresión Lineal Múltiple</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte V: Análisis de Datos Categóricos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Semana 11 — Análisis de Datos Categóricos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Apéndice A: Repaso Matemático Riguroso</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceB.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Apéndice B: El Paquete <code>BioEstatR</code> — Guía de Referencia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Apéndice C: Guía de R para Estadística Médica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceD.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Apéndice D: Investigación Reproducible con Git, GitHub y RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/examen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Examen Final</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenidos</h2>
   
  <ul>
  <li><a href="#sec-semana08-z-test" id="toc-sec-semana08-z-test" class="nav-link active" data-scroll-target="#sec-semana08-z-test"><span class="header-section-number">8.1</span> Prueba Z para Diferencia de Medias (Varianzas Conocidas)</a>
  <ul class="collapse">
  <li><a href="#preparacion-distribucion-de-la-diferencia-de-medias" id="toc-preparacion-distribucion-de-la-diferencia-de-medias" class="nav-link" data-scroll-target="#preparacion-distribucion-de-la-diferencia-de-medias"><span class="header-section-number">8.1.1</span> Preparación: Distribución de la Diferencia de Medias</a></li>
  <li><a href="#hipotesis-e-estadistico-de-prueba" id="toc-hipotesis-e-estadistico-de-prueba" class="nav-link" data-scroll-target="#hipotesis-e-estadistico-de-prueba"><span class="header-section-number">8.1.2</span> Hipótesis e Estadístico de Prueba</a></li>
  </ul></li>
  <li><a href="#sec-semana08-t-test" id="toc-sec-semana08-t-test" class="nav-link" data-scroll-target="#sec-semana08-t-test"><span class="header-section-number">8.2</span> Prueba t para Dos Muestras Independientes (Varianzas Desconocidas)</a>
  <ul class="collapse">
  <li><a href="#sec-semana08-equal-var" id="toc-sec-semana08-equal-var" class="nav-link" data-scroll-target="#sec-semana08-equal-var"><span class="header-section-number">8.2.1</span> Caso 1: Varianzas Iguales (Homogéneas)</a></li>
  <li><a href="#sec-semana08-unequal-var" id="toc-sec-semana08-unequal-var" class="nav-link" data-scroll-target="#sec-semana08-unequal-var"><span class="header-section-number">8.2.2</span> Caso 2: Varianzas Desiguales (Heterogéneas) — Prueba de Welch</a></li>
  </ul></li>
  <li><a href="#sec-semana08-paired-test" id="toc-sec-semana08-paired-test" class="nav-link" data-scroll-target="#sec-semana08-paired-test"><span class="header-section-number">8.3</span> Prueba t Pareada</a>
  <ul class="collapse">
  <li><a href="#motivacion-y-formulacion" id="toc-motivacion-y-formulacion" class="nav-link" data-scroll-target="#motivacion-y-formulacion"><span class="header-section-number">8.3.1</span> Motivación y Formulación</a></li>
  </ul></li>
  <li><a href="#sec-semana08-f-test" id="toc-sec-semana08-f-test" class="nav-link" data-scroll-target="#sec-semana08-f-test"><span class="header-section-number">8.4</span> Prueba F para Igualdad de Varianzas</a>
  <ul class="collapse">
  <li><a href="#hipotesis-y-estadistico" id="toc-hipotesis-y-estadistico" class="nav-link" data-scroll-target="#hipotesis-y-estadistico"><span class="header-section-number">8.4.1</span> Hipótesis y Estadístico</a></li>
  </ul></li>
  <li><a href="#sec-semana08-power" id="toc-sec-semana08-power" class="nav-link" data-scroll-target="#sec-semana08-power"><span class="header-section-number">8.5</span> Potencia de una Prueba</a>
  <ul class="collapse">
  <li><a href="#conceptos-fundamentales" id="toc-conceptos-fundamentales" class="nav-link" data-scroll-target="#conceptos-fundamentales"><span class="header-section-number">8.5.1</span> Conceptos Fundamentales</a></li>
  <li><a href="#relacion-con-errores-de-tipo-i-y-ii" id="toc-relacion-con-errores-de-tipo-i-y-ii" class="nav-link" data-scroll-target="#relacion-con-errores-de-tipo-i-y-ii"><span class="header-section-number">8.5.2</span> Relación con Errores de Tipo I y II</a></li>
  <li><a href="#derivacion-potencia-para-prueba-bilateral-varianza-conocida" id="toc-derivacion-potencia-para-prueba-bilateral-varianza-conocida" class="nav-link" data-scroll-target="#derivacion-potencia-para-prueba-bilateral-varianza-conocida"><span class="header-section-number">8.5.3</span> Derivación: Potencia para Prueba Bilateral (Varianza Conocida)</a></li>
  <li><a href="#potencia-prueba-unilateral-derecha" id="toc-potencia-prueba-unilateral-derecha" class="nav-link" data-scroll-target="#potencia-prueba-unilateral-derecha"><span class="header-section-number">8.5.4</span> Potencia: Prueba Unilateral Derecha</a></li>
  <li><a href="#potencia-prueba-unilateral-izquierda" id="toc-potencia-prueba-unilateral-izquierda" class="nav-link" data-scroll-target="#potencia-prueba-unilateral-izquierda"><span class="header-section-number">8.5.5</span> Potencia: Prueba Unilateral Izquierda</a></li>
  <li><a href="#factores-que-afectan-la-potencia" id="toc-factores-que-afectan-la-potencia" class="nav-link" data-scroll-target="#factores-que-afectan-la-potencia"><span class="header-section-number">8.5.6</span> Factores que Afectan la Potencia</a></li>
  </ul></li>
  <li><a href="#sec-semana08-power-proportion" id="toc-sec-semana08-power-proportion" class="nav-link" data-scroll-target="#sec-semana08-power-proportion"><span class="header-section-number">8.6</span> Potencia para Pruebas de Proporción</a>
  <ul class="collapse">
  <li><a href="#formulacion" id="toc-formulacion" class="nav-link" data-scroll-target="#formulacion"><span class="header-section-number">8.6.1</span> Formulación</a></li>
  </ul></li>
  <li><a href="#sec-semana08-sample-size" id="toc-sec-semana08-sample-size" class="nav-link" data-scroll-target="#sec-semana08-sample-size"><span class="header-section-number">8.7</span> Cálculo de Tamaño Muestral</a>
  <ul class="collapse">
  <li><a href="#principio-general" id="toc-principio-general" class="nav-link" data-scroll-target="#principio-general"><span class="header-section-number">8.7.1</span> Principio General</a></li>
  <li><a href="#formula-para-prueba-t-de-dos-muestras-varianzas-iguales" id="toc-formula-para-prueba-t-de-dos-muestras-varianzas-iguales" class="nav-link" data-scroll-target="#formula-para-prueba-t-de-dos-muestras-varianzas-iguales"><span class="header-section-number">8.7.2</span> Fórmula para Prueba t de Dos Muestras (Varianzas Iguales)</a></li>
  <li><a href="#sec-semana08-bio-power" id="toc-sec-semana08-bio-power" class="nav-link" data-scroll-target="#sec-semana08-bio-power"><span class="header-section-number">8.7.3</span> Cálculo con BioEstatR: <code>testt()</code> y <code>testp()</code></a></li>
  </ul></li>
  <li><a href="#sec-semana08-multiple-testing" id="toc-sec-semana08-multiple-testing" class="nav-link" data-scroll-target="#sec-semana08-multiple-testing"><span class="header-section-number">8.8</span> Comparación Múltiple y Corrección de Bonferroni</a>
  <ul class="collapse">
  <li><a href="#problema-inflacion-de-tasa-de-error-tipo-i" id="toc-problema-inflacion-de-tasa-de-error-tipo-i" class="nav-link" data-scroll-target="#problema-inflacion-de-tasa-de-error-tipo-i"><span class="header-section-number">8.8.1</span> Problema: Inflación de Tasa de Error Tipo I</a></li>
  <li><a href="#correccion-de-bonferroni" id="toc-correccion-de-bonferroni" class="nav-link" data-scroll-target="#correccion-de-bonferroni"><span class="header-section-number">8.8.2</span> Corrección de Bonferroni</a></li>
  </ul></li>
  <li><a href="#sec-semana08-mosquito-example" id="toc-sec-semana08-mosquito-example" class="nav-link" data-scroll-target="#sec-semana08-mosquito-example"><span class="header-section-number">8.9</span> Ejemplo Completo: Análisis de Datos de Mosquitos</a>
  <ul class="collapse">
  <li><a href="#contexto-del-problema" id="toc-contexto-del-problema" class="nav-link" data-scroll-target="#contexto-del-problema"><span class="header-section-number">8.9.1</span> Contexto del Problema</a></li>
  <li><a href="#datos-y-exploracion" id="toc-datos-y-exploracion" class="nav-link" data-scroll-target="#datos-y-exploracion"><span class="header-section-number">8.9.2</span> Datos y Exploración</a></li>
  <li><a href="#test-t-varianzas-homogeneas" id="toc-test-t-varianzas-homogeneas" class="nav-link" data-scroll-target="#test-t-varianzas-homogeneas"><span class="header-section-number">8.9.3</span> Test t: Varianzas Homogéneas</a></li>
  <li><a href="#test-t-varianzas-heterogeneas-welch" id="toc-test-t-varianzas-heterogeneas-welch" class="nav-link" data-scroll-target="#test-t-varianzas-heterogeneas-welch"><span class="header-section-number">8.9.4</span> Test t: Varianzas Heterogéneas (Welch)</a></li>
  <li><a href="#test-f-igualdad-de-varianzas" id="toc-test-f-igualdad-de-varianzas" class="nav-link" data-scroll-target="#test-f-igualdad-de-varianzas"><span class="header-section-number">8.9.5</span> Test F: Igualdad de Varianzas</a></li>
  <li><a href="#calculo-de-potencia" id="toc-calculo-de-potencia" class="nav-link" data-scroll-target="#calculo-de-potencia"><span class="header-section-number">8.9.6</span> Cálculo de Potencia</a></li>
  </ul></li>
  <li><a href="#sec-semana08-summary-table" id="toc-sec-semana08-summary-table" class="nav-link" data-scroll-target="#sec-semana08-summary-table"><span class="header-section-number">8.10</span> Tabla Resumen: Contrastes de Dos Muestras</a></li>
  <li><a href="#sec-semana08-resumen" id="toc-sec-semana08-resumen" class="nav-link" data-scroll-target="#sec-semana08-resumen"><span class="header-section-number">8.11</span> Resumen</a>
  <ul class="collapse">
  <li><a href="#conceptos-clave" id="toc-conceptos-clave" class="nav-link" data-scroll-target="#conceptos-clave"><span class="header-section-number">8.11.1</span> Conceptos Clave</a></li>
  <li><a href="#potencia-estadistica" id="toc-potencia-estadistica" class="nav-link" data-scroll-target="#potencia-estadistica"><span class="header-section-number">8.11.2</span> Potencia Estadística</a></li>
  <li><a href="#tamano-muestral" id="toc-tamano-muestral" class="nav-link" data-scroll-target="#tamano-muestral"><span class="header-section-number">8.11.3</span> Tamaño Muestral</a></li>
  <li><a href="#testing-multiple" id="toc-testing-multiple" class="nav-link" data-scroll-target="#testing-multiple"><span class="header-section-number">8.11.4</span> Testing Múltiple</a></li>
  </ul></li>
  <li><a href="#sec-semana08-supuestos" id="toc-sec-semana08-supuestos" class="nav-link" data-scroll-target="#sec-semana08-supuestos"><span class="header-section-number">8.12</span> Verificación de Supuestos: Normalidad y Homogeneidad</a>
  <ul class="collapse">
  <li><a href="#test-de-shapiro-wilk-normalidad" id="toc-test-de-shapiro-wilk-normalidad" class="nav-link" data-scroll-target="#test-de-shapiro-wilk-normalidad"><span class="header-section-number">8.12.1</span> Test de Shapiro-Wilk: Normalidad</a></li>
  <li><a href="#test-de-bartlett-homogeneidad-de-varianzas" id="toc-test-de-bartlett-homogeneidad-de-varianzas" class="nav-link" data-scroll-target="#test-de-bartlett-homogeneidad-de-varianzas"><span class="header-section-number">8.12.2</span> Test de Bartlett: Homogeneidad de Varianzas</a></li>
  </ul></li>
  <li><a href="#sec-semana9-bootstrap" id="toc-sec-semana9-bootstrap" class="nav-link" data-scroll-target="#sec-semana9-bootstrap"><span class="header-section-number">8.13</span> Bootstrap y Métodos Robustos como Alternativas</a></li>
  <li><a href="#sec-semana08-non-parametric" id="toc-sec-semana08-non-parametric" class="nav-link" data-scroll-target="#sec-semana08-non-parametric"><span class="header-section-number">8.14</span> Pruebas No Paramétricas Basadas en Rangos</a>
  <ul class="collapse">
  <li><a href="#sec-semana08-wilcoxon-indep" id="toc-sec-semana08-wilcoxon-indep" class="nav-link" data-scroll-target="#sec-semana08-wilcoxon-indep"><span class="header-section-number">8.14.1</span> Prueba de Wilcoxon-Mann-Whitney (Muestras Independientes)</a></li>
  <li><a href="#sec-semana08-wilcoxon-paired" id="toc-sec-semana08-wilcoxon-paired" class="nav-link" data-scroll-target="#sec-semana08-wilcoxon-paired"><span class="header-section-number">8.14.2</span> Prueba de Wilcoxon de los Rangos con Signo (Muestras Pareadas)</a></li>
  <li><a href="#sec-semana08-kruskal" id="toc-sec-semana08-kruskal" class="nav-link" data-scroll-target="#sec-semana08-kruskal"><span class="header-section-number">8.14.3</span> Prueba de Kruskal-Wallis (K Muestras Independientes)</a></li>
  </ul></li>
  <li><a href="#sec-semana08-ejercicios" id="toc-sec-semana08-ejercicios" class="nav-link" data-scroll-target="#sec-semana08-ejercicios"><span class="header-section-number">8.15</span> Ejercicios</a></li>
  <li><a href="#sec-semana08-respuestas" id="toc-sec-semana08-respuestas" class="nav-link" data-scroll-target="#sec-semana08-respuestas"><span class="header-section-number">8.16</span> Respuestas a los Ejercicios</a></li>
  <li><a href="#sec-semana08-resources" id="toc-sec-semana08-resources" class="nav-link" data-scroll-target="#sec-semana08-resources"><span class="header-section-number">8.17</span> Recursos Adicionales</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/edit/main/chapters/semana08.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/blob/main/chapters/semana08.qmd" class="toc-action"><i class="bi empty"></i>Ver el código</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/semana06.html">Parte III: Inferencia Estadística</a></li><li class="breadcrumb-item"><a href="../chapters/semana08.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Semana 8 — Contrastes de Hipótesis (Parte II)</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-semana08" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Semana 8 — Contrastes de Hipótesis (Parte II)</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>En esta semana continuamos con contrastes de hipótesis, enfocándonos en pruebas para comparar <strong>dos muestras independientes y pareadas</strong>, pruebas para igualdad de varianzas, y conceptos fundamentales de <strong>potencia estadística</strong> y cálculo de tamaño muestral.</p>
<section id="sec-semana08-z-test" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="sec-semana08-z-test"><span class="header-section-number">8.1</span> Prueba Z para Diferencia de Medias (Varianzas Conocidas)</h2>
<section id="preparacion-distribucion-de-la-diferencia-de-medias" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="preparacion-distribucion-de-la-diferencia-de-medias"><span class="header-section-number">8.1.1</span> Preparación: Distribución de la Diferencia de Medias</h3>
<p>Supongamos que tenemos dos poblaciones independientes:</p>
<ul>
<li>Población 1: <span class="math inline">\(X_1 \sim N(\mu_1, \sigma_1^2)\)</span> con <span class="math inline">\(\sigma_1^2\)</span> <strong>conocida</strong></li>
<li>Población 2: <span class="math inline">\(X_2 \sim N(\mu_2, \sigma_2^2)\)</span> con <span class="math inline">\(\sigma_2^2\)</span> <strong>conocida</strong></li>
</ul>
<p>Tomamos muestras de tamaños <span class="math inline">\(n_1\)</span> y <span class="math inline">\(n_2\)</span> respectivamente. Los estimadores de las medias son:</p>
<p><span class="math display">\[\bar{X}_1 \sim N\left(\mu_1, \frac{\sigma_1^2}{n_1}\right), \quad \bar{X}_2 \sim N\left(\mu_2, \frac{\sigma_2^2}{n_2}\right)\]</span></p>
<p>La diferencia entre las medias muestrales sigue una distribución normal:</p>
<p><span class="math display">\[D = \bar{X}_1 - \bar{X}_2 \sim N\left(\omega, \sigma_D^2\right)\]</span></p>
<p>donde: <span class="math display">\[\omega = \mu_1 - \mu_2, \quad \sigma_D^2 = \frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}\]</span></p>
</section>
<section id="hipotesis-e-estadistico-de-prueba" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="hipotesis-e-estadistico-de-prueba"><span class="header-section-number">8.1.2</span> Hipótesis e Estadístico de Prueba</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Prueba Z para Dos Muestras
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consideramos las hipótesis:</p>
<ul>
<li><strong>Bilateral:</strong> <span class="math inline">\(H_0: \mu_1 - \mu_2 = \omega_0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \mu_1 - \mu_2 \neq \omega_0\)</span></li>
<li><strong>Unilateral derecha:</strong> <span class="math inline">\(H_0: \mu_1 - \mu_2 \leq \omega_0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \mu_1 - \mu_2 &gt; \omega_0\)</span></li>
<li><strong>Unilateral izquierda:</strong> <span class="math inline">\(H_0: \mu_1 - \mu_2 \geq \omega_0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \mu_1 - \mu_2 &lt; \omega_0\)</span></li>
</ul>
<p>(Habitualmente, <span class="math inline">\(\omega_0 = 0\)</span>)</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Estadístico de Prueba: Z
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bajo <span class="math inline">\(H_0\)</span> (asumiendo <span class="math inline">\(\omega = \omega_0\)</span>):</p>
<p><span class="math display">\[Z = \frac{(\bar{X}_1 - \bar{X}_2) - \omega_0}{\sqrt{\frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}}} \sim N(0, 1)\]</span></p>
<p><strong>Criterios de rechazo:</strong> - <strong>Bilateral:</strong> Rechazo si <span class="math inline">\(|Z| &gt; z_{1-\alpha/2}\)</span> - <strong>Unilateral derecha:</strong> Rechazo si <span class="math inline">\(Z &gt; z_{1-\alpha}\)</span> - <strong>Unilateral izquierda:</strong> Rechazo si <span class="math inline">\(Z &lt; -z_{1-\alpha}\)</span></p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana08-t-test" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-semana08-t-test"><span class="header-section-number">8.2</span> Prueba t para Dos Muestras Independientes (Varianzas Desconocidas)</h2>
<section id="sec-semana08-equal-var" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="sec-semana08-equal-var"><span class="header-section-number">8.2.1</span> Caso 1: Varianzas Iguales (Homogéneas)</h3>
<p>Cuando no conocemos las varianzas pero <strong>asumimos que son iguales</strong> (<span class="math inline">\(\sigma_1^2 = \sigma_2^2 = \sigma^2\)</span>), utilizamos un estimador combinado (pooled) de la varianza:</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Varianza Combinada (Pooled)
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[S_p^2 = \frac{(n_1 - 1)S_1^2 + (n_2 - 1)S_2^2}{n_1 + n_2 - 2}\]</span></p>
<p>donde <span class="math inline">\(S_1^2\)</span> y <span class="math inline">\(S_2^2\)</span> son las varianzas muestrales sesgadas:</p>
<p><span class="math display">\[S_j^2 = \frac{1}{n_j - 1} \sum_{i=1}^{n_j} (X_{ji} - \bar{X}_j)^2, \quad j = 1, 2\]</span></p>
<p>El estimador de la varianza de la diferencia es:</p>
<p><span class="math display">\[S_D^2 = S_p^2 \left( \frac{1}{n_1} + \frac{1}{n_2} \right)\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Estadístico t (Varianzas Homogéneas)
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[T = \frac{(\bar{X}_1 - \bar{X}_2) - \omega_0}{S_D} \sim t_{n_1 + n_2 - 2}\]</span></p>
<p>bajo <span class="math inline">\(H_0: \mu_1 - \mu_2 = \omega_0\)</span>.</p>
<p><strong>Grados de libertad:</strong> <span class="math inline">\(\nu = n_1 + n_2 - 2\)</span></p>
<p><strong>Criterios de rechazo:</strong> - <strong>Bilateral:</strong> Rechazo si <span class="math inline">\(|T| &gt; t_{1-\alpha/2;\nu}\)</span> - <strong>Unilateral derecha:</strong> Rechazo si <span class="math inline">\(T &gt; t_{1-\alpha;\nu}\)</span> - <strong>Unilateral izquierda:</strong> Rechazo si <span class="math inline">\(T &lt; -t_{1-\alpha;\nu}\)</span></p>
</div>
</div>
</section>
<section id="sec-semana08-unequal-var" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="sec-semana08-unequal-var"><span class="header-section-number">8.2.2</span> Caso 2: Varianzas Desiguales (Heterogéneas) — Prueba de Welch</h3>
<p>Cuando las varianzas poblacionales son <strong>desiguales</strong> (<span class="math inline">\(\sigma_1^2 \neq \sigma_2^2\)</span>), la solución es aproximada.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Estadístico de Welch-Satterthwaite
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[T = \frac{(\bar{X}_1 - \bar{X}_2) - \omega_0}{\sqrt{\frac{S_1^2}{n_1} + \frac{S_2^2}{n_2}}} \approx t_\nu\]</span></p>
<p>donde los <strong>grados de libertad aproximados</strong> (Welch-Satterthwaite) son:</p>
<p><span class="math display">\[\nu = \frac{\left( \frac{S_1^2}{n_1} + \frac{S_2^2}{n_2} \right)^2}{\frac{1}{n_1-1}\left(\frac{S_1^2}{n_1}\right)^2 + \frac{1}{n_2-1}\left(\frac{S_2^2}{n_2}\right)^2}\]</span></p>
<p>Este test es más conservador que asumir varianzas iguales.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo con BioEstatR: testt(), testf() y testwx()
</div>
</div>
<div class="callout-body-container callout-body">
<p>Documentacion completa de las tres funciones en <a href="apendiceB.html#sec-bio-contrastes" class="quarto-xref"><span>Sección B.5</span></a>.</p>
<div class="cell">
<div id="lst-semana08-1" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana08-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;8.1: Código R
</figcaption>
<div aria-describedby="lst-semana08-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BioEstatR)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># t-test dos muestras independientes: HbA1c por sexo</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">testt</span>(<span class="at">grupos =</span> osteo<span class="sc">$</span>sexo, <span class="at">m =</span> osteo<span class="sc">$</span>hba1c, <span class="at">grf =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> 

# t-test para 2 Muestras Independientes
# -------------------------------------

# Información muestral y estimación de las medias
  Niveles de agrupación: Hombre, Mujer 

                        n media    dt   sem             IC
  osteo$hba1c [Hombre] 45  8.55 1.745 0.260 (8.029, 9.078)
  osteo$hba1c [Mujer]  49  8.58 1.864 0.266  (8.04, 9.111)
  ____ 
  * IC elaborados al 95% de confianza para estimar μ₁ y μ₂ respectivamente 


# Pruebas de normalidad (test de Shapiro-Wilk)
[1] Para grupo = Hombre, W = 0.958, gl = 45, p = 0.102
[2] Para grupo = Mujer, W = 0.980, gl = 49, p = 0.566

# Test de homogeneidad de varianzas. Fexp = (var₂/var₁)
  Fexp = 1.141, gl₁ = 48, gl₂ = 44, p = 0.660 

# Diferencia de medias (osteo$hba1c [Mujer] - osteo$hba1c [Hombre])
  Hipótesis a contrastar: H₀:μ₁=μ₂ (μ₂-μ₁=0) 

  a) Test de Student (varianzas homogéneas) 
  texp = 0.059, gl = 92 
    p = 0.953 para la alternativa bilateral H₁:μ₁≠μ₂ 
    p = 0.476 para la alternativa unilateral H₁:μ₁&lt;μ₂ 
  95%-IC(μ₂-μ₁) = (-0.719, 0.764) 

  b) Test de Welch (varianzas no homogéneas) 
  texp = 0.060, gl = 91.96 
    p = 0.953 para la alternativa bilateral H₁:μ₁≠μ₂ 
    p = 0.476 para la alternativa unilateral H₁:μ₁&lt;μ₂ 
  95%-IC(μ₂-μ₁) = (-0.717, 0.762) </code></pre>
</div>
<div id="lst-semana08-1" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana08-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;8.2: Código R
</figcaption>
<div aria-describedby="lst-semana08-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test F de varianzas del IMC por sexo</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">testf</span>(<span class="at">s1 =</span> <span class="fu">sd</span>(osteo<span class="sc">$</span>imc[osteo<span class="sc">$</span>sexo <span class="sc">==</span> <span class="st">"Hombre"</span>]),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">n1 =</span> <span class="fu">sum</span>(osteo<span class="sc">$</span>sexo <span class="sc">==</span> <span class="st">"Hombre"</span>),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">s2 =</span> <span class="fu">sd</span>(osteo<span class="sc">$</span>imc[osteo<span class="sc">$</span>sexo <span class="sc">==</span> <span class="st">"Mujer"</span>]),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">n2 =</span> <span class="fu">sum</span>(osteo<span class="sc">$</span>sexo <span class="sc">==</span> <span class="st">"Mujer"</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 2.31

[[2]]
[1] 48

[[3]]
[1] 44

[[4]]
[1] 0.00585</code></pre>
</div>
<div id="lst-semana08-1" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana08-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;8.3: Código R
</figcaption>
<div aria-describedby="lst-semana08-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Wilcoxon-Mann-Whitney: IMC &lt; 25 años vs &gt; 33 años (no normales)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">testwx</span>(<span class="at">m1 =</span> osteo<span class="sc">$</span>imc[osteo<span class="sc">$</span>grupo_edad <span class="sc">==</span> <span class="st">"&lt; 25"</span>],</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">m2 =</span> osteo<span class="sc">$</span>imc[osteo<span class="sc">$</span>grupo_edad <span class="sc">==</span> <span class="st">"&gt; 33"</span>],</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">grf =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Test de Wilcoxon/Mann-Whithney para dos muestras independientes 
----------------------------------------------------------------
# Información muestral ---

                                Muestra  n    min     Q1     Q2     Q3    max
1 osteo$imc[osteo$grupo_edad == "&lt; 25"] 32 19.628 21.421 22.845 24.149 32.475
2 osteo$imc[osteo$grupo_edad == "&gt; 33"] 30 18.070 23.382 25.889 28.945 37.333
    RIQ
1 2.728
2 5.563

# Rangos ---

                                Muestra  n Suma_rangos Rango_medio       U
1 osteo$imc[osteo$grupo_edad == "&lt; 25"] 32         807      25.219 681.000
2 osteo$imc[osteo$grupo_edad == "&gt; 33"] 30        1146      38.200 279.000

# Test ---

  U = 279.000; Z = 2.831; W = 279.000; p = 0.004

# Tamaño del efecto ---

  Diferencia de localización: -2.668    95%-IC = (-4.518, -0.778) 
  r = 0.360  (criterio: 0.1 pequeño; 0.3 mediano; &gt;0.5 grande)
  Probabilidad de superioridad PS = 0.709
  (probabilidad de que un valor al azar de M1 sea &lt; a un valor al azar de M2) </code></pre>
</div>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana08-paired-test" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-semana08-paired-test"><span class="header-section-number">8.3</span> Prueba t Pareada</h2>
<section id="motivacion-y-formulacion" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="motivacion-y-formulacion"><span class="header-section-number">8.3.1</span> Motivación y Formulación</h3>
<p>En muchos estudios, las observaciones de dos muestras están <strong>apareadas</strong> (matched):</p>
<ul>
<li>Medidas antes y después en los mismos sujetos</li>
<li>Observaciones de hermanos gemelos</li>
<li>Medidas en ambos ojos del mismo paciente</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Datos Pareados
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para datos pareados <span class="math inline">\((X_{1i}, X_{2i})\)</span>, <span class="math inline">\(i = 1, \ldots, n\)</span>, definimos las diferencias:</p>
<p><span class="math display">\[D_i = X_{1i} - X_{2i}\]</span></p>
<p>El test pareado <strong>reduce el problema a una prueba t de una muestra</strong> sobre las diferencias:</p>
<p><span class="math display">\[H_0: \mu_D = \mu_1 - \mu_2 = \omega_0 \quad \text{vs.} \quad H_1: \mu_D \neq \omega_0\]</span></p>
<p>(Típicamente, <span class="math inline">\(\omega_0 = 0\)</span>)</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Estadístico t Pareado
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[T = \frac{\bar{D} - \omega_0}{S_D / \sqrt{n}} \sim t_{n-1}\]</span></p>
<p>donde:</p>
<p><span class="math display">\[\bar{D} = \frac{1}{n} \sum_{i=1}^n D_i, \quad S_D^2 = \frac{1}{n-1} \sum_{i=1}^n (D_i - \bar{D})^2\]</span></p>
<p><strong>Nota importante:</strong> La varianza de las diferencias es típicamente <strong>menor</strong> que la suma de varianzas, lo que da mayor potencia al test pareado cuando los datos están realmente correlacionados.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana08-f-test" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="sec-semana08-f-test"><span class="header-section-number">8.4</span> Prueba F para Igualdad de Varianzas</h2>
<section id="hipotesis-y-estadistico" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="hipotesis-y-estadistico"><span class="header-section-number">8.4.1</span> Hipótesis y Estadístico</h3>
<p>En algunos análisis necesitamos probar si <strong>dos varianzas poblacionales son iguales</strong>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Prueba F de Fisher
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consideramos:</p>
<ul>
<li><strong>Bilateral:</strong> <span class="math inline">\(H_0: \sigma_1^2 = \sigma_2^2\)</span> vs.&nbsp;<span class="math inline">\(H_1: \sigma_1^2 \neq \sigma_2^2\)</span></li>
<li><strong>Unilateral derecha:</strong> <span class="math inline">\(H_0: \sigma_1^2 \leq \sigma_2^2\)</span> vs.&nbsp;<span class="math inline">\(H_1: \sigma_1^2 &gt; \sigma_2^2\)</span></li>
<li><strong>Unilateral izquierda:</strong> <span class="math inline">\(H_0: \sigma_1^2 \geq \sigma_2^2\)</span> vs.&nbsp;<span class="math inline">\(H_1: \sigma_1^2 &lt; \sigma_2^2\)</span></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Estadístico F
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bajo <span class="math inline">\(H_0\)</span> (<span class="math inline">\(\sigma_1^2 = \sigma_2^2\)</span>):</p>
<p><span class="math display">\[F = \frac{S_1^2}{S_2^2} \sim F_{n_1-1, n_2-1}\]</span></p>
<p><strong>Criterios de rechazo:</strong> - <strong>Bilateral:</strong> Rechazo si <span class="math inline">\(F &lt; F_{n_1-1, n_2-1, \alpha/2}\)</span> o <span class="math inline">\(F &gt; F_{n_1-1, n_2-1, 1-\alpha/2}\)</span> - <strong>Unilateral derecha:</strong> Rechazo si <span class="math inline">\(F &gt; F_{n_1-1, n_2-1, 1-\alpha}\)</span> - <strong>Unilateral izquierda:</strong> Rechazo si <span class="math inline">\(F &lt; F_{n_1-1, n_2-1, \alpha}\)</span></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Advertencia: Testing Secuencial
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>No recomendamos realizar la prueba F antes de elegir entre test t con varianzas iguales o desiguales</strong>, porque esta prueba de igualdad consume el nivel de significancia global. Es preferir usar siempre la <strong>Prueba de Welch</strong> como default, que es válida en ambos casos.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana08-power" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="sec-semana08-power"><span class="header-section-number">8.5</span> Potencia de una Prueba</h2>
<section id="conceptos-fundamentales" class="level3" data-number="8.5.1">
<h3 data-number="8.5.1" class="anchored" data-anchor-id="conceptos-fundamentales"><span class="header-section-number">8.5.1</span> Conceptos Fundamentales</h3>
<p>La <strong>potencia</strong> es un concepto crucial en el diseño y evaluación de estudios estadísticos.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Función de Potencia
</div>
</div>
<div class="callout-body-container callout-body">
<p>La <strong>función de potencia</strong> <span class="math inline">\(G(\theta)\)</span> es la probabilidad de rechazar <span class="math inline">\(H_0\)</span> cuando el parámetro verdadero es <span class="math inline">\(\theta\)</span>:</p>
<p><span class="math display">\[G(\theta) = P(\text{rechazar } H_0 | \theta)\]</span></p>
<p><strong>Interpretación:</strong> - Si <span class="math inline">\(\theta \in \Theta_0\)</span> (región de <span class="math inline">\(H_0\)</span>): <span class="math inline">\(G(\theta) = P(\text{Error Tipo I}) \leq \alpha\)</span> - Si <span class="math inline">\(\theta \in \Theta_1\)</span> (región de <span class="math inline">\(H_1\)</span>): <span class="math inline">\(G(\theta) = P(\text{Rechazo correcto}) = 1 - \beta(\theta)\)</span></p>
<p>donde <span class="math inline">\(\beta(\theta)\)</span> es la probabilidad del <strong>Error Tipo II</strong>.</p>
</div>
</div>
</section>
<section id="relacion-con-errores-de-tipo-i-y-ii" class="level3" data-number="8.5.2">
<h3 data-number="8.5.2" class="anchored" data-anchor-id="relacion-con-errores-de-tipo-i-y-ii"><span class="header-section-number">8.5.2</span> Relación con Errores de Tipo I y II</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 20%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Realidad</th>
<th>Rechazamos <span class="math inline">\(H_0\)</span></th>
<th>No rechazamos <span class="math inline">\(H_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_0\)</span> es verdadera</td>
<td>Error Tipo I (prob. <span class="math inline">\(\alpha\)</span>)</td>
<td>Decisión correcta</td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_1\)</span> es verdadera</td>
<td>Decisión correcta (prob. <span class="math inline">\(1-\beta\)</span>)</td>
<td>Error Tipo II (prob. <span class="math inline">\(\beta\)</span>)</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Significancia (<span class="math inline">\(\alpha\)</span>):</strong> Probabilidad de Error Tipo I. Típicamente 0.05.</li>
<li><strong>Potencia (<span class="math inline">\(1-\beta\)</span>):</strong> Probabilidad de detectar una diferencia real. Típicamente 0.80 o 0.90.</li>
</ul>
</section>
<section id="derivacion-potencia-para-prueba-bilateral-varianza-conocida" class="level3" data-number="8.5.3">
<h3 data-number="8.5.3" class="anchored" data-anchor-id="derivacion-potencia-para-prueba-bilateral-varianza-conocida"><span class="header-section-number">8.5.3</span> Derivación: Potencia para Prueba Bilateral (Varianza Conocida)</h3>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Potencia: Prueba Bilateral
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sea <span class="math inline">\(\mu_0\)</span> el valor hipotetizado, <span class="math inline">\(\sigma\)</span> conocida, tamaño muestral <span class="math inline">\(n\)</span> y nivel de significancia <span class="math inline">\(\alpha\)</span>.</p>
<p>Para una prueba bilateral con <span class="math inline">\(H_0: \mu = \mu_0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \mu \neq \mu_0\)</span>:</p>
<p><span class="math display">\[G(\mu) = 1 - P\left(z_{1-\alpha/2} - \frac{\mu - \mu_0}{\sigma/\sqrt{n}} \leq Z \leq z_{1-\alpha/2} - \frac{\mu - \mu_0}{\sigma/\sqrt{n}}\right)\]</span></p>
<p>Equivalentemente:</p>
<p><span class="math display">\[G(\mu) = P\left(Z \leq -z_{1-\alpha/2} - \frac{\mu - \mu_0}{\sigma/\sqrt{n}}\right) + P\left(Z &gt; z_{1-\alpha/2} - \frac{\mu - \mu_0}{\sigma/\sqrt{n}}\right)\]</span></p>
<p><strong>Casos extremos:</strong> - En <span class="math inline">\(\mu = \mu_0\)</span>: <span class="math inline">\(G(\mu_0) = \alpha\)</span> (tasa de Error Tipo I) - Conforme <span class="math inline">\(|\mu - \mu_0|\)</span> aumenta: <span class="math inline">\(G(\mu) \to 1\)</span> (potencia tiende a 1)</p>
</div>
</div>
</section>
<section id="potencia-prueba-unilateral-derecha" class="level3" data-number="8.5.4">
<h3 data-number="8.5.4" class="anchored" data-anchor-id="potencia-prueba-unilateral-derecha"><span class="header-section-number">8.5.4</span> Potencia: Prueba Unilateral Derecha</h3>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Potencia: Prueba Unilateral Derecha
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para <span class="math inline">\(H_0: \mu \leq \mu_0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \mu &gt; \mu_0\)</span>:</p>
<p><span class="math display">\[G(\mu) = 1 - P\left(Z \leq z_{1-\alpha} - \frac{\mu - \mu_0}{\sigma/\sqrt{n}}\right)\]</span></p>
<p>La potencia aumenta cuando <span class="math inline">\(\mu &gt; \mu_0\)</span>, alcanzando su máximo cuando <span class="math inline">\(\mu\)</span> es mucho mayor que <span class="math inline">\(\mu_0\)</span>.</p>
</div>
</div>
</section>
<section id="potencia-prueba-unilateral-izquierda" class="level3" data-number="8.5.5">
<h3 data-number="8.5.5" class="anchored" data-anchor-id="potencia-prueba-unilateral-izquierda"><span class="header-section-number">8.5.5</span> Potencia: Prueba Unilateral Izquierda</h3>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Potencia: Prueba Unilateral Izquierda
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para <span class="math inline">\(H_0: \mu \geq \mu_0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \mu &lt; \mu_0\)</span>:</p>
<p><span class="math display">\[G(\mu) = P\left(Z \leq -z_{1-\alpha} - \frac{\mu - \mu_0}{\sigma/\sqrt{n}}\right)\]</span></p>
<p>La potencia aumenta cuando <span class="math inline">\(\mu &lt; \mu_0\)</span>, alcanzando su máximo cuando <span class="math inline">\(\mu\)</span> es mucho menor que <span class="math inline">\(\mu_0\)</span>.</p>
</div>
</div>
</section>
<section id="factores-que-afectan-la-potencia" class="level3" data-number="8.5.6">
<h3 data-number="8.5.6" class="anchored" data-anchor-id="factores-que-afectan-la-potencia"><span class="header-section-number">8.5.6</span> Factores que Afectan la Potencia</h3>
<p>La potencia de una prueba depende de:</p>
<ol type="1">
<li><strong>Tamaño muestral (<span class="math inline">\(n\)</span>):</strong> Aumentar <span class="math inline">\(n\)</span> aumenta la potencia.</li>
<li><strong>Magnitud del efecto (<span class="math inline">\(|\mu - \mu_0|\)</span> o <span class="math inline">\(\delta\)</span>):</strong> Diferencias más grandes son más fáciles de detectar.</li>
<li><strong>Variabilidad (<span class="math inline">\(\sigma\)</span>):</strong> Menor variabilidad aumenta la potencia.</li>
<li><strong>Nivel de significancia (<span class="math inline">\(\alpha\)</span>):</strong> Aumentar <span class="math inline">\(\alpha\)</span> aumenta la potencia, pero incrementa el Error Tipo I.</li>
</ol>
<hr>
</section>
</section>
<section id="sec-semana08-power-proportion" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="sec-semana08-power-proportion"><span class="header-section-number">8.6</span> Potencia para Pruebas de Proporción</h2>
<section id="formulacion" class="level3" data-number="8.6.1">
<h3 data-number="8.6.1" class="anchored" data-anchor-id="formulacion"><span class="header-section-number">8.6.1</span> Formulación</h3>
<p>Para una prueba binomial sobre proporción <span class="math inline">\(\pi\)</span>:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Potencia: Prueba de Proporción
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sea <span class="math inline">\(\pi_0\)</span> la proporción hipotetizada, <span class="math inline">\(n\)</span> el tamaño muestral, <span class="math inline">\(\alpha\)</span> el nivel de significancia.</p>
<p>Para una prueba bilateral con <span class="math inline">\(H_0: \pi = \pi_0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \pi \neq \pi_0\)</span>:</p>
<p><span class="math display">\[G(\pi) = P(X \leq x_l | \pi) + P(X &gt; x_u | \pi)\]</span></p>
<p>donde <span class="math inline">\(x_l\)</span> y <span class="math inline">\(x_u\)</span> son los valores críticos determinados por el nivel de significancia <span class="math inline">\(\alpha\)</span>, y <span class="math inline">\(X \sim \text{Binomial}(n, \pi)\)</span>.</p>
<ul>
<li><strong>En <span class="math inline">\(\pi = \pi_0\)</span>:</strong> <span class="math inline">\(G(\pi_0) = \alpha\)</span> (tasa de Error Tipo I)</li>
<li><strong>Cuando <span class="math inline">\(\pi\)</span> se aleja de <span class="math inline">\(\pi_0\)</span>:</strong> La potencia <span class="math inline">\(G(\pi)\)</span> aumenta</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Proporción de Éxitos en Prueba Binomial
</div>
</div>
<div class="callout-body-container callout-body">
<p>Supongamos <span class="math inline">\(n = 10\)</span>, <span class="math inline">\(\pi_0 = 0.5\)</span>, <span class="math inline">\(\alpha = 0.05\)</span>. Los valores críticos son <span class="math inline">\(x_l = 2\)</span> y <span class="math inline">\(x_u = 8\)</span>.</p>
<p>Potencia en varios valores de <span class="math inline">\(\pi\)</span>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(\pi\)</span></th>
<th><span class="math inline">\(G(\pi)\)</span></th>
<th><span class="math inline">\(\beta = 1 - G(\pi)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.20</td>
<td>0.3758</td>
<td>0.6242</td>
</tr>
<tr class="even">
<td>0.30</td>
<td>0.1495</td>
<td>0.8505</td>
</tr>
<tr class="odd">
<td>0.40</td>
<td>0.0480</td>
<td>0.9520</td>
</tr>
<tr class="even">
<td>0.50</td>
<td>0.0214</td>
<td>0.9786 (Error Tipo II)</td>
</tr>
<tr class="odd">
<td>0.60</td>
<td>0.0480</td>
<td>0.9520</td>
</tr>
<tr class="even">
<td>0.70</td>
<td>0.1495</td>
<td>0.8505</td>
</tr>
</tbody>
</table>
<p>La potencia es máxima en los extremos de la distribución (<span class="math inline">\(\pi\)</span> cercano a 0 o 1). Esto representa la dificultad de detectar desviaciones pequeñas de <span class="math inline">\(\pi_0 = 0.5\)</span> debido a la máxima variabilidad en ese punto (varianza máxima <span class="math inline">\(p(1-p) = 0.25\)</span>). En contraste, para <span class="math inline">\(\pi\)</span> cerca de 0 o 1, la variabilidad es menor, lo que facilita la detección de diferencias.</p>
</div>
</div>
</section>
</section>
<section id="sec-semana08-sample-size" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="sec-semana08-sample-size"><span class="header-section-number">8.7</span> Cálculo de Tamaño Muestral</h2>
<section id="principio-general" class="level3" data-number="8.7.1">
<h3 data-number="8.7.1" class="anchored" data-anchor-id="principio-general"><span class="header-section-number">8.7.1</span> Principio General</h3>
<p>El tamaño muestral se calcula especificando:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Elementos para Calcular Tamaño Muestral
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Diferencia mínima relevante (<span class="math inline">\(\delta\)</span>):</strong> Qué magnitud de efecto queremos detectar</li>
<li><strong>Nivel de significancia (<span class="math inline">\(\alpha\)</span>):</strong> Típicamente 0.05</li>
<li><strong>Potencia deseada (<span class="math inline">\(1 - \beta\)</span>):</strong> Típicamente 0.80 o 0.90</li>
<li><strong>Desviación estándar (<span class="math inline">\(\sigma\)</span>):</strong> De estudios previos o piloto</li>
</ol>
</div>
</div>
</section>
<section id="formula-para-prueba-t-de-dos-muestras-varianzas-iguales" class="level3" data-number="8.7.2">
<h3 data-number="8.7.2" class="anchored" data-anchor-id="formula-para-prueba-t-de-dos-muestras-varianzas-iguales"><span class="header-section-number">8.7.2</span> Fórmula para Prueba t de Dos Muestras (Varianzas Iguales)</h3>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Tamaño Muestral: Prueba t Bilateral
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para detectar una diferencia <span class="math inline">\(\delta = \mu_1 - \mu_2\)</span> entre dos muestras de igual tamaño:</p>
<p><span class="math display">\[n = \frac{2\sigma^2 (z_{1-\alpha/2} + z_{1-\beta})^2}{\delta^2}\]</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(z_{1-\alpha/2}\)</span> es el quantil normal para nivel de significancia <span class="math inline">\(\alpha\)</span></li>
<li><span class="math inline">\(z_{1-\beta}\)</span> es el quantil normal para potencia <span class="math inline">\(1-\beta\)</span></li>
<li><span class="math inline">\(\sigma^2\)</span> es la varianza (asumida igual en ambas muestras)</li>
</ul>
<p><strong>Ejemplo:</strong> Si <span class="math inline">\(\delta = 10\)</span>, <span class="math inline">\(\sigma = 15\)</span>, <span class="math inline">\(\alpha = 0.05\)</span>, <span class="math inline">\(1-\beta = 0.80\)</span>:</p>
<p><span class="math display">\[z_{1-0.025} = 1.96, \quad z_{0.80} = 0.84\]</span></p>
<p><span class="math display">\[n = \frac{2 \times 225 \times (1.96 + 0.84)^2}{100} = \frac{450 \times 6.4}{100} \approx 28.8 \approx 29 \text{ por grupo}\]</span></p>
</div>
</div>
</section>
<section id="sec-semana08-bio-power" class="level3" data-number="8.7.3">
<h3 data-number="8.7.3" class="anchored" data-anchor-id="sec-semana08-bio-power"><span class="header-section-number">8.7.3</span> Cálculo con BioEstatR: <code>testt()</code> y <code>testp()</code></h3>
<p>Las funciones <code>testt()</code> y <code>testp()</code> del paquete <code>BioEstatR</code> (ver <a href="apendiceB.html#sec-bio-contrastes" class="quarto-xref"><span>Sección B.5</span></a>) calculan <strong>simultáneamente</strong> el contraste de hipótesis, la <strong>potencia</strong> y el <strong>tamaño muestral</strong> necesario para detectar una diferencia mínima relevante <span class="math inline">\(\delta\)</span> (effect size en unidades de la variable).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Argumentos clave
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 37%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Argumento</th>
<th>Significado</th>
<th>Función</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>delta</code></td>
<td>Diferencia mínima clínicamente relevante a detectar</td>
<td><code>testt</code>, <code>testp</code></td>
</tr>
<tr class="even">
<td><code>potencia</code></td>
<td>Potencia objetivo <span class="math inline">\(1-\beta\)</span> (típicamente 0.80 o 0.90)</td>
<td><code>testt</code>, <code>testp</code></td>
</tr>
<tr class="odd">
<td><code>alfa</code></td>
<td>Nivel de significancia <span class="math inline">\(\alpha\)</span> (por defecto 0.05)</td>
<td><code>testt</code>, <code>testp</code></td>
</tr>
<tr class="even">
<td><code>m</code>, <code>s</code>, <code>n</code></td>
<td>Media, DT y tamaño piloto (estimaciones previas)</td>
<td><code>testt</code></td>
</tr>
<tr class="odd">
<td><code>x</code>, <code>n</code>, <code>p0</code></td>
<td>Éxitos, tamaño piloto y proporción hipotética</td>
<td><code>testp</code></td>
</tr>
</tbody>
</table>
<p>Cuando se proporciona <code>delta</code> y <code>potencia</code>, la función devuelve el <strong>n necesario</strong>. Si en cambio se fija <code>n</code> y <code>delta</code>, devuelve la <strong>potencia alcanzada</strong>.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Potencia y tamaño muestral en contexto clínico
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dos escenarios reales del estudio piloto <code>osteo</code> (94 pacientes diabéticos):</p>
<ul>
<li><strong>Contraste de medias</strong> (<code>testt</code>): ¿Cuántos pacientes necesitamos para detectar una diferencia de <span class="math inline">\(\delta = 0.5\%\)</span> en HbA1c respecto al umbral clínico de 7.5% con potencia del 90%?</li>
<li><strong>Contraste de proporciones</strong> (<code>testp</code>): ¿Y para detectar una desviación de <span class="math inline">\(\delta = 0.05\)</span> frente a una prevalencia hipotética de tabaquismo del 35% con potencia del 90%?</li>
</ul>
<div class="cell">
<div id="lst-semana08-power" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana08-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;8.4: Código R
</figcaption>
<div aria-describedby="lst-semana08-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BioEstatR)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 1. testt(): potencia y n para una media ---</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># H0: µ_HbA1c = 7.5  ;  delta clinicamente relevante = 0.5%</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Usamos m, s del estudio piloto como referencia</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">testt</span>(<span class="at">m =</span> osteo<span class="sc">$</span>hba1c, <span class="at">m0 =</span> <span class="fl">7.5</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">delta =</span> <span class="fl">0.5</span>, <span class="at">potencia =</span> <span class="fl">0.90</span>, <span class="at">alfa =</span> <span class="fl">0.05</span>, <span class="at">grf =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
# t-Test con una muestra
# ----------------------

# Resumen de 'osteo$hba1c'
    n = 94.000 
    media = 8.565 
    d.t. = 1.799 
    sem = 0.186 

# Estimación de la media μ:
  95%-IC(μ) = (8.196, 8.933) 

# Test de normalidad de Shapiro-Wilk:
  W = 0.983, gl = 94, p = 0.276 

# Test de Student para contrastar H₀:μ=μ₀ con μ₀=7.500
  texp = 5.740, gl = 93 
    p &lt; 0.001 para la alternativa bilateral H₁:μ≠μ₀ 
    p &lt; 0.001 para la alternativa unilateral H₁:μ&gt;μ₀ 

  Estimación del efecto bruto 
  95%-IC(μ-μ₀) = (0.696, 1.433) 

# Estudio de la potencia:
  El test es significativo, se omite el análisis de la potencia. </code></pre>
</div>
<div id="lst-semana08-power" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana08-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;8.5: Código R
</figcaption>
<div aria-describedby="lst-semana08-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 2. testp(): potencia y n para una proporcion ---</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># H0: pi_tabaco = 0.35  ;  delta = 0.05 (5 puntos porcentuales)</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">testp</span>(<span class="at">x =</span> <span class="dv">41</span>, <span class="at">n =</span> <span class="dv">94</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">p0 =</span> <span class="fl">0.35</span>, <span class="at">delta =</span> <span class="fl">0.05</span>, <span class="at">potencia =</span> <span class="fl">0.90</span>, <span class="at">alfa =</span> <span class="fl">0.05</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
# Test para contrastar una proporción binomial
# --------------------------------------------

# Información muestral
  n = 94
  x = 41   n-x=53
  p = 0.436; q = (1-p) = 0.564

# Test Ho:π=0.350
  [1] Método exacto
                      H1  Fexp Valor.p
    Cola derecha π&gt;0.350 1.410   0.052
    Bilateral    π≠0.350     -   0.103

    95%-IC(π) = (0.339, 0.542) (método de Clooper-Pearson)

  [2] Método aproximado a la distribución normal
    Validez: min(nπ₀, n(1-π₀)) = 32.9 (&gt;5, el método es válido)
    zexp = 1.643,  p  = 0.100

    95%-IC(π) = (0.335, 0.542) (método de Wilson)


# Tamaño de muestra para detectar |π-p₀|=δ
  p₀ = 0.350;  δ = 0.05
  Casos (cpc = corrección por continuidad):
                            p1   n n_cpc
  1 Unilateral π&lt;0.350   0.300 753   773
  2 Unilateral π&gt;0.350   0.400 753   773
  3 Bilateral  π≠0.350   0.400 977   997</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los argumentos <code>delta</code> y <code>potencia</code> transforman un contraste de hipótesis estático (sólo p-valor) en un <strong>análisis prospectivo de diseño</strong>: cuantifican la sensibilidad del estudio para detectar efectos clínicamente relevantes. Para la <strong>HbA1c</strong>, el contraste resulta altamente significativo (<span class="math inline">\(t_{obs} = 5.74\)</span>, gl = 93, <span class="math inline">\(p &lt; 0.001\)</span>) por lo que <code>testt()</code> omite el análisis de potencia (la sensibilidad ya se confirma de facto sobre los <span class="math inline">\(n = 94\)</span> pacientes actuales). Una desviación de medio punto porcentual respecto al umbral clínico (7.5%) corresponde a ~10–15 mg/dL de glucemia media, magnitud clínicamente relevante para decisiones terapéuticas. Para la <strong>prevalencia de tabaquismo</strong>, alcanzar potencia del 90% para detectar una desviación de 5 puntos porcentuales respecto al 35% hipotético exige <strong>n ≈ 977 pacientes</strong> (bilateral, ~997 con corrección por continuidad) o ≈ 753 (unilateral), aproximadamente diez veces el tamaño piloto. Esta asimetría refleja una propiedad clave: detectar diferencias en proporciones cercanas a 0.5 (varianza máxima <span class="math inline">\(p(1-p) = 0.25\)</span>) consume más muestra que detectar diferencias en variables continuas con buen contraste señal/ruido. En el diseño de protocolos clínicos, este análisis previo evita el error de planificar estudios incapaces de detectar el efecto buscado (estudios negativos por falta de potencia, no por ausencia real de efecto), y constituye argumento obligado ante comités éticos y agencias financiadoras.</p>
</div>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana08-multiple-testing" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="sec-semana08-multiple-testing"><span class="header-section-number">8.8</span> Comparación Múltiple y Corrección de Bonferroni</h2>
<section id="problema-inflacion-de-tasa-de-error-tipo-i" class="level3" data-number="8.8.1">
<h3 data-number="8.8.1" class="anchored" data-anchor-id="problema-inflacion-de-tasa-de-error-tipo-i"><span class="header-section-number">8.8.1</span> Problema: Inflación de Tasa de Error Tipo I</h3>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Problema: Múltiples Pruebas
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cuando realizamos <strong>múltiples pruebas de hipótesis independientes</strong> con nivel <span class="math inline">\(\alpha\)</span>:</p>
<p>Si efectuamos <span class="math inline">\(k\)</span> pruebas, la probabilidad de al menos un Error Tipo I es:</p>
<p><span class="math display">\[P(\text{al menos un Error Tipo I}) = 1 - (1 - \alpha)^k\]</span></p>
<p><strong>Ejemplo:</strong> Con <span class="math inline">\(k = 10\)</span> pruebas y <span class="math inline">\(\alpha = 0.05\)</span>:</p>
<p><span class="math display">\[P(\text{al menos un Error Tipo I}) = 1 - (0.95)^{10} \approx 0.401 = 40.1\%\]</span></p>
<p>En lugar del nivel de significancia global deseado del 5%, obtenemos una tasa de Error Tipo I del 40%!</p>
</div>
</div>
</section>
<section id="correccion-de-bonferroni" class="level3" data-number="8.8.2">
<h3 data-number="8.8.2" class="anchored" data-anchor-id="correccion-de-bonferroni"><span class="header-section-number">8.8.2</span> Corrección de Bonferroni</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Corrección de Bonferroni
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para mantener una tasa global de Error Tipo I de <span class="math inline">\(\alpha\)</span> cuando realizamos <span class="math inline">\(k\)</span> pruebas:</p>
<p><span class="math display">\[\alpha_{\text{ajustado}} = \frac{\alpha}{k}\]</span></p>
<p>Es decir, cada prueba individual se realiza con nivel de significancia <span class="math inline">\(\alpha/k\)</span>.</p>
<p><strong>Ventajas:</strong> - Simple de implementar - Conservador (garantiza control del Error Tipo I)</p>
<p><strong>Desventajas:</strong> - Muy conservador cuando <span class="math inline">\(k\)</span> es grande - Reduce la potencia de cada prueba individual</p>
<p><strong>Alternativas:</strong> El método de Holm, la corrección FDR (False Discovery Rate), o métodos Bayesianos son menos conservadores.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana08-mosquito-example" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="sec-semana08-mosquito-example"><span class="header-section-number">8.9</span> Ejemplo Completo: Análisis de Datos de Mosquitos</h2>
<section id="contexto-del-problema" class="level3" data-number="8.9.1">
<h3 data-number="8.9.1" class="anchored" data-anchor-id="contexto-del-problema"><span class="header-section-number">8.9.1</span> Contexto del Problema</h3>
<p>Según la Organización Mundial de la Salud, los mosquitos Aedes pueden transmitir enfermedades como dengue y Zika. Un esfuerzo de control consiste en liberar mosquitos transgénicos con esperanza de vida más corta.</p>
<p><strong>Pregunta de investigación:</strong> ¿Es la esperanza de vida significativamente diferente entre mosquitos salvajes (wildtype) y transgénicos?</p>
</section>
<section id="datos-y-exploracion" class="level3" data-number="8.9.2">
<h3 data-number="8.9.2" class="anchored" data-anchor-id="datos-y-exploracion"><span class="header-section-number">8.9.2</span> Datos y Exploración</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Wildtype: n = 20 , media = 29.4 , sd = 2.68 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Transgenic: n = 20 , media = 40.1 , sd = 3.19 </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="semana08_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="test-t-varianzas-homogeneas" class="level3" data-number="8.9.3">
<h3 data-number="8.9.3" class="anchored" data-anchor-id="test-t-varianzas-homogeneas"><span class="header-section-number">8.9.3</span> Test t: Varianzas Homogéneas</h3>
<p>Primero suponemos varianzas iguales:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  wildtype and transgenic
t = -11, df = 38, p-value = 0.00000000000008
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -12.54  -8.76
sample estimates:
mean of x mean of y 
     29.4      40.1 </code></pre>
</div>
</div>
</section>
<section id="test-t-varianzas-heterogeneas-welch" class="level3" data-number="8.9.4">
<h3 data-number="8.9.4" class="anchored" data-anchor-id="test-t-varianzas-heterogeneas-welch"><span class="header-section-number">8.9.4</span> Test t: Varianzas Heterogéneas (Welch)</h3>
<p>Si observamos varianzas muy diferentes, usamos la prueba de Welch:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  wildtype and transgenic
t = -11, df = 37, p-value = 0.0000000000001
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -12.54  -8.76
sample estimates:
mean of x mean of y 
     29.4      40.1 </code></pre>
</div>
</div>
</section>
<section id="test-f-igualdad-de-varianzas" class="level3" data-number="8.9.5">
<h3 data-number="8.9.5" class="anchored" data-anchor-id="test-f-igualdad-de-varianzas"><span class="header-section-number">8.9.5</span> Test F: Igualdad de Varianzas</h3>
<p>Podemos probar formalmente si las varianzas son iguales:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  wildtype and transgenic
F = 0.7, num df = 19, denom df = 19, p-value = 0.5
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.28 1.79
sample estimates:
ratio of variances 
             0.707 </code></pre>
</div>
</div>
</section>
<section id="calculo-de-potencia" class="level3" data-number="8.9.6">
<h3 data-number="8.9.6" class="anchored" data-anchor-id="calculo-de-potencia"><span class="header-section-number">8.9.6</span> Cálculo de Potencia</h3>
<p>Si el estudio fuera diseñado ahora, ¿qué tamaño muestral necesitaríamos?</p>
<div class="cell">
<div id="lst-semana08-8" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana08-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;8.6: Código R
</figcaption>
<div aria-describedby="lst-semana08-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Supongamos que queremos detectar una diferencia de 5 días</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># con desviación estándar combinada de 10 días</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Potencia deseada = 0.80, significancia = 0.05</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>power_result <span class="ot">&lt;-</span> <span class="fu">power.t.test</span>(</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="cn">NULL</span>,           <span class="co"># Queremos calcular n</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">delta =</span> <span class="dv">5</span>,          <span class="co"># Diferencia a detectar</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="dv">10</span>,            <span class="co"># Desviación estándar</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">sig.level =</span> <span class="fl">0.05</span>,   <span class="co"># Significancia bilateral</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">power =</span> <span class="fl">0.80</span>,       <span class="co"># Potencia deseada</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Tamaño muestral requerido por grupo:"</span>, <span class="fu">round</span>(power_result<span class="sc">$</span>n), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Tamaño muestral requerido por grupo: 64 </code></pre>
</div>
<div id="lst-semana08-8" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana08-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;8.7: Código R
</figcaption>
<div aria-describedby="lst-semana08-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># También podemos calcular la potencia de nuestro estudio actual</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>power_actual <span class="ot">&lt;-</span> <span class="fu">power.t.test</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n1,             <span class="co"># Tamaño muestral observado</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">delta =</span> <span class="fu">mean</span>(wildtype) <span class="sc">-</span> <span class="fu">mean</span>(transgenic),  <span class="co"># Diferencia observada</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="fu">sqrt</span>((<span class="fu">var</span>(wildtype) <span class="sc">+</span> <span class="fu">var</span>(transgenic)) <span class="sc">/</span> <span class="dv">2</span>),  <span class="co"># SD combinada</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">"two.sided"</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Potencia del estudio observado:"</span>, <span class="fu">round</span>(power_actual<span class="sc">$</span>power, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Potencia del estudio observado: 1 </code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana08-summary-table" class="level2" data-number="8.10">
<h2 data-number="8.10" class="anchored" data-anchor-id="sec-semana08-summary-table"><span class="header-section-number">8.10</span> Tabla Resumen: Contrastes de Dos Muestras</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Escenario</th>
<th>Estadístico</th>
<th>Distribución</th>
<th>Grados de Libertad</th>
<th>Fórmula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Z-test</strong> (varianzas conocidas)</td>
<td><span class="math inline">\(Z = \frac{(\bar{X}_1 - \bar{X}_2) - \omega_0}{\sqrt{\sigma_1^2/n_1 + \sigma_2^2/n_2}}\)</span></td>
<td><span class="math inline">\(N(0,1)\)</span></td>
<td>∞</td>
<td>Conocidas</td>
</tr>
<tr class="even">
<td><strong>t-test</strong> (varianzas iguales)</td>
<td><span class="math inline">\(T = \frac{(\bar{X}_1 - \bar{X}_2) - \omega_0}{S_p\sqrt{1/n_1 + 1/n_2}}\)</span></td>
<td><span class="math inline">\(t\)</span></td>
<td><span class="math inline">\(n_1 + n_2 - 2\)</span></td>
<td>Estimadas</td>
</tr>
<tr class="odd">
<td><strong>Welch</strong> (varianzas desiguales)</td>
<td><span class="math inline">\(T = \frac{(\bar{X}_1 - \bar{X}_2) - \omega_0}{\sqrt{S_1^2/n_1 + S_2^2/n_2}}\)</span></td>
<td><span class="math inline">\(t\)</span> (aprox.)</td>
<td>W-S formula</td>
<td>Estimadas</td>
</tr>
<tr class="even">
<td><strong>t pareado</strong></td>
<td><span class="math inline">\(T = \frac{\bar{D} - \omega_0}{S_D/\sqrt{n}}\)</span></td>
<td><span class="math inline">\(t\)</span></td>
<td><span class="math inline">\(n - 1\)</span></td>
<td>Diferencias</td>
</tr>
<tr class="odd">
<td><strong>F-test</strong></td>
<td><span class="math inline">\(F = \frac{S_1^2}{S_2^2}\)</span></td>
<td><span class="math inline">\(F\)</span></td>
<td><span class="math inline">\((n_1-1, n_2-1)\)</span></td>
<td>Varianzas</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="sec-semana08-resumen" class="level2" data-number="8.11">
<h2 data-number="8.11" class="anchored" data-anchor-id="sec-semana08-resumen"><span class="header-section-number">8.11</span> Resumen</h2>
<section id="conceptos-clave" class="level3" data-number="8.11.1">
<h3 data-number="8.11.1" class="anchored" data-anchor-id="conceptos-clave"><span class="header-section-number">8.11.1</span> Conceptos Clave</h3>
<ul>
<li><p><strong>Prueba Z de dos muestras:</strong> Para varianzas conocidas, estadístico sigue <span class="math inline">\(N(0,1)\)</span></p></li>
<li><p><strong>Prueba t de dos muestras (varianzas iguales):</strong> Varianza combinada (pooled), grados de libertad <span class="math inline">\(= n_1 + n_2 - 2\)</span></p></li>
<li><p><strong>Prueba t de Welch:</strong> Para varianzas desiguales, usa grados de libertad Welch-Satterthwaite</p></li>
<li><p><strong>Prueba t pareada:</strong> Reduce a una prueba t de una muestra sobre diferencias</p></li>
<li><p><strong>Prueba F:</strong> Para comparar varianzas, estadístico <span class="math inline">\(F = S_1^2 / S_2^2 \sim F_{n_1-1, n_2-1}\)</span></p></li>
</ul>
</section>
<section id="potencia-estadistica" class="level3" data-number="8.11.2">
<h3 data-number="8.11.2" class="anchored" data-anchor-id="potencia-estadistica"><span class="header-section-number">8.11.2</span> Potencia Estadística</h3>
<ul>
<li><p><strong>Potencia (<span class="math inline">\(1-\beta\)</span>):</strong> Probabilidad de rechazar <span class="math inline">\(H_0\)</span> cuando <span class="math inline">\(H_1\)</span> es verdadera (detectar un efecto real)</p></li>
<li><p><strong>Error Tipo I (<span class="math inline">\(\alpha\)</span>):</strong> Probabilidad de rechazar <span class="math inline">\(H_0\)</span> cuando es verdadera (típicamente 0.05)</p></li>
<li><p><strong>Error Tipo II (<span class="math inline">\(\beta\)</span>):</strong> Probabilidad de no rechazar <span class="math inline">\(H_0\)</span> cuando <span class="math inline">\(H_1\)</span> es verdadera (típicamente 0.10-0.20)</p></li>
<li><p><strong>Factores que aumentan potencia:</strong></p>
<ul>
<li>Mayor tamaño muestral (<span class="math inline">\(n\)</span>)</li>
<li>Mayor diferencia/efecto a detectar (<span class="math inline">\(\delta\)</span>)</li>
<li>Menor variabilidad (<span class="math inline">\(\sigma\)</span>)</li>
<li>Mayor nivel de significancia (<span class="math inline">\(\alpha\)</span>) — pero aumenta Error Tipo I</li>
</ul></li>
</ul>
</section>
<section id="tamano-muestral" class="level3" data-number="8.11.3">
<h3 data-number="8.11.3" class="anchored" data-anchor-id="tamano-muestral"><span class="header-section-number">8.11.3</span> Tamaño Muestral</h3>
<ul>
<li><p>Se calcula especificando: efecto a detectar, potencia deseada, nivel de significancia, variabilidad</p></li>
<li><p>Fórmula para t-test bilateral: <span class="math inline">\(n = \frac{2\sigma^2 (z_{1-\alpha/2} + z_{1-\beta})^2}{\delta^2}\)</span></p></li>
</ul>
</section>
<section id="testing-multiple" class="level3" data-number="8.11.4">
<h3 data-number="8.11.4" class="anchored" data-anchor-id="testing-multiple"><span class="header-section-number">8.11.4</span> Testing Múltiple</h3>
<ul>
<li><p><strong>Corrección de Bonferroni:</strong> Usar <span class="math inline">\(\alpha_{\text{ajustado}} = \alpha/k\)</span> cuando se hacen <span class="math inline">\(k\)</span> pruebas</p></li>
<li><p>Evitar prueba de igualdad de varianzas antes de elegir test (mejor usar Welch siempre)</p></li>
</ul>
<hr>
</section>
</section>
<section id="sec-semana08-supuestos" class="level2" data-number="8.12">
<h2 data-number="8.12" class="anchored" data-anchor-id="sec-semana08-supuestos"><span class="header-section-number">8.12</span> Verificación de Supuestos: Normalidad y Homogeneidad</h2>
<p>Los contrastes asintóticos basados en el Teorema Central del Límite —como el t-test y el F-test— requieren verificar dos condiciones: (1) normalidad de los datos o residuos, y (2) igualdad de varianzas entre grupos. Con <span class="math inline">\(n \geq 60\)</span> el TCL garantiza normalidad asintótica de la media, pero para muestras menores conviene comprobarlo formalmente.</p>
<section id="test-de-shapiro-wilk-normalidad" class="level3" data-number="8.12.1">
<h3 data-number="8.12.1" class="anchored" data-anchor-id="test-de-shapiro-wilk-normalidad"><span class="header-section-number">8.12.1</span> Test de Shapiro-Wilk: Normalidad</h3>
<p>El test de Shapiro-Wilk <span class="citation" data-cites="Shapiro1965">(<a href="../references.html#ref-Shapiro1965" role="doc-biblioref">Shapiro &amp; Wilk, 1965</a>)</span> es la prueba de normalidad más potente para muestras pequeñas y moderadas (<span class="math inline">\(n \leq 5000\)</span>).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Test de Shapiro-Wilk
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dada una muestra <span class="math inline">\(x_1, \ldots, x_n\)</span>, el estadístico es:</p>
<p><span class="math display">\[W = \frac{\left(\displaystyle\sum_{i=1}^{n} a_i\, x_{(i)}\right)^2}{\displaystyle\sum_{i=1}^{n} (x_i - \bar{x})^2}\]</span></p>
<p>donde <span class="math inline">\(x_{(i)}\)</span> son los estadísticos de orden y <span class="math inline">\(a_i\)</span> son coeficientes tabulados que dependen de la distribución normal estándar.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: la muestra proviene de una distribución normal</li>
<li><span class="math inline">\(H_1\)</span>: la distribución no es normal</li>
<li>Se rechaza <span class="math inline">\(H_0\)</span> cuando <span class="math inline">\(W\)</span> es <strong>pequeño</strong> (p-valor &lt; <span class="math inline">\(\alpha\)</span>)</li>
<li><span class="math inline">\(W \in (0, 1]\)</span>; valores próximos a 1 indican normalidad</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Test de normalidad en datos clínicos
</div>
</div>
<div class="callout-body-container callout-body">
<p>Usando el conjunto de datos <code>osteo</code> de <code>BioEstatR</code>, que contiene 94 pacientes diabéticos de la Facultad de Medicina de la UGR, comprobamos la normalidad de la variable edad:</p>
<div class="cell">
<div id="lst-semana08-9" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana08-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;8.8: Código R
</figcaption>
<div aria-describedby="lst-semana08-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BioEstatR)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Shapiro-Wilk con BioEstatR</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">testnormal</span>(osteo<span class="sc">$</span>edad)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="semana08_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
# Test de normalidad de Shapiro-Wilk  
 ------------------------------------- 
   n = 94,  W = 0.907,  p &lt; 0.001 </code></pre>
</div>
<div id="lst-semana08-9" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana08-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;8.9: Código R
</figcaption>
<div aria-describedby="lst-semana08-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Shapiro-Wilk con R base</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(osteo<span class="sc">$</span>edad)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  osteo$edad
W = 0.9, p-value = 0.000005</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong> Con <span class="math inline">\(W = 0.907\)</span> y <span class="math inline">\(p &lt; 0.001\)</span>, rechazamos normalidad (<span class="math inline">\(\alpha = 0.05\)</span>). Para alternativas cuando no hay normalidad y <span class="math inline">\(n &lt; 60\)</span>, ver <span class="quarto-unresolved-ref">?sec-semana12-bootstrap</span>.</p>
</div>
</div>
</section>
<section id="test-de-bartlett-homogeneidad-de-varianzas" class="level3" data-number="8.12.2">
<h3 data-number="8.12.2" class="anchored" data-anchor-id="test-de-bartlett-homogeneidad-de-varianzas"><span class="header-section-number">8.12.2</span> Test de Bartlett: Homogeneidad de Varianzas</h3>
<p>El test de Bartlett contrasta si <span class="math inline">\(k\)</span> grupos independientes tienen la misma varianza poblacional, bajo el supuesto de que los datos son normales.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Test de Bartlett
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sean <span class="math inline">\(k\)</span> grupos con tamaños <span class="math inline">\(n_1, \ldots, n_k\)</span> y varianzas muestrales <span class="math inline">\(s_1^2, \ldots, s_k^2\)</span>.</p>
<p><strong>Hipótesis:</strong> <span class="math inline">\(H_0: \sigma_1^2 = \sigma_2^2 = \cdots = \sigma_k^2\)</span> frente a <span class="math inline">\(H_1\)</span>: al menos dos varianzas difieren.</p>
<p><strong>Varianza combinada:</strong> <span class="math display">\[s_p^2 = \frac{\sum_{j=1}^k (n_j - 1)\,s_j^2}{n - k}, \quad n = \sum_{j=1}^k n_j\]</span></p>
<p><strong>Estadístico de Bartlett:</strong> <span class="math display">\[\chi^2_B = \frac{1}{c}\left[(n-k)\ln s_p^2 - \sum_{j=1}^k (n_j - 1)\ln s_j^2\right]\]</span></p>
<p>donde <span class="math inline">\(c = 1 + \frac{1}{3(k-1)}\left(\sum_{j=1}^k \frac{1}{n_j - 1} - \frac{1}{n-k}\right)\)</span> es un factor de corrección.</p>
<p>Bajo <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\chi^2_B \sim \chi^2_{k-1}\)</span> (asintóticamente). Sensible a no normalidad — si los datos no son normales, usar <strong>Test de Levene</strong> (<code>car::leveneTest()</code>).</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Homogeneidad del IMC por grupo de edad
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  imc by grupo_edad
Bartlett's K-squared = 11, df = 2, p-value = 0.004</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong> <span class="math inline">\(\chi^2_B \approx 10.96\)</span>, <span class="math inline">\(gl = 2\)</span>, <span class="math inline">\(p = 0.004 &lt; 0.05\)</span>: <strong>se rechaza</strong> la igualdad de varianzas. El supuesto de homocedasticidad <strong>no se cumple</strong>; conviene usar el test de Welch (<code>oneway.test(..., var.equal = FALSE)</code>) o, si los datos no son normales, el test de Levene (<code>car::leveneTest()</code>) y comparaciones no paramétricas como Kruskal-Wallis. Evitar t-test o ANOVA clásico.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Regla Práctica: ¿Cuándo verificar los supuestos?
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Supuesto</th>
<th>Test</th>
<th>Función R</th>
<th>Cuándo usarlo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Normalidad</td>
<td>Shapiro-Wilk</td>
<td><code>shapiro.test()</code></td>
<td>Siempre si <span class="math inline">\(n &lt; 60\)</span></td>
</tr>
<tr class="even">
<td>Homogeneidad</td>
<td>Bartlett</td>
<td><code>bartlett.test()</code></td>
<td>Datos normales</td>
</tr>
<tr class="odd">
<td>Homogeneidad</td>
<td>Levene</td>
<td><code>car::leveneTest()</code></td>
<td>Datos no normales</td>
</tr>
</tbody>
</table>
<p><strong>TCL:</strong> Con <span class="math inline">\(n \geq 60\)</span>, el t-test es robusto a la no normalidad <span class="citation" data-cites="Casella2002">(<a href="../references.html#ref-Casella2002" role="doc-biblioref">Casella &amp; Berger, 2002</a>)</span>. Para <span class="math inline">\(n &lt; 60\)</span> y datos no normales, ver métodos bootstrap en <span class="quarto-unresolved-ref">?sec-semana12-bootstrap</span>.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana9-bootstrap" class="level2" data-number="8.13">
<h2 data-number="8.13" class="anchored" data-anchor-id="sec-semana9-bootstrap"><span class="header-section-number">8.13</span> Bootstrap y Métodos Robustos como Alternativas</h2>
<p>Cuando el test de Shapiro-Wilk rechaza normalidad <strong>y</strong> el tamaño muestral es insuficiente para garantizar el TCL (<span class="math inline">\(n &lt; 60\)</span>), los métodos clásicos basados en la distribución <span class="math inline">\(t\)</span> o <span class="math inline">\(F\)</span> pueden producir inferencias incorrectas. El <strong>bootstrap</strong> y los <strong>tests de permutación</strong> son alternativas válidas que no requieren supuestos distribucionales <span class="citation" data-cites="Chihara2019">(<a href="../references.html#ref-Chihara2019" role="doc-biblioref">Chihara &amp; Hesterberg, 2019</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Bootstrap (Efron, 1979)
</div>
</div>
<div class="callout-body-container callout-body">
<p>El bootstrap simula la distribución muestral de un estadístico <span class="math inline">\(\hat{\theta}\)</span> remuestreando <strong>con reemplazo</strong> de la muestra original.</p>
<p><strong>Algoritmo del IC bootstrap por percentiles:</strong></p>
<ol type="1">
<li><p>Sea <span class="math inline">\(\mathbf{x} = (x_1, \ldots, x_n)\)</span> la muestra original.</p></li>
<li><p>Para <span class="math inline">\(b = 1, \ldots, B\)</span> (con <span class="math inline">\(B = 10000\)</span> recomendado):</p>
<ul>
<li>Generar muestra bootstrap <span class="math inline">\(\mathbf{x}^{(b)}\)</span>: extraer <span class="math inline">\(n\)</span> valores con reemplazo de <span class="math inline">\(\mathbf{x}\)</span></li>
<li>Calcular <span class="math inline">\(\hat{\theta}^{(b)} = T(\mathbf{x}^{(b)})\)</span></li>
</ul></li>
<li><p>El IC al <span class="math inline">\((1-\alpha)\)</span>% por percentiles es: <span class="math display">\[\left[\hat{\theta}^{*}_{(\alpha/2)}, \; \hat{\theta}^{*}_{(1-\alpha/2)}\right]\]</span> donde los superíndices son cuantiles de la distribución bootstrap <span class="math inline">\(\{\hat{\theta}^{(b)}\}_{b=1}^{B}\)</span>.</p></li>
</ol>
<p>El <strong>método BCa</strong> (Bias-Corrected and Accelerated) ajusta por sesgo y asimetría — es más preciso y se recomienda para muestras pequeñas.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Test de Permutación
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para contrastar <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> (igualdad de medias entre dos grupos), el test de permutación calcula la distribución exacta del estadístico de prueba bajo <span class="math inline">\(H_0\)</span> permutando aleatoriamente las etiquetas de grupo.</p>
<p><strong>Algoritmo:</strong></p>
<ol type="1">
<li>Calcular la diferencia observada: <span class="math inline">\(D_{\text{obs}} = \bar{x}_1 - \bar{x}_2\)</span></li>
<li>Para <span class="math inline">\(b = 1, \ldots, B\)</span>: permutar aleatoriamente las asignaciones de grupo → calcular <span class="math inline">\(D^{(b)}\)</span></li>
<li>p-valor bilateral: <span class="math inline">\(\hat{p} = \frac{\#\{|D^{(b)}| \geq |D_{\text{obs}}|\}}{B}\)</span></li>
</ol>
<p>No requiere normalidad ni homocedasticidad. Válido para cualquier tamano muestral.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: IMC en hombres diabéticos — bootstrap manual con bucle
</div>
</div>
<div class="callout-body-container callout-body">
<p>El IMC de los pacientes masculinos del dataset <code>osteo</code> <strong>no sigue una distribución normal</strong> (Shapiro-Wilk: <span class="math inline">\(W = 0.924\)</span>, <span class="math inline">\(p = 0.006\)</span>). Implementamos el bootstrap <strong>manualmente con un bucle <code>for</code></strong> (estilo <span class="citation" data-cites="Chihara2019">Chihara &amp; Hesterberg (<a href="../references.html#ref-Chihara2019" role="doc-biblioref">2019</a>)</span>), siguiendo paso a paso el algoritmo de Efron. Después comparamos con el método BCa (paquete <code>boot</code>) y con el IC clásico <span class="math inline">\(t\)</span>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  x
W = 0.9, p-value = 0.006</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Media muestral observada: 23.5 kg/m²</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Réplicas bootstrap (B): 10000 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Media bootstrap promedio: 23.5 kg/m²</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Error estándar bootstrap: 0.428 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>IC 95% (percentiles, bucle manual): [ 22.7 ,  24.4 ] kg/m²</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
Based on 10000 bootstrap replicates

CALL : 
boot.ci(boot.out = boot_obj, type = "bca")

Intervals : 
Level       BCa          
95%   (22.8, 24.5 )  
Calculations and Intervals on Original Scale</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.6 24.4
attr(,"conf.level")
[1] 0.95</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<p>El bootstrap manual con bucle <code>for</code> reproduce paso a paso el algoritmo de Efron (1979): en cada una de las B = 10.000 iteraciones se construye una pseudomuestra extrayendo n = 45 pacientes con reemplazo del IMC observado, se calcula su media, y al final se ordenan las 10.000 medias para extraer los percentiles 2.5% y 97.5%. El IC 95% resultante (≈ [22.7, 24.4] kg/m²) se interpreta clínicamente como el rango plausible del IMC poblacional medio de varones diabéticos —dentro del rango <strong>normopeso</strong> (18.5–24.9 kg/m²) próximo al umbral del sobrepeso según criterios OMS. Comparado con el IC <span class="math inline">\(t\)</span> clásico, el bootstrap proporciona inferencia válida sin requerir normalidad, lo cual es relevante en cohortes pequenas con asimetría en la distribución del IMC (común en diabetes tipo 2). El método BCa corrige por sesgo y asimetría y se recomienda como referencia cuando <span class="math inline">\(n &lt; 30\)</span>; con <span class="math inline">\(n = 45\)</span> los tres intervalos convergen porque el TCL ya comienza a actuar. Esta convergencia se romperá si reducimos n por debajo de 20 o si analizamos variables muy asimétricas (p.&nbsp;ej., triglicéridos o carga viral).</p>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Test de permutación — diferencia de IMC por sexo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Shapiro-Wilk rechaza normalidad tanto en hombres (<span class="math inline">\(p = 0.006\)</span>) como en mujeres (<span class="math inline">\(p = 0.001\)</span>). Usamos un test de permutación en lugar del t-test clásico.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Diferencia observada: -0.78 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>p-valor permutacion:  0.312 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.308</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong> Ambos métodos concuerdan: no hay diferencia significativa en el IMC entre hombres y mujeres (<span class="math inline">\(p \approx 0.32\)</span>). Cuando los tamaños son moderados (<span class="math inline">\(n_1 = 45\)</span>, <span class="math inline">\(n_2 = 49\)</span>), el TCL protege al t-test. El test de permutación proporciona validez exacta sin supuestos.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Cuándo usar cada método
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 46%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Situación</th>
<th>Método recomendado</th>
<th>Función R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Normal, <span class="math inline">\(n\)</span> cualquiera</td>
<td>t-test, ANOVA clásico</td>
<td><code>t.test()</code>, <code>aov()</code></td>
</tr>
<tr class="even">
<td>No normal, <span class="math inline">\(n \geq 60\)</span></td>
<td>t-test (TCL garantiza)</td>
<td><code>t.test()</code></td>
</tr>
<tr class="odd">
<td>No normal, <span class="math inline">\(n &lt; 60\)</span>, 1 muestra</td>
<td>IC Bootstrap BCa</td>
<td><code>boot()</code>, <code>boot.ci()</code></td>
</tr>
<tr class="even">
<td>No normal, <span class="math inline">\(n &lt; 60\)</span>, 2 grupos</td>
<td>Permutación o Wilcoxon</td>
<td><code>replicate()</code>, <code>wilcox.test()</code></td>
</tr>
<tr class="odd">
<td>No normal, <span class="math inline">\(k &gt; 2\)</span> grupos</td>
<td>Kruskal-Wallis</td>
<td><code>kruskal.test()</code></td>
</tr>
<tr class="even">
<td>Varianzas desiguales</td>
<td>Welch t-test</td>
<td><code>t.test(var.equal=FALSE)</code></td>
</tr>
</tbody>
</table>
<p><strong>Referencia:</strong> <span class="citation" data-cites="Chihara2019">Chihara &amp; Hesterberg (<a href="../references.html#ref-Chihara2019" role="doc-biblioref">2019</a>)</span> proporciona una tratamiento riguroso de bootstrap y permutaciones con implementación completa en R, incluyendo la justificación teórica de cada método.</p>
</div>
</div>
<hr>
</section>
<section id="sec-semana08-non-parametric" class="level2" data-number="8.14">
<h2 data-number="8.14" class="anchored" data-anchor-id="sec-semana08-non-parametric"><span class="header-section-number">8.14</span> Pruebas No Paramétricas Basadas en Rangos</h2>
<p>Las pruebas no paramétricas son alternativas a las pruebas paramétricas (como el t-test o el ANOVA) que no requieren que los datos sigan una distribución normal. Se basan en el <strong>rango</strong> (posición) de las observaciones en lugar de sus valores originales, lo que las hace robustas frente a valores atípicos (outliers) y distribuciones asimétricas.</p>
<section id="sec-semana08-wilcoxon-indep" class="level3" data-number="8.14.1">
<h3 data-number="8.14.1" class="anchored" data-anchor-id="sec-semana08-wilcoxon-indep"><span class="header-section-number">8.14.1</span> Prueba de Wilcoxon-Mann-Whitney (Muestras Independientes)</h3>
<p>Es la alternativa no paramétrica al t-test de dos muestras independientes. Contrasta si las distribuciones de dos grupos son idénticas, evaluando si un valor seleccionado al azar de una población tiende a ser mayor que uno de la otra.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Estadístico U de Mann-Whitney
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dadas dos muestras independientes de tamaños <span class="math inline">\(n_1\)</span> y <span class="math inline">\(n_2\)</span>:</p>
<ol type="1">
<li>Se combinan ambas muestras y se asignan rangos (de 1 a <span class="math inline">\(n_1+n_2\)</span>).</li>
<li>Se calcula la suma de rangos para cada grupo (<span class="math inline">\(R_1\)</span> y <span class="math inline">\(R_2\)</span>).</li>
<li>El estadístico <span class="math inline">\(U\)</span> es el mínimo de: <span class="math display">\[U_1 = n_1n_2 + \frac{n_1(n_1+1)}{2} - R_1, \quad U_2 = n_1n_2 + \frac{n_2(n_2+1)}{2} - R_2\]</span></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Comparación del IMC (Wilcoxon-Mann-Whitney)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Contrastamos si el Índice de Masa Corporal (IMC) difiere entre hombres y mujeres usando la alternativa no paramétrica, dado que el IMC frecuentemente presenta asimetría.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Test de Wilcoxon/Mann-Whithney para dos muestras independientes 
----------------------------------------------------------------
# Información muestral ---

                            Muestra  n    min     Q1     Q2     Q3    max   RIQ
1 osteo$imc[osteo$sexo == "Hombre"] 45 18.327 21.436 23.055 24.259 32.323 2.823
2  osteo$imc[osteo$sexo == "Mujer"] 49 18.070 21.155 23.338 26.298 37.333 5.143

# Rangos ---

                            Muestra  n Suma_rangos Rango_medio        U
1 osteo$imc[osteo$sexo == "Hombre"] 45        2095      46.556 1145.000
2  osteo$imc[osteo$sexo == "Mujer"] 49        2370      48.367 1060.000

# Test ---

  U = 1060.000; Z = 0.322; W = 1060.000; p = 0.750

# Tamaño del efecto ---

  Diferencia de localización: -0.193    95%-IC = (-1.595, 0.962) 
  r = 0.033  (criterio: 0.1 pequeño; 0.3 mediano; &gt;0.5 grande)
  Probabilidad de superioridad PS = 0.519
  (probabilidad de que un valor al azar de M1 sea &lt; a un valor al azar de M2) </code></pre>
</div>
</div>
<p><strong>Interpretación:</strong> No se observan diferencias significativas en las distribuciones de IMC entre sexos (<span class="math inline">\(p = 0.751\)</span>). La probabilidad de que un hombre elegido al azar tenga un IMC mayor que una mujer elegida al azar es del <strong>48.1%</strong> (calculada como <span class="math inline">\(1 - PS = 1 - 0.519\)</span>, ya que la salida de <code>testwx()</code> reporta <span class="math inline">\(PS\)</span> como probabilidad de que un valor de <span class="math inline">\(M_1\)</span> sea <strong>menor</strong> que uno de <span class="math inline">\(M_2\)</span>).</p>
</div>
</div>
</section>
<section id="sec-semana08-wilcoxon-paired" class="level3" data-number="8.14.2">
<h3 data-number="8.14.2" class="anchored" data-anchor-id="sec-semana08-wilcoxon-paired"><span class="header-section-number">8.14.2</span> Prueba de Wilcoxon de los Rangos con Signo (Muestras Pareadas)</h3>
<p>Es la alternativa no paramétrica al t-test pareado. Se utiliza para comparar dos medidas relacionadas (antes-después) sobre los mismos sujetos cuando las diferencias no siguen una distribución normal.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Procedimiento
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Calcular las diferencias <span class="math inline">\(D_i = X_{1i} - X_{2i}\)</span>.</li>
<li>Eliminar las diferencias iguales a cero.</li>
<li>Asignar rangos a los valores absolutos <span class="math inline">\(|D_i|\)</span>.</li>
<li>El estadístico <span class="math inline">\(W\)</span> es la suma de los rangos de las diferencias positivas.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Prueba pareada con BioEstatR
</div>
</div>
<div class="callout-body-container callout-body">
<p>Supongamos que evaluamos el calcio sérico (<code>ca</code>) antes y después de un tratamiento en 10 pacientes (datos simulados para ilustración).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Test de Wilcoxon  para dos muestras apareadas 
----------------------------------------------
# Información muestral ---

  Muestra  n   min    Q1    Q2    Q3   max   RIQ
1  ca_pre 10 8.400 8.725 8.950 9.175 9.500 0.450
2 ca_post 10 8.700 8.925 9.050 9.475 9.600 0.550

# Rangos ---

  Se obtienen las diferencias como ca_pre - ca_post
  Pares de datos efectivos para los rangos: 10 de 10

        Muestra  n Suma_rangos Rango_medio
1 dif.negativas 10          55       5.500
2 dif.positivas  0           0         NaN

# Test ---

  V = 0.000; p = 0.002
  z = 2.803; p = 0.005

# Correlación de Spearman ---

  rho-Spearman = 0.982; p &lt; 0.001

# Tamaño del efecto ---

  Diferencia de localización:  (pseudo)mediana = -0.200    95%-IC = (-0.300, -0.100) 
  r = 0.627; p = 0.002</code></pre>
</div>
</div>
<p><strong>Interpretacion:</strong> Existe un aumento significativo en los niveles de calcio tras el tratamiento (<span class="math inline">\(p = 0.005\)</span>). El tamaño del efecto es grande (<span class="math inline">\(r = 0.627\)</span>, criterio convencional: <span class="math inline">\(r &gt; 0.5\)</span> grande).</p>
</div>
</div>
</section>
<section id="sec-semana08-kruskal" class="level3" data-number="8.14.3">
<h3 data-number="8.14.3" class="anchored" data-anchor-id="sec-semana08-kruskal"><span class="header-section-number">8.14.3</span> Prueba de Kruskal-Wallis (K Muestras Independientes)</h3>
<p>Es la alternativa no paramétrica al ANOVA de un factor. Se utiliza para comparar las medianas de tres o más grupos independientes.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Estadístico H de Kruskal-Wallis
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para <span class="math inline">\(k\)</span> grupos con tamaños <span class="math inline">\(n_j\)</span> y suma de rangos <span class="math inline">\(R_j\)</span>:</p>
<p><span class="math display">\[H = \frac{12}{n(n+1)} \sum_{j=1}^k \frac{R_j^2}{n_j} - 3(n+1)\]</span></p>
<p>donde <span class="math inline">\(n = \sum n_j\)</span>. Bajo <span class="math inline">\(H_0\)</span>, <span class="math inline">\(H \sim \chi^2_{k-1}\)</span> asintóticamente.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: IMC por grupo de edad (&gt; 2 grupos)
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  imc by grupo_edad
Kruskal-Wallis chi-squared = 17, df = 2, p-value = 0.0002</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong> Como <span class="math inline">\(p \approx 0.0002 &lt; 0.05\)</span>, rechazamos la hipótesis de igualdad. Al menos un grupo de edad tiene una distribución de IMC significativamente distinta.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana08-ejercicios" class="level2" data-number="8.15">
<h2 data-number="8.15" class="anchored" data-anchor-id="sec-semana08-ejercicios"><span class="header-section-number">8.15</span> Ejercicios</h2>
<p><strong>Ejercicio 8.1:</strong> Se comparan dos métodos de enseñanza en estadística. El Método A (n₁ = 30) tiene media 75 y desviación estándar 8. El Método B (n₂ = 35) tiene media 78 y desviación estándar 7. ¿Hay diferencia significativa entre los métodos a nivel α = 0.05? (Suponga varianzas iguales)</p>
<p><strong>Ejercicio 8.2:</strong> Un investigador mide presión arterial en 10 pacientes antes y después de tomar un medicamento. Las diferencias promedio son -5 mmHg con desviación estándar 8 mmHg. ¿Es el medicamento efectivo en reducir presión (prueba unilateral, α = 0.05)?</p>
<p><strong>Ejercicio 8.3:</strong> Se comparan dos proveedores de materia prima. Proveedor 1: S₁² = 15, n = 20. Proveedor 2: S₂² = 8, n₂ = 18. ¿Hay diferencia significativa en variabilidad (α = 0.05, bilateral)?</p>
<p><strong>Ejercicio 8.4:</strong> Se diseña un estudio para detectar una diferencia de 12 puntos en una escala (σ = 10) con potencia 0.90 y α = 0.05. ¿Cuántos sujetos se necesitan por grupo?</p>
<p><strong>Ejercicio 8.5:</strong> Un investigador realiza 15 pruebas independientes con α = 0.05 sin corrección.&nbsp;¿Cuál es la probabilidad aproximada de cometer al menos un Error Tipo I?</p>
<p><strong>Ejercicio 8.6:</strong> Interprete este resultado de R: <code>t.test(x, y, var.equal=FALSE)</code> da t = 2.34, df = 45.2, p-value = 0.024. ¿Qué conclusión saca?</p>
<p><strong>Ejercicio 8.7:</strong> Un estudio observa media₁ = 100, media₂ = 105, pero el intervalo de confianza al 95% para la diferencia incluye cero. ¿Qué significa esto respecto a la significancia estadística y práctica?</p>
<p><strong>Ejercicio 8.8:</strong> Si el test de Shapiro-Wilk rechaza la normalidad en una muestra pequeña (<span class="math inline">\(n=15\)</span>), ¿qué prueba utilizaría para comparar dos grupos independientes?</p>
<p><strong>Ejercicio 8.9:</strong> ¿Cuál es la principal ventaja de la prueba de Kruskal-Wallis sobre el ANOVA de un factor?</p>
<p><strong>Ejercicio 8.10:</strong> En una muestra de 35 valores de presión arterial sistólica, el test de Shapiro-Wilk produce <span class="math inline">\(W = 0.94\)</span> con <span class="math inline">\(p = 0.089\)</span>. ¿Es válido aplicar un test t de una muestra con <span class="math inline">\(\alpha = 0.05\)</span>? ¿Cambiaría su decisión si <span class="math inline">\(n = 75\)</span>?</p>
</section>
<section id="sec-semana08-respuestas" class="level2" data-number="8.16">
<h2 data-number="8.16" class="anchored" data-anchor-id="sec-semana08-respuestas"><span class="header-section-number">8.16</span> Respuestas a los Ejercicios</h2>
<p><strong>Ejercicio 8.1:</strong> t = (75-78)/√((29×64 + 34×49)/(63) × (1/30 + 1/35)) ≈ -1.81; df ≈ 63; p &gt; 0.05. No hay diferencia significativa.</p>
<p><strong>Ejercicio 8.2:</strong> t = -5/(8/√10) ≈ -1.98; df = 9; p ≈ 0.038 &lt; 0.05. El medicamento es efectivo en reducir presión.</p>
<p><strong>Ejercicio 8.3:</strong> F = 15/8 = 1.875; df₁ = 19, df₂ = 17. F crítico ≈ 2.74. No rechaza H₀; no hay diferencia significativa en variabilidad.</p>
<p><strong>Ejercicio 8.4:</strong> Usando fórmula de potencia: n ≈ 2×(10)²×(1.96 + 1.28)²/(12)² ≈ 29-30 sujetos por grupo.</p>
<p><strong>Ejercicio 8.5:</strong> P(al menos 1 error) = 1 - (1-0.05)¹⁵ ≈ 1 - 0.463 = 0.537 (53.7%). El problema de multiplicidad es importante.</p>
<p><strong>Ejercicio 8.6:</strong> t = 2.34, df = 45.2, p = 0.024 &lt; 0.05. Se rechaza H₀. Hay diferencia significativa entre x e y (usando Welch’s t-test por varianzas desiguales).</p>
<p><strong>Ejercicio 8.7:</strong> Si el IC 95% incluye cero, la diferencia no es estadísticamente significativa (p &gt; 0.05), aunque hay diferencia práctica de 5 unidades. Sin significancia estadística, no podemos afirmar que la diferencia poblacional es real.</p>
<p><strong>Ejercicio 8.8:</strong> Utilizaría la prueba de Wilcoxon-Mann-Whitney (o un test de permutación).</p>
<p><strong>Ejercicio 8.9:</strong> No requiere el supuesto de normalidad en los datos, siendo más robusta cuando hay outliers o distribuciones muy asimétricas.</p>
<p><strong>Ejercicio 8.10:</strong> Con <span class="math inline">\(p = 0.089 &gt; 0.05\)</span>, <strong>no rechazamos</strong> <span class="math inline">\(H_0\)</span> de normalidad → el test t es válido. Con <span class="math inline">\(n = 75\)</span>, el TCL garantiza normalidad asintótica de la media, por lo que el test t es válido independientemente del resultado de Shapiro-Wilk.</p>
</section>
<section id="sec-semana08-resources" class="level2" data-number="8.17">
<h2 data-number="8.17" class="anchored" data-anchor-id="sec-semana08-resources"><span class="header-section-number">8.17</span> Recursos Adicionales</h2>
<ul>
<li><strong>Software R:</strong> Funciones <code>t.test()</code>, <code>var.test()</code>, <code>power.t.test()</code>, <code>wilcox.test()</code>, <code>kruskal.test()</code> en stats</li>
<li><strong>OpenIntro Statistics:</strong> Capítulos sobre comparación de dos medias y potencia</li>
<li><strong>Referencias clásicas:</strong> Rosner (2011) Fundamentals of Biostatistics; Kahn &amp; Sempos (2002) Statistical Methods in Epidemiology</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-Casella2002" class="csl-entry" role="listitem">
Casella, G., &amp; Berger, R. L. (2002). <em>Statistical Inference</em> (2nd ed.). Duxbury Press.
</div>
<div id="ref-Chihara2019" class="csl-entry" role="listitem">
Chihara, L. M., &amp; Hesterberg, T. C. (2019). <em>Mathematical Statistics with Resampling and R</em> (2nd ed.). Wiley.
</div>
<div id="ref-Shapiro1965" class="csl-entry" role="listitem">
Shapiro, S. S., &amp; Wilk, M. B. (1965). An Analysis of Variance Test for Normality (Complete Samples). <em>Biometrika</em>, <em>52</em>(3–4), 591-611.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/semana07.html" class="pagination-link" aria-label="Semana 7 — Contrastes de Hipótesis (Parte I)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Semana 7 — Contrastes de Hipótesis (Parte I)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/semana09.html" class="pagination-link" aria-label="Semana 9 — Regresión Lineal Simple">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Semana 9 — Regresión Lineal Simple</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Matemáticas para la Estadística Médica con R, por Miguel Ángel Luque Fernández</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/edit/main/chapters/semana08.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/blob/main/chapters/semana08.qmd" class="toc-action"><i class="bi empty"></i>Ver el código</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>© 2026 Universidad de Granada · <a href="https://www.ugr.es">ugr.es</a></p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>