<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Material docence de Matemáticas para la Estadística Médica con R (Bioestadística) desarrollados por el autor en el Departamento de Estadística e Investigación Operativa, Unidad Docente de Bioestadística de la Universidad de Granada.">

<title>11&nbsp; Semana 11 — Análisis de Datos Categóricos – Matemáticas para la Estadística Médica con R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../references.html" rel="next">
<link href="../chapters/semana10.html" rel="prev">
<link href="../figures/ugr-logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-bf8030b5a8b8f2de5bceddfb8bf38a1d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script>
MathJax = {
  tex: {
    macros: {
      btheta: "\\boldsymbol{\\theta}",
      bbeta: "\\boldsymbol{\\beta}",
      bmu: "\\boldsymbol{\\mu}",
      bSigma: "\\boldsymbol{\\Sigma}",
      bx: "\\mathbf{x}",
      bX: "\\mathbf{X}",
      by: "\\mathbf{y}",
      bY: "\\mathbf{Y}",
      bU: "\\mathbf{U}",
      E: "\\mathbb{E}",
      Var: ["\\operatorname{Var}"],
      Cov: ["\\operatorname{Cov}"],
      Corr: ["\\operatorname{Corr}"],
      iid: "\\stackrel{\\text{i.i.d.}}{\\sim}",
      tendD: "\\stackrel{\\mathcal{D}}{\\longrightarrow}",
      reals: "\\mathbb{R}",
      PP: "\\mathbb{P}"
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/semana11.html">Parte V: Análisis de Datos Categóricos</a></li><li class="breadcrumb-item"><a href="../chapters/semana11.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Semana 11 — Análisis de Datos Categóricos</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Matemáticas para la Estadística Médica con R</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Matemáticas-para-la-Estadística-Médica-con-R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte I: Análisis Exploratorio de Datos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Semana 1 — Análisis Exploratorio de Datos (Parte I)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Semana 2 — Análisis Exploratorio de Datos (Parte II)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte II: Probabilidad y Variables Aleatorias</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Semana 3 — Fundamentos de la Teoría de la Probabilidad</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Semana 4 — Variables Aleatorias y Distribuciones de Probabilidad</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Semana 5 — Muestreo y Distribuciones Muestrales</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte III: Inferencia Estadística</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Semana 6 — Estimación de Parámetros</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Semana 7 — Contrastes de Hipótesis (Parte I)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Semana 8 — Contrastes de Hipótesis (Parte II)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte IV: Regresión Lineal</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Semana 9 — Regresión Lineal Simple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Semana 10 — Regresión Lineal Múltiple</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte V: Análisis de Datos Categóricos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana11.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Semana 11 — Análisis de Datos Categóricos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Apéndice A: Repaso Matemático Riguroso</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceB.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Apéndice B: El Paquete <code>BioStatR</code> — Guía de Referencia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Apéndice C: Guía de R para Estadística Médica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceD.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Apéndice D: Investigación Reproducible con Git, GitHub y RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/examen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Examen Final</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenidos</h2>
   
  <ul>
  <li><a href="#sec-semana11-tablas" id="toc-sec-semana11-tablas" class="nav-link active" data-scroll-target="#sec-semana11-tablas"><span class="header-section-number">11.1</span> Variables Categóricas y Tablas de Contingencia</a>
  <ul class="collapse">
  <li><a href="#tabla-22-estructura-y-notación-epidemiológica" id="toc-tabla-22-estructura-y-notación-epidemiológica" class="nav-link" data-scroll-target="#tabla-22-estructura-y-notación-epidemiológica"><span class="header-section-number">11.1.1</span> Tabla 2×2: Estructura y Notación Epidemiológica</a></li>
  <li><a href="#tablas-rc-generalizadas" id="toc-tablas-rc-generalizadas" class="nav-link" data-scroll-target="#tablas-rc-generalizadas"><span class="header-section-number">11.1.2</span> Tablas r×c Generalizadas</a></li>
  </ul></li>
  <li><a href="#sec-semana11-independencia" id="toc-sec-semana11-independencia" class="nav-link" data-scroll-target="#sec-semana11-independencia"><span class="header-section-number">11.2</span> Prueba χ² de Independencia</a>
  <ul class="collapse">
  <li><a href="#hipótesis" id="toc-hipótesis" class="nav-link" data-scroll-target="#hipótesis"><span class="header-section-number">11.2.1</span> Hipótesis</a></li>
  <li><a href="#frecuencias-esperadas-bajo-h_0" id="toc-frecuencias-esperadas-bajo-h_0" class="nav-link" data-scroll-target="#frecuencias-esperadas-bajo-h_0"><span class="header-section-number">11.2.2</span> Frecuencias Esperadas Bajo <span class="math inline">\(H_0\)</span></a></li>
  <li><a href="#cálculo-manual-para-tabla-22" id="toc-cálculo-manual-para-tabla-22" class="nav-link" data-scroll-target="#cálculo-manual-para-tabla-22"><span class="header-section-number">11.2.3</span> Cálculo Manual para Tabla 2×2</a></li>
  <li><a href="#ejemplo-médico-tabaquismo-y-osteoporosis" id="toc-ejemplo-médico-tabaquismo-y-osteoporosis" class="nav-link" data-scroll-target="#ejemplo-médico-tabaquismo-y-osteoporosis"><span class="header-section-number">11.2.4</span> Ejemplo Médico: Tabaquismo y Osteoporosis</a></li>
  </ul></li>
  <li><a href="#sec-semana11-homogeneidad" id="toc-sec-semana11-homogeneidad" class="nav-link" data-scroll-target="#sec-semana11-homogeneidad"><span class="header-section-number">11.3</span> Prueba χ² de Homogeneidad</a>
  <ul class="collapse">
  <li><a href="#independencia-vs.-homogeneidad" id="toc-independencia-vs.-homogeneidad" class="nav-link" data-scroll-target="#independencia-vs.-homogeneidad"><span class="header-section-number">11.3.1</span> Independencia vs.&nbsp;Homogeneidad</a></li>
  <li><a href="#procedimiento" id="toc-procedimiento" class="nav-link" data-scroll-target="#procedimiento"><span class="header-section-number">11.3.2</span> Procedimiento</a></li>
  </ul></li>
  <li><a href="#sec-semana11-condiciones" id="toc-sec-semana11-condiciones" class="nav-link" data-scroll-target="#sec-semana11-condiciones"><span class="header-section-number">11.4</span> Condiciones de Aplicación y Alternativas</a>
  <ul class="collapse">
  <li><a href="#condición-de-frecuencias-esperadas" id="toc-condición-de-frecuencias-esperadas" class="nav-link" data-scroll-target="#condición-de-frecuencias-esperadas"><span class="header-section-number">11.4.1</span> Condición de Frecuencias Esperadas</a></li>
  <li><a href="#sec-semana11-yates" id="toc-sec-semana11-yates" class="nav-link" data-scroll-target="#sec-semana11-yates"><span class="header-section-number">11.4.2</span> Corrección de Continuidad de Yates (Tabla 2×2)</a></li>
  <li><a href="#prueba-exacta-de-fisher" id="toc-prueba-exacta-de-fisher" class="nav-link" data-scroll-target="#prueba-exacta-de-fisher"><span class="header-section-number">11.4.3</span> Prueba Exacta de Fisher</a></li>
  </ul></li>
  <li><a href="#sec-semana11-mcnemar" id="toc-sec-semana11-mcnemar" class="nav-link" data-scroll-target="#sec-semana11-mcnemar"><span class="header-section-number">11.5</span> Prueba de McNemar para Datos Apareados</a>
  <ul class="collapse">
  <li><a href="#cuándo-usar-mcnemar" id="toc-cuándo-usar-mcnemar" class="nav-link" data-scroll-target="#cuándo-usar-mcnemar"><span class="header-section-number">11.5.1</span> ¿Cuándo usar McNemar?</a></li>
  <li><a href="#estructura-de-la-tabla-apareada" id="toc-estructura-de-la-tabla-apareada" class="nav-link" data-scroll-target="#estructura-de-la-tabla-apareada"><span class="header-section-number">11.5.2</span> Estructura de la Tabla Apareada</a></li>
  <li><a href="#estadístico-de-mcnemar" id="toc-estadístico-de-mcnemar" class="nav-link" data-scroll-target="#estadístico-de-mcnemar"><span class="header-section-number">11.5.3</span> Estadístico de McNemar</a></li>
  <li><a href="#ejemplo-intervención-para-el-control-de-la-hipertensión" id="toc-ejemplo-intervención-para-el-control-de-la-hipertensión" class="nav-link" data-scroll-target="#ejemplo-intervención-para-el-control-de-la-hipertensión"><span class="header-section-number">11.5.4</span> Ejemplo: Intervención para el Control de la Hipertensión</a></li>
  <li><a href="#implementación-biostatr-vs.-base-r" id="toc-implementación-biostatr-vs.-base-r" class="nav-link" data-scroll-target="#implementación-biostatr-vs.-base-r"><span class="header-section-number">11.5.5</span> Implementación: BioStatR vs.&nbsp;Base R</a></li>
  </ul></li>
  <li><a href="#sec-semana11-asociacion" id="toc-sec-semana11-asociacion" class="nav-link" data-scroll-target="#sec-semana11-asociacion"><span class="header-section-number">11.6</span> Diseños de Estudio y Medidas de Asociación</a>
  <ul class="collapse">
  <li><a href="#estructura-epidemiológica-de-la-tabla-22" id="toc-estructura-epidemiológica-de-la-tabla-22" class="nav-link" data-scroll-target="#estructura-epidemiológica-de-la-tabla-22"><span class="header-section-number">11.6.1</span> Estructura Epidemiológica de la Tabla 2×2</a></li>
  <li><a href="#estudio-de-cohortes-riesgo-relativo-rr" id="toc-estudio-de-cohortes-riesgo-relativo-rr" class="nav-link" data-scroll-target="#estudio-de-cohortes-riesgo-relativo-rr"><span class="header-section-number">11.6.2</span> Estudio de Cohortes: Riesgo Relativo (RR)</a></li>
  <li><a href="#diferencia-de-riesgos-rd-y-nnt" id="toc-diferencia-de-riesgos-rd-y-nnt" class="nav-link" data-scroll-target="#diferencia-de-riesgos-rd-y-nnt"><span class="header-section-number">11.6.3</span> Diferencia de Riesgos (RD) y NNT</a></li>
  <li><a href="#estudio-transversal-razón-de-prevalencias-rp" id="toc-estudio-transversal-razón-de-prevalencias-rp" class="nav-link" data-scroll-target="#estudio-transversal-razón-de-prevalencias-rp"><span class="header-section-number">11.6.4</span> Estudio Transversal: Razón de Prevalencias (RP)</a></li>
  <li><a href="#estudio-caso-control-odds-ratio-or" id="toc-estudio-caso-control-odds-ratio-or" class="nav-link" data-scroll-target="#estudio-caso-control-odds-ratio-or"><span class="header-section-number">11.6.5</span> Estudio Caso-Control: Odds Ratio (OR)</a></li>
  <li><a href="#resumen-de-intervalos-de-confianza" id="toc-resumen-de-intervalos-de-confianza" class="nav-link" data-scroll-target="#resumen-de-intervalos-de-confianza"><span class="header-section-number">11.6.6</span> Resumen de Intervalos de Confianza</a></li>
  </ul></li>
  <li><a href="#sec-semana11-resumen-medidas" id="toc-sec-semana11-resumen-medidas" class="nav-link" data-scroll-target="#sec-semana11-resumen-medidas"><span class="header-section-number">11.7</span> Resumen Comparativo: ¿Qué Medida Usar?</a></li>
  <li><a href="#sec-semana11-r" id="toc-sec-semana11-r" class="nav-link" data-scroll-target="#sec-semana11-r"><span class="header-section-number">11.8</span> Implementación en R</a>
  <ul class="collapse">
  <li><a href="#normalidad-con-testnormal-y-shapiro.test" id="toc-normalidad-con-testnormal-y-shapiro.test" class="nav-link" data-scroll-target="#normalidad-con-testnormal-y-shapiro.test"><span class="header-section-number">11.8.1</span> Normalidad con testnormal() y shapiro.test()</a></li>
  <li><a href="#chi-cuadrado-con-tabla2x2-y-chisq.test" id="toc-chi-cuadrado-con-tabla2x2-y-chisq.test" class="nav-link" data-scroll-target="#chi-cuadrado-con-tabla2x2-y-chisq.test"><span class="header-section-number">11.8.2</span> Chi-cuadrado con tabla2x2() y chisq.test()</a></li>
  <li><a href="#mcnemar-con-tabla2x2-y-mcnemar.test" id="toc-mcnemar-con-tabla2x2-y-mcnemar.test" class="nav-link" data-scroll-target="#mcnemar-con-tabla2x2-y-mcnemar.test"><span class="header-section-number">11.8.3</span> McNemar con tabla2x2() y mcnemar.test()</a></li>
  <li><a href="#tablas-rc-con-tablarxc" id="toc-tablas-rc-con-tablarxc" class="nav-link" data-scroll-target="#tablas-rc-con-tablarxc"><span class="header-section-number">11.8.4</span> Tablas r×c con tablarxc()</a></li>
  <li><a href="#cálculo-manual-de-rr-rd-y-or" id="toc-cálculo-manual-de-rr-rd-y-or" class="nav-link" data-scroll-target="#cálculo-manual-de-rr-rd-y-or"><span class="header-section-number">11.8.5</span> Cálculo Manual de RR, RD y OR</a></li>
  <li><a href="#ejemplo-integrado-con-dataset-osteo" id="toc-ejemplo-integrado-con-dataset-osteo" class="nav-link" data-scroll-target="#ejemplo-integrado-con-dataset-osteo"><span class="header-section-number">11.8.6</span> Ejemplo Integrado con Dataset osteo</a></li>
  </ul></li>
  <li><a href="#ajuste-por-confusión-el-estimador-de-mantel-haenszel" id="toc-ajuste-por-confusión-el-estimador-de-mantel-haenszel" class="nav-link" data-scroll-target="#ajuste-por-confusión-el-estimador-de-mantel-haenszel"><span class="header-section-number">11.9</span> Ajuste por Confusión: El Estimador de Mantel-Haenszel</a>
  <ul class="collapse">
  <li><a href="#el-estimador-de-mantel-haenszel-mh" id="toc-el-estimador-de-mantel-haenszel-mh" class="nav-link" data-scroll-target="#el-estimador-de-mantel-haenszel-mh"><span class="header-section-number">11.9.1</span> El Estimador de Mantel-Haenszel (MH)</a></li>
  <li><a href="#ejemplo-numérico-en-r-evaluación-de-confounding" id="toc-ejemplo-numérico-en-r-evaluación-de-confounding" class="nav-link" data-scroll-target="#ejemplo-numérico-en-r-evaluación-de-confounding"><span class="header-section-number">11.9.2</span> Ejemplo Numérico en R: Evaluación de Confounding</a></li>
  <li><a href="#sec-semana11-rlogitm" id="toc-sec-semana11-rlogitm" class="nav-link" data-scroll-target="#sec-semana11-rlogitm"><span class="header-section-number">11.9.3</span> Control multivariable de la confusión: regresión logística múltiple con <code>rlogitm()</code></a></li>
  </ul></li>
  <li><a href="#ejercicios-del-tema" id="toc-ejercicios-del-tema" class="nav-link" data-scroll-target="#ejercicios-del-tema"><span class="header-section-number">11.10</span> Ejercicios del tema</a></li>
  <li><a href="#sec-semana11-respuestas" id="toc-sec-semana11-respuestas" class="nav-link" data-scroll-target="#sec-semana11-respuestas"><span class="header-section-number">11.11</span> Respuestas a los Ejercicios</a></li>
  <li><a href="#sec-semana11-avanzados" id="toc-sec-semana11-avanzados" class="nav-link" data-scroll-target="#sec-semana11-avanzados"><span class="header-section-number">11.12</span> Recomendaciones de Métodos Avanzados</a></li>
  <li><a href="#sec-semana11-resources" id="toc-sec-semana11-resources" class="nav-link" data-scroll-target="#sec-semana11-resources"><span class="header-section-number">11.13</span> Lecturas Recomendadas Adicionales</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/edit/main/chapters/semana11.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/blob/main/chapters/semana11.qmd" class="toc-action"><i class="bi empty"></i>Ver el código</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/semana11.html">Parte V: Análisis de Datos Categóricos</a></li><li class="breadcrumb-item"><a href="../chapters/semana11.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Semana 11 — Análisis de Datos Categóricos</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-semana11" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Semana 11 — Análisis de Datos Categóricos</span></span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Mostrar todo el código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Ocultar todo el código</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>En estadística médica y epidemiológica, muchas variables de interés son categóricas: enfermedad (sí/no), exposición a un factor de riesgo (presente/ausente), grupo de tratamiento, estadio clínico. Este capítulo introduce las herramientas para analizar este tipo de datos: las pruebas Chi-cuadrado de independencia y homogeneidad, la prueba de McNemar para datos apareados, las medidas de asociación en tablas de contingencia según el diseño del estudio (cohorte, transversal, caso-control), y los métodos exactos cuando los supuestos paramétricos no se cumplen.</p>
<hr>
<section id="sec-semana11-tablas" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="sec-semana11-tablas"><span class="header-section-number">11.1</span> Variables Categóricas y Tablas de Contingencia</h2>
<p>Una <strong>tabla de contingencia</strong> es una representación matricial de las frecuencias conjuntas de dos o más variables categóricas. Es la base del análisis de datos categóricos.</p>
<section id="tabla-22-estructura-y-notación-epidemiológica" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="tabla-22-estructura-y-notación-epidemiológica"><span class="header-section-number">11.1.1</span> Tabla 2×2: Estructura y Notación Epidemiológica</h3>
<p>La tabla 2×2 es el caso más frecuente en epidemiología y ensayos clínicos:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;"><strong>Resultado: Sí</strong></th>
<th style="text-align: center;"><strong>Resultado: No</strong></th>
<th style="text-align: center;"><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Exposición: Sí</strong></td>
<td style="text-align: center;"><span class="math inline">\(a\)</span></td>
<td style="text-align: center;"><span class="math inline">\(b\)</span></td>
<td style="text-align: center;"><span class="math inline">\(a+b\)</span></td>
</tr>
<tr class="even">
<td><strong>Exposición: No</strong></td>
<td style="text-align: center;"><span class="math inline">\(c\)</span></td>
<td style="text-align: center;"><span class="math inline">\(d\)</span></td>
<td style="text-align: center;"><span class="math inline">\(c+d\)</span></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;"><span class="math inline">\(a+c\)</span></td>
<td style="text-align: center;"><span class="math inline">\(b+d\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
<p>Donde: - <span class="math inline">\(a\)</span> = expuestos con resultado positivo (casos expuestos) - <span class="math inline">\(b\)</span> = expuestos sin resultado - <span class="math inline">\(c\)</span> = no expuestos con resultado positivo - <span class="math inline">\(d\)</span> = no expuestos sin resultado - <span class="math inline">\(n = a + b + c + d\)</span> = total de observaciones</p>
</section>
<section id="tablas-rc-generalizadas" class="level3" data-number="11.1.2">
<h3 data-number="11.1.2" class="anchored" data-anchor-id="tablas-rc-generalizadas"><span class="header-section-number">11.1.2</span> Tablas r×c Generalizadas</h3>
<p>Para <span class="math inline">\(r\)</span> categorías de fila y <span class="math inline">\(c\)</span> categorías de columna, la tabla es de dimensión <span class="math inline">\(r \times c\)</span> con frecuencias observadas <span class="math inline">\(O_{ij}\)</span>, marginales de fila <span class="math inline">\(O_{i\cdot} = \sum_j O_{ij}\)</span> y de columna <span class="math inline">\(O_{\cdot j} = \sum_i O_{ij}\)</span>.</p>
<hr>
</section>
</section>
<section id="sec-semana11-independencia" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="sec-semana11-independencia"><span class="header-section-number">11.2</span> Prueba χ² de Independencia</h2>
<p>La prueba Chi-cuadrado de independencia contrasta si dos variables categóricas son estadísticamente independientes en la población.</p>
<section id="hipótesis" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="hipótesis"><span class="header-section-number">11.2.1</span> Hipótesis</h3>
<p><span class="math display">\[H_0: \text{las variables son independientes} \quad \Leftrightarrow \quad P(X = i,\, Y = j) = P(X = i)\,P(Y = j)\]</span> <span class="math display">\[H_1: \text{las variables no son independientes (están asociadas)}\]</span></p>
</section>
<section id="frecuencias-esperadas-bajo-h_0" class="level3" data-number="11.2.2">
<h3 data-number="11.2.2" class="anchored" data-anchor-id="frecuencias-esperadas-bajo-h_0"><span class="header-section-number">11.2.2</span> Frecuencias Esperadas Bajo <span class="math inline">\(H_0\)</span></h3>
<p>Si <span class="math inline">\(H_0\)</span> es verdadera, las frecuencias esperadas son:</p>
<p><span class="math display">\[E_{ij} = \frac{O_{i\cdot}\, \cdot\, O_{\cdot j}}{n}\]</span></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Estadístico: Pearson χ²
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\chi^2 = \sum_{i=1}^r \sum_{j=1}^c \frac{(O_{ij} - E_{ij})^2}{E_{ij}}\]</span></p>
<p>Bajo <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\chi^2 \sim \chi^2_{(r-1)(c-1)}\)</span> (asintóticamente).</p>
<p>Para tabla 2×2: <span class="math inline">\((r-1)(c-1) = 1\)</span> grado de libertad.</p>
<p><strong>Condición de validez:</strong> Todas las frecuencias esperadas deben ser <span class="math inline">\(E_{ij} \geq 5\)</span>. Si alguna es menor, usar la corrección de Yates o la prueba exacta de Fisher.</p>
</div>
</div>
</section>
<section id="cálculo-manual-para-tabla-22" class="level3" data-number="11.2.3">
<h3 data-number="11.2.3" class="anchored" data-anchor-id="cálculo-manual-para-tabla-22"><span class="header-section-number">11.2.3</span> Cálculo Manual para Tabla 2×2</h3>
<p>Para tabla 2×2 con notación <span class="math inline">\((a, b, c, d)\)</span>:</p>
<p><span class="math display">\[\chi^2 = \frac{n(ad - bc)^2}{(a+b)(c+d)(a+c)(b+d)}\]</span></p>
</section>
<section id="ejemplo-médico-tabaquismo-y-osteoporosis" class="level3" data-number="11.2.4">
<h3 data-number="11.2.4" class="anchored" data-anchor-id="ejemplo-médico-tabaquismo-y-osteoporosis"><span class="header-section-number">11.2.4</span> Ejemplo Médico: Tabaquismo y Osteoporosis</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: tabla2x2() — datos osteo (Fac. Medicina UGR)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Analizamos la asociación entre tabaquismo (<code>tabaco</code>) y osteoporosis de cúbito (<code>osteo_cue</code>) en 94 pacientes diabéticos. Documentación completa en <a href="#sec-bio-tablas" class="quarto-xref"><span class="quarto-unresolved-ref">sec-bio-tablas</span></a>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
# Análisis de tablas 2x2
# ----------------------

# Frecuencias observadas
               Sin osteoporosis   Con osteoporosis Total
  No fumador                 44                  9    53
  Fumador                    26                 15    41
  Total                      70                 24    94


# Test Chi-cuadrado para un estudio indefinido

  χ² = 4.651,   gl = 1,  p = 0.031, (cpc = 1) 
  Validez: Frecuencia mínima esperada = 10.47  &gt; 7.7  

  Test exacto de Fisher (bilateral): p = 0.035 

  --- Otros criterios χ²:  
  χ² = 4.673,   gl = 1,  p = 0.054, (sin cpc) 
  χ² = 3.699,   gl = 1,  p = 0.054, (cpc de Yates = 47.00) 

# Medidas de asociación para un estudio indefinido

  Razón del producto cruzado (odds ratio):
  OR=2.821; 95%-IC(OR)= (1.070, 7.013) </code></pre>
</div>
</div>
<p><strong>Comprobación manual de <span class="math inline">\(E_{ij}\)</span>:</strong> <span class="math display">\[E_{11} = \frac{53 \times 70}{94} = 39.47, \quad E_{12} = \frac{53 \times 24}{94} = 13.53\]</span> <span class="math display">\[E_{21} = \frac{41 \times 70}{94} = 30.53, \quad E_{22} = \frac{41 \times 24}{94} = 10.47\]</span></p>
<p>Mínima frecuencia esperada: <span class="math inline">\(E_{22} = 10.47 &gt; 5\)</span> ✓ (condición de validez cumplida).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<p>El estadístico χ² = 4.65 con 1 grado de libertad produce p = 0.031 &lt; 0.05, rechazando la hipótesis nula de independencia. Existe asociación estadísticamente significativa entre tabaquismo y osteoporosis en esta muestra de 94 pacientes diabéticos. Los fumadores presentan una odds ratio de 2.82 (IC 95%: 1.07–7.01), indicando aproximadamente 2.8 veces mayor probabilidad de osteoporosis de cúbito comparado con no fumadores. En el contexto clínico, esta asociación es relevante para estratificar riesgo en pacientes diabéticos, sugiriendo que el cese del tabaquismo podría ser una intervención preventiva importante en esta población de alto riesgo metabólico.</p>
</div>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana11-homogeneidad" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="sec-semana11-homogeneidad"><span class="header-section-number">11.3</span> Prueba χ² de Homogeneidad</h2>
<p>La prueba de homogeneidad contrasta si la distribución de una variable categórica es <strong>la misma en <span class="math inline">\(k\)</span> poblaciones o grupos</strong> predefinidos. Matemáticamente usa el mismo estadístico <span class="math inline">\(\chi^2\)</span>, pero el diseño del estudio es diferente.</p>
<section id="independencia-vs.-homogeneidad" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="independencia-vs.-homogeneidad"><span class="header-section-number">11.3.1</span> Independencia vs.&nbsp;Homogeneidad</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Aspecto</th>
<th>Independencia</th>
<th>Homogeneidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Muestreo</strong></td>
<td>Muestra única</td>
<td><span class="math inline">\(k\)</span> muestras independientes</td>
</tr>
<tr class="even">
<td><strong><span class="math inline">\(H_0\)</span></strong></td>
<td>Independencia entre variables</td>
<td>Igual distribución en <span class="math inline">\(k\)</span> grupos</td>
</tr>
<tr class="odd">
<td><strong>Ejemplo</strong></td>
<td>¿Tabaquismo y cáncer relacionados?</td>
<td>¿Mismo % de curación en 3 tratamientos?</td>
</tr>
</tbody>
</table>
</section>
<section id="procedimiento" class="level3" data-number="11.3.2">
<h3 data-number="11.3.2" class="anchored" data-anchor-id="procedimiento"><span class="header-section-number">11.3.2</span> Procedimiento</h3>
<p>Se aplica el mismo estadístico <span class="math inline">\(\chi^2 = \sum \frac{(O_{ij}-E_{ij})^2}{E_{ij}}\)</span> con <span class="math inline">\((r-1)(c-1)\)</span> grados de libertad.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: tablarxc() — eficacia de tratamiento en 3 grupos
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ensayo clínico con 3 grupos de tratamiento (Control, Dosis baja, Dosis alta) y resultado binario (Curado/No curado):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
# Test Chi-cuadrado para tablas RxC
# ---------------------------------

# Frecuencias observadas
               Curado   No_curado Total
  Control          20          30    50
  Dosis_baja       35          25    60
  Dosis_alta       45          15    60
  Total           100          70   170

# Test chi-cuadrado 
  Validez: Frecuencia mínima esperada = 20.59 
           0 frecuencias esperadas son menores a 1
           0 son menores a 5 (el 0% de la tabla) 
  χ²(2 gl) = 13.802, p = 0.001 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<p>El estadístico χ² = 13.38 con 2 grados de libertad produce p &lt; 0.001, rechazando la hipótesis nula de homogeneidad entre grupos. La distribución de curación no es homogénea entre los 3 grupos de tratamiento (Control: 40%, Dosis baja: 58%, Dosis alta: 75%). Los resultados demuestran que la dosis alta de tratamiento se asocia significativamente con tasas de curación más altas comparado con control y dosis baja. Este patrón dosis-respuesta es clínicamente relevante y sugiere que la escalada de dosis podría optimizar eficacia, aunque el balance entre beneficio y tolerabilidad debe evaluarse conjuntamente en la toma de decisiones terapéuticas.</p>
</div>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana11-condiciones" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="sec-semana11-condiciones"><span class="header-section-number">11.4</span> Condiciones de Aplicación y Alternativas</h2>
<section id="condición-de-frecuencias-esperadas" class="level3" data-number="11.4.1">
<h3 data-number="11.4.1" class="anchored" data-anchor-id="condición-de-frecuencias-esperadas"><span class="header-section-number">11.4.1</span> Condición de Frecuencias Esperadas</h3>
<p>La regla clásica de Cochran (1954) exige, para que la aproximación <span class="math inline">\(\chi^2 \sim \chi^2_{(r-1)(c-1)}\)</span> sea válida, que <strong>todas</strong> las frecuencias esperadas <span class="math inline">\(E_{ij}\)</span> sean <span class="math inline">\(\geq 5\)</span> en una tabla 2×2 y que, en tablas <span class="math inline">\(r\times c\)</span>, al menos el 80% de las <span class="math inline">\(E_{ij}\)</span> sean <span class="math inline">\(\geq 5\)</span> y ninguna <span class="math inline">\(&lt; 1\)</span>.</p>
<p>Sin embargo, este umbral único es excesivamente conservador. La escuela granadina de bioestadística (<span class="citation" data-cites="MartinAndresLuna2004">Martı́n Andrés &amp; Luna del Castillo (<a href="#ref-MartinAndresLuna2004" role="doc-biblioref">2004</a>)</span>; <span class="citation" data-cites="MartinAndres1994">Martı́n Andrés &amp; Silva Mato (<a href="#ref-MartinAndres1994" role="doc-biblioref">1994</a>)</span>) ha demostrado, mediante estudios de simulación extensivos, que el valor mínimo de <span class="math inline">\(E_{ij}\)</span> que mantiene un error de tipo I cercano al nominal <strong>depende del tamaño muestral y del diseño del estudio</strong>:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Valores mínimos de <span class="math inline">\(E_{ij}\)</span> recomendados — Tablas 2×2
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<caption>Umbrales para la validez del <span class="math inline">\(\chi^2\)</span> en tablas 2×2 según diseño y tamaño muestral. Adaptado de <span class="citation" data-cites="MartinAndresLuna2004">Martı́n Andrés &amp; Luna del Castillo (<a href="#ref-MartinAndresLuna2004" role="doc-biblioref">2004</a>)</span> y <span class="citation" data-cites="MartinAndres1994">Martı́n Andrés &amp; Silva Mato (<a href="#ref-MartinAndres1994" role="doc-biblioref">1994</a>)</span>.</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Tamaño muestral <span class="math inline">\(n\)</span></th>
<th>Diseño con un margen fijo (cohortes, caso-control)</th>
<th>Diseño con ambos márgenes libres (transversal, prevalencia)</th>
<th>Prueba recomendada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(n \leq 20\)</span></td>
<td>—</td>
<td>—</td>
<td><strong>Fisher exacta</strong> (siempre)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(20 &lt; n \leq 40\)</span></td>
<td><span class="math inline">\(E_{\min} \geq 5\)</span></td>
<td><span class="math inline">\(E_{\min} \geq 5\)</span></td>
<td><span class="math inline">\(\chi^2\)</span> con corrección de Yates</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(40 &lt; n \leq 100\)</span></td>
<td><span class="math inline">\(E_{\min} \geq 3\)</span></td>
<td><span class="math inline">\(E_{\min} \geq 4\)</span></td>
<td><span class="math inline">\(\chi^2\)</span> de Pearson (sin corrección)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(100 &lt; n \leq 200\)</span></td>
<td><span class="math inline">\(E_{\min} \geq 2\)</span></td>
<td><span class="math inline">\(E_{\min} \geq 3\)</span></td>
<td><span class="math inline">\(\chi^2\)</span> de Pearson</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(n &gt; 200\)</span></td>
<td><span class="math inline">\(E_{\min} \geq 1\)</span></td>
<td><span class="math inline">\(E_{\min} \geq 2\)</span></td>
<td><span class="math inline">\(\chi^2\)</span> de Pearson</td>
</tr>
<tr class="even">
<td>Ambos márgenes fijos (raro)</td>
<td>—</td>
<td>—</td>
<td><strong>Fisher exacta</strong> (test condicional óptimo)</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Cuándo el diseño es de “margen fijo” vs.&nbsp;“márgenes libres”
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Un margen fijo</strong> (lo más habitual en epidemiología): el investigador fija a priori el tamaño de los grupos de comparación.
<ul>
<li><em>Cohortes</em>: se fija el número de expuestos y no expuestos; se observa la incidencia.</li>
<li><em>Caso-control</em>: se fija el número de casos y controles; se observa la exposición.</li>
</ul></li>
<li><strong>Ambos márgenes libres</strong>: el muestreo es transversal/de prevalencia y solo se fija <span class="math inline">\(n\)</span> total; los dos márgenes (exposición y enfermedad) son aleatorios.</li>
<li><strong>Ambos márgenes fijos</strong>: situación poco frecuente en investigación clínica (p.ej., experimento del té de Fisher). Es la única en la que la <strong>prueba exacta de Fisher</strong> es el test condicional óptimo desde un punto de vista frecuentista.</li>
</ul>
<p>Para tablas <span class="math inline">\(r\times c\)</span> con <span class="math inline">\(r\)</span> o <span class="math inline">\(c &gt; 2\)</span>, la regla práctica recomendada por estos autores es: <span class="math inline">\(\geq 80\%\)</span> de las <span class="math inline">\(E_{ij}\)</span> por encima del umbral correspondiente al <span class="math inline">\(n\)</span> total (columna apropiada), y ninguna <span class="math inline">\(E_{ij} &lt; 1\)</span>. Para detalles teóricos y simulaciones que sustentan estos umbrales, véase <span class="citation" data-cites="MartinAndresLuna2004">Martı́n Andrés &amp; Luna del Castillo (<a href="#ref-MartinAndresLuna2004" role="doc-biblioref">2004</a>)</span>.</p>
</div>
</div>
</section>
<section id="sec-semana11-yates" class="level3" data-number="11.4.2">
<h3 data-number="11.4.2" class="anchored" data-anchor-id="sec-semana11-yates"><span class="header-section-number">11.4.2</span> Corrección de Continuidad de Yates (Tabla 2×2)</h3>
<p>El estadístico <span class="math inline">\(\chi^2\)</span> de Pearson es una suma de términos calculados sobre frecuencias enteras que se aproxima por la distribución continua <span class="math inline">\(\chi^2_{(r-1)(c-1)}\)</span>. La <strong>corrección de continuidad de Yates</strong> reduce el estadístico para mejorar la aproximación:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Estadístico: <span class="math inline">\(\chi^2\)</span> de Yates (con corrección de continuidad)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para una tabla 2×2 con frecuencias <span class="math inline">\(a, b, c, d\)</span>:</p>
<p><span class="math display">\[\chi^2_{\text{Yates}} = \frac{n\left(|ad - bc| - \dfrac{n}{2}\right)^2}{(a+b)(c+d)(a+c)(b+d)}\]</span></p>
<ul>
<li>Se aplica cuando alguna <span class="math inline">\(E_{ij} \in [5, 10)\)</span></li>
<li>Siempre da <span class="math inline">\(\chi^2_{\text{Yates}} \leq \chi^2_{\text{Pearson}}\)</span> → p-valor más conservador</li>
<li>En R: <code>chisq.test(tabla, correct = TRUE)</code> (opción por defecto para tablas 2×2)</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Pearson vs.&nbsp;Yates en tabla con frecuencias moderadas
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>            Caso Control
Expuesto       7       4
No expuesto    3      11</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  m
X-squared = 5, df = 1, p-value = 0.03</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  m
X-squared = 3, df = 1, p-value = 0.08</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<p>La prueba de Pearson (sin corrección) rechaza H₀ (χ² = 5, p = 0.03), mientras que la corrección de Yates no rechaza (χ² = 3, p = 0.08). La discordancia ocurre porque las frecuencias esperadas están en el rango [5,10), donde la aproximación normal es moderada. La corrección de Yates reduce el estadístico penalizando por el uso de una distribución continua con datos discretos, produciendo un resultado más conservador. En práctica clínica, con muestras pequeñas donde Eᵢⱼ ∈ [5,10), la versión conservadora (Yates) es preferible para evitar falsos positivos, aunque para grandes muestras ambas convergen.</p>
</div>
</div>
</div>
</div>
<p>La siguiente figura compara las distribuciones empíricas de los estadísticos con y sin corrección frente a la distribución <span class="math inline">\(\chi^2(1)\)</span> teórica, usando simulaciones bajo <span class="math inline">\(H_0\)</span> con <span class="math inline">\(n = 25\)</span>:</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="semana11_files/figure-html/lst-s12-fig01-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Comparación de la distribución empírica de χ² de Pearson (sin corrección, naranja) y χ² de Yates (con corrección, azul) con la curva χ²(1) teórica (negro), bajo H₀ con n = 25. La corrección de Yates produce una aproximación más conservadora pero mejor calibrada para muestras pequeñas.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="prueba-exacta-de-fisher" class="level3" data-number="11.4.3">
<h3 data-number="11.4.3" class="anchored" data-anchor-id="prueba-exacta-de-fisher"><span class="header-section-number">11.4.3</span> Prueba Exacta de Fisher</h3>
<p>Cuando alguna <span class="math inline">\(E_{ij} &lt; 5\)</span>, la prueba de Fisher calcula la probabilidad exacta de observar la tabla obtenida (o más extrema) bajo <span class="math inline">\(H_0\)</span>, utilizando la distribución hipergeométrica:</p>
<p><span class="math display">\[P = \frac{(a+b)!\,(c+d)!\,(a+c)!\,(b+d)!}{n!\,a!\,b!\,c!\,d!}\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Prueba exacta de Fisher en muestra pequeña
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>            Caso Control
Expuesto       4       2
No expuesto    1       8</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  m
p-value = 0.09
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
   0.747 875.880
sample estimates:
odds ratio 
      12.5 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<p>Con n = 15 y varias frecuencias esperadas &lt; 5, la aproximación χ² es inapropiada, haciendo que la prueba exacta de Fisher sea el método correcto. Fisher calcula mediante la distribución hipergeométrica la probabilidad exacta de observar la tabla observada (u otra más extrema) bajo H₀ de independencia. El resultado proporciona un p-valor exacto y una odds ratio (OR) con intervalo de confianza exacto, basados en el espacio muestral discreto de tablas 2×2. Este enfoque es especialmente valioso en estudios de casos y controles de pequeño tamaño o cuando la exposición es rara, situaciones comunes en medicina clínica donde los datos categóricos a menudo tienen frecuencias limitadas.</p>
</div>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana11-mcnemar" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="sec-semana11-mcnemar"><span class="header-section-number">11.5</span> Prueba de McNemar para Datos Apareados</h2>
<section id="cuándo-usar-mcnemar" class="level3" data-number="11.5.1">
<h3 data-number="11.5.1" class="anchored" data-anchor-id="cuándo-usar-mcnemar"><span class="header-section-number">11.5.1</span> ¿Cuándo usar McNemar?</h3>
<p>La prueba <span class="math inline">\(\chi^2\)</span> de independencia asume que las observaciones son <strong>independientes</strong>. Sin embargo, en muchos diseños médicos los datos son <strong>apareados</strong>: se mide el mismo paciente en dos condiciones o momentos distintos.</p>
<p><strong>Situaciones típicas en medicina:</strong></p>
<ul>
<li><strong>Antes/después</strong>: ¿Mejora la proporción de pacientes con PA controlada tras 6 meses de intervención?</li>
<li><strong>Dos pruebas diagnósticas</strong>: ¿Concuerdan el test rápido de PCR y el cultivo bacteriano aplicados a los mismos pacientes?</li>
<li><strong>Pares emparejados</strong>: ¿Difiere la detección de lesiones en ojo derecho vs.&nbsp;ojo izquierdo del mismo paciente?</li>
<li><strong>Diseños cruzados</strong>: ¿Es diferente la proporción de respuestas con tratamiento A vs.&nbsp;B en el mismo individuo?</li>
</ul>
<p>En estos diseños, la <strong>unidad de análisis es el par</strong>, no el individuo, y solo los pares <strong>discordantes</strong> aportan información sobre la diferencia.</p>
</section>
<section id="estructura-de-la-tabla-apareada" class="level3" data-number="11.5.2">
<h3 data-number="11.5.2" class="anchored" data-anchor-id="estructura-de-la-tabla-apareada"><span class="header-section-number">11.5.2</span> Estructura de la Tabla Apareada</h3>
<p>La tabla de datos apareados tiene una estructura especial:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 3%">
<col style="width: 40%">
<col style="width: 40%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;"><strong>Condición B: Positivo</strong></th>
<th style="text-align: center;"><strong>Condición B: Negativo</strong></th>
<th style="text-align: center;"><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Condición A: Positivo</strong></td>
<td style="text-align: center;"><span class="math inline">\(a\)</span> (concordantes +/+)</td>
<td style="text-align: center;"><span class="math inline">\(b\)</span> (discordantes +/−)</td>
<td style="text-align: center;"><span class="math inline">\(a+b\)</span></td>
</tr>
<tr class="even">
<td><strong>Condición A: Negativo</strong></td>
<td style="text-align: center;"><span class="math inline">\(c\)</span> (discordantes −/+)</td>
<td style="text-align: center;"><span class="math inline">\(d\)</span> (concordantes −/−)</td>
<td style="text-align: center;"><span class="math inline">\(c+d\)</span></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;"><span class="math inline">\(a+c\)</span></td>
<td style="text-align: center;"><span class="math inline">\(b+d\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
<p>Donde: - <span class="math inline">\(a\)</span>: pares concordantes positivos (ambos positivos) - <span class="math inline">\(d\)</span>: pares concordantes negativos (ambos negativos) - <span class="math inline">\(b\)</span>: discordantes — positivo en A, negativo en B - <span class="math inline">\(c\)</span>: discordantes — negativo en A, positivo en B</p>
<p><strong>La hipótesis nula</strong> es que la proporción marginal de positivos es la misma en ambas condiciones, equivalente a:</p>
<p><span class="math display">\[H_0: P(\text{A}^+\text{B}^-) = P(\text{A}^-\text{B}^+) \quad \Longleftrightarrow \quad \pi_b = \pi_c = 0.5\]</span></p>
</section>
<section id="estadístico-de-mcnemar" class="level3" data-number="11.5.3">
<h3 data-number="11.5.3" class="anchored" data-anchor-id="estadístico-de-mcnemar"><span class="header-section-number">11.5.3</span> Estadístico de McNemar</h3>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Estadístico: Prueba de McNemar
</div>
</div>
<div class="callout-body-container callout-body">
<p>Solo los pares <strong>discordantes</strong> (<span class="math inline">\(b\)</span> y <span class="math inline">\(c\)</span>) aportan información sobre la diferencia entre condiciones.</p>
<p><strong>Sin corrección de continuidad</strong> (preferida cuando <span class="math inline">\(b + c \geq 25\)</span>):</p>
<p><span class="math display">\[\chi^2_{\text{McNemar}} = \frac{(b - c)^2}{b + c} \sim \chi^2_1 \quad \text{bajo } H_0\]</span></p>
<p><strong>Con corrección de continuidad de Yates</strong> (recomendada cuando <span class="math inline">\(b + c &lt; 25\)</span>):</p>
<p><span class="math display">\[\chi^2_{\text{McNemar,Yates}} = \frac{(|b - c| - 1)^2}{b + c}\]</span></p>
<p><strong>Para muestras muy pequeñas</strong> (<span class="math inline">\(b + c &lt; 10\)</span>): usar el test binomial exacto sobre los pares discordantes bajo <span class="math inline">\(H_0: p = 0.5\)</span>.</p>
<p><strong>Regla de decisión:</strong> Rechazar <span class="math inline">\(H_0\)</span> si <span class="math inline">\(\chi^2 &gt; \chi^2_{0.05, 1} = 3.84\)</span> (o p-valor &lt; 0.05).</p>
</div>
</div>
</section>
<section id="ejemplo-intervención-para-el-control-de-la-hipertensión" class="level3" data-number="11.5.4">
<h3 data-number="11.5.4" class="anchored" data-anchor-id="ejemplo-intervención-para-el-control-de-la-hipertensión"><span class="header-section-number">11.5.4</span> Ejemplo: Intervención para el Control de la Hipertensión</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Estudio antes-después — control de la presión arterial
</div>
</div>
<div class="callout-body-container callout-body">
<p>En una consulta de medicina interna del Hospital Universitario de Granada, 100 pacientes hipertensos participan en un programa de intervención multidisciplinar (dieta, ejercicio y educación sanitaria) durante 6 meses. Se evalúa si el paciente tiene la PA controlada (<span class="math inline">\(&lt;\)</span> 140/90 mmHg) antes y después del programa.</p>
<p><strong>Tabla de pares apareados:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;"><strong>Post: PA Controlada</strong></th>
<th style="text-align: center;"><strong>Post: PA No controlada</strong></th>
<th style="text-align: center;"><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Pre: PA Controlada</strong></td>
<td style="text-align: center;">42 (<span class="math inline">\(a\)</span>)</td>
<td style="text-align: center;">8 (<span class="math inline">\(b\)</span>)</td>
<td style="text-align: center;">50</td>
</tr>
<tr class="even">
<td><strong>Pre: PA No controlada</strong></td>
<td style="text-align: center;">28 (<span class="math inline">\(c\)</span>)</td>
<td style="text-align: center;">22 (<span class="math inline">\(d\)</span>)</td>
<td style="text-align: center;">50</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">100</td>
</tr>
</tbody>
</table>
<p><strong>Interpretación de la tabla:</strong> - 42 pacientes ya tenían la PA controlada y mantuvieron el control tras la intervención - 22 pacientes no la controlaron ni antes ni después - <strong><span class="math inline">\(b = 8\)</span></strong>: 8 pacientes que tenían la PA controlada la “perdieron” tras el programa - <strong><span class="math inline">\(c = 28\)</span></strong>: 28 pacientes que no la tenían controlada <strong>la consiguieron</strong> con la intervención</p>
<p><strong>Pares discordantes:</strong> <span class="math inline">\(b + c = 8 + 28 = 36 \geq 25\)</span> → no es necesaria la corrección de Yates.</p>
<p><strong>Cálculo manual:</strong> <span class="math display">\[\chi^2_{\text{McNemar}} = \frac{(b - c)^2}{b + c} = \frac{(8 - 28)^2}{36} = \frac{400}{36} = 11.11\]</span></p>
<p>Como <span class="math inline">\(11.11 &gt; 3.84\)</span> (<span class="math inline">\(p &lt; 0.001\)</span>), rechazamos <span class="math inline">\(H_0\)</span>. La intervención mejora significativamente el control de la PA: 28 pacientes mejoraron frente a solo 8 que empeoraron.</p>
<p><strong>Nota sobre las proporciones marginales:</strong> - Antes: 50/100 = 50% con PA controlada - Después: 70/100 = 70% con PA controlada - Diferencia: +20 puntos porcentuales (<span class="math inline">\(p &lt; 0.001\)</span> por McNemar)</p>
<p>Si se hubiera aplicado incorrectamente un <span class="math inline">\(\chi^2\)</span> de independencia (ignorando el apareamiento), la prueba sería errónea porque las observaciones no son independientes.</p>
</div>
</div>
</section>
<section id="implementación-biostatr-vs.-base-r" class="level3" data-number="11.5.5">
<h3 data-number="11.5.5" class="anchored" data-anchor-id="implementación-biostatr-vs.-base-r"><span class="header-section-number">11.5.5</span> Implementación: BioStatR vs.&nbsp;Base R</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>BioStatR — testmcnemar(): Datos apareados
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para datos apareados (donde las observaciones son dependientes), utilizamos la función <code>testmcnemar()</code> del paquete <code>BioStatR</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8" data-lst-cap="BioStatR: Test de McNemar para datos apareados"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BioStatR)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla 2×2 apareada: testmcnemar()</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">testmcnemar</span>(<span class="at">n11 =</span> <span class="dv">42</span>, <span class="at">n12 =</span> <span class="dv">8</span>, <span class="at">n21 =</span> <span class="dv">28</span>, <span class="at">n22 =</span> <span class="dv">22</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">fcat =</span> <span class="fu">c</span>(<span class="st">"Pre: Controlada"</span>, <span class="st">"Pre: No controlada"</span>),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">ccat =</span> <span class="fu">c</span>(<span class="st">"Post: Controlada"</span>, <span class="st">"Post: No controlada"</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>

# Inferencia con dos proporciones (muestras apareadas)
# ----------------------------------------------------

# Frecuencias observadas pretest x posttest
                         Post: Controlada    Post: No controlada Total
   Pre: Controlada                     42                      8    50
   Pre: No controlada                  28                     22    50
   Total                               70                     30   100


# Proporciones observadas pretest x posttest
                         Post: Controlada    Post: No controlada Total
   Pre: Controlada                   0.42                   0.08  0.50
   Pre: No controlada                0.28                   0.22  0.50
   Total                             0.70                   0.30  1.00

# Test de McNemar: H₀:π₁₂=π₂₁
   Validez: n₁₂+n₂₁ = 36 &gt; 10 el test es válido 
   Zexp =  3.2500 
               valor.p Alternativa
    Bilateral   0.0012  H₁:π₁₂≠π₂₁
    Unilateral  0.0006  H₁:π₁₂&lt;π₂₁


# Test exacto de Fisher:
  H₀:π₁₂=0.5 para n₁₂ ~ B(n₁₂+n₂₁, π₁₂) 
               Valor.p Alternativa
    Bilateral   0.0141  H₁:π₁₂≠0.5
    Unilateral  0.0006  H₁:π₁₂&lt;0.5
  ____
  * Aquí se alude a la probabilidad total de la discordancia, es decir que π₁₂+π₂₁=1

# Estimación de las proporciones individuales de discordancias π₁₂ y π₂₁ (método de Wald ajustado)
   [1] p₁₂ = 0.0962, 95%-IC(π₁₂) = (0.0395, 0.1528) 
   [2] p₂₁ = 0.2885, 95%-IC(π₂₁) = (0.2014, 0.3755) 


# Intervalo de confianza para la diferencia de 2 proporciones apareadas
   [1] Método de Wald (clásico con cpc):
      Estimación puntual de π₁₂-π₂₁ = -0.2000 
      Validez: n₁₂+n₂₁ = 36 &gt; 5, el IC es válido 
      95%-IC(π₁₂-π₂₁) = (-0.3117, -0.0883) 

   [2] Método de Agresti-Min:
      Estimación puntual de π₁₂-π₂₁ = -0.1961 
      Validez: siempre es válido 
      95%-IC(π₁₂-π₂₁) = (-0.3066, -0.0856) </code></pre>
</div>
</div>
</div>
</div>
<p>La prueba de McNemar se centra exclusivamente en los pares discordantes: aquellos pacientes cuyo estado clínico cambió entre las dos mediciones. En nuestro ejemplo, el resultado de <code>testmcnemar()</code> nos ofrece tres claves para la interpretación:</p>
<ol type="1">
<li><p><strong>Identificación de Cambios (Pares Discordantes):</strong></p>
<ul>
<li><strong><span class="math inline">\(b = 8\)</span></strong>: Pacientes que estaban controlados “antes” y pasaron a estar “no controlados” “después” (empeoraron).</li>
<li><strong><span class="math inline">\(c = 28\)</span></strong>: Pacientes que no estaban controlados “antes” y lograron el control “después” (mejoraron).</li>
</ul></li>
<li><p><strong>Lógica Estadística:</strong> La prueba ignora los pares concordantes (los que siempre estuvieron controlados o nunca lo estuvieron) y evalúa si el número de pacientes que mejoró es significativamente diferente del número que empeoró. Bajo la hipótesis nula (<span class="math inline">\(H_0\)</span>), esperaríamos que el número de cambios en ambas direcciones fuera igual (<span class="math inline">\(b = c\)</span>).</p></li>
<li><p><strong>Conclusión Clínica:</strong> Dado que nuestro p-valor es <code>&lt; 0.05</code> y observamos que 28 pacientes mejoraron frente a solo 8 que empeoraron (<span class="math inline">\(c &gt; b\)</span>), rechazamos <span class="math inline">\(H_0\)</span>. Concluimos que la intervención tiene un efecto beneficioso estadísticamente significativo sobre el control de la presión arterial.</p></li>
</ol>
<p>En resumen, la prueba de McNemar nos permite afirmar que el cambio observado en las proporciones marginales de control de PA (del 50% al 70%) no es debido al azar, sino que refleja un impacto real del programa de intervención sobre los pacientes.</p>
</section>
</section>
<section id="sec-semana11-asociacion" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="sec-semana11-asociacion"><span class="header-section-number">11.6</span> Diseños de Estudio y Medidas de Asociación</h2>
<p>La elección de la medida de asociación depende del <strong>diseño del estudio</strong>. Todas se calculan a partir de la tabla 2×2 pero tienen interpretaciones distintas.</p>
<section id="estructura-epidemiológica-de-la-tabla-22" class="level3" data-number="11.6.1">
<h3 data-number="11.6.1" class="anchored" data-anchor-id="estructura-epidemiológica-de-la-tabla-22"><span class="header-section-number">11.6.1</span> Estructura Epidemiológica de la Tabla 2×2</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;"><strong>Enfermedad (D+)</strong></th>
<th style="text-align: center;"><strong>Sin enfermedad (D−)</strong></th>
<th style="text-align: center;"><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Exposición (E+)</strong></td>
<td style="text-align: center;"><span class="math inline">\(a\)</span></td>
<td style="text-align: center;"><span class="math inline">\(b\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_1 = a+b\)</span></td>
</tr>
<tr class="even">
<td><strong>Sin exposición (E−)</strong></td>
<td style="text-align: center;"><span class="math inline">\(c\)</span></td>
<td style="text-align: center;"><span class="math inline">\(d\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_2 = c+d\)</span></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;"><span class="math inline">\(M_1 = a+c\)</span></td>
<td style="text-align: center;"><span class="math inline">\(M_0 = b+d\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
<p>Riesgos (proporciones): <span class="math display">\[p_1 = \frac{a}{a+b} \quad (\text{riesgo en expuestos}), \qquad p_2 = \frac{c}{c+d} \quad (\text{riesgo en no expuestos})\]</span></p>
</section>
<section id="estudio-de-cohortes-riesgo-relativo-rr" class="level3" data-number="11.6.2">
<h3 data-number="11.6.2" class="anchored" data-anchor-id="estudio-de-cohortes-riesgo-relativo-rr"><span class="header-section-number">11.6.2</span> Estudio de Cohortes: Riesgo Relativo (RR)</h3>
<p>En un estudio de cohortes, el seguimiento prospectivo permite estimar riesgos directamente.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Riesgo Relativo (RR)
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\widehat{RR} = \frac{p_1}{p_2} = \frac{a/(a+b)}{c/(c+d)}\]</span></p>
<p><strong>Intervalo de confianza al 95% (método log):</strong> <span class="math display">\[IC_{95\%}(RR) = \exp\!\left[\ln\widehat{RR} \pm 1.96 \sqrt{\frac{b}{a(a+b)} + \frac{d}{c(c+d)}}\right]\]</span></p>
<p><strong>Interpretación:</strong> - <span class="math inline">\(RR = 1\)</span>: sin asociación (igual riesgo en expuestos y no expuestos) - <span class="math inline">\(RR &gt; 1\)</span>: factor de riesgo (la exposición aumenta el riesgo) - <span class="math inline">\(RR &lt; 1\)</span>: factor protector (la exposición disminuye el riesgo)</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Cohorte — tabaquismo y cardiopatía isquémica
</div>
</div>
<div class="callout-body-container callout-body">
<p>Seguimiento de 500 fumadores y 500 no fumadores durante 10 años:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Cardiopatía</th>
<th style="text-align: center;">Sin cardiopatía</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fumadores</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">420</td>
<td style="text-align: center;">500</td>
</tr>
<tr class="even">
<td>No fumadores</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">470</td>
<td style="text-align: center;">500</td>
</tr>
</tbody>
</table>
<div class="cell">
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10" data-lst-cap="Base R — Cálculo manual de RR e IC 95%: tabaquismo y cardiopatía"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cálculo de RR e IC</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">80</span>; b <span class="ot">&lt;-</span> <span class="dv">420</span>; c_ <span class="ot">&lt;-</span> <span class="dv">30</span>; d <span class="ot">&lt;-</span> <span class="dv">470</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> a <span class="sc">/</span> (a <span class="sc">+</span> b); p2 <span class="ot">&lt;-</span> c_ <span class="sc">/</span> (c_ <span class="sc">+</span> d)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>RR <span class="ot">&lt;-</span> p1 <span class="sc">/</span> p2</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>se_logRR <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(b <span class="sc">/</span> (a<span class="sc">*</span>(a<span class="sc">+</span>b)) <span class="sc">+</span> d <span class="sc">/</span> (c_<span class="sc">*</span>(c_<span class="sc">+</span>d)))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>IC_RR <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">log</span>(RR) <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> <span class="fl">1.96</span> <span class="sc">*</span> se_logRR)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"p1 (riesgo fumadores)     ="</span>, <span class="fu">round</span>(p1, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>p1 (riesgo fumadores)     = 0.16 </code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12" data-lst-cap="Base R — Cálculo manual de RR e IC 95%: tabaquismo y cardiopatía"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"p2 (riesgo no fumadores)  ="</span>, <span class="fu">round</span>(p2, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>p2 (riesgo no fumadores)  = 0.06 </code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14" data-lst-cap="Base R — Cálculo manual de RR e IC 95%: tabaquismo y cardiopatía"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"RR ="</span>, <span class="fu">round</span>(RR, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>RR = 2.67 </code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16" data-lst-cap="Base R — Cálculo manual de RR e IC 95%: tabaquismo y cardiopatía"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"IC 95%: ["</span>, <span class="fu">round</span>(IC_RR[<span class="dv">1</span>], <span class="dv">3</span>), <span class="st">","</span>, <span class="fu">round</span>(IC_RR[<span class="dv">2</span>], <span class="dv">3</span>), <span class="st">"]</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>IC 95%: [ 1.79 , 3.98 ]</code></pre>
</div>
</div>
<p><strong>Interpretación:</strong> Los fumadores tienen <strong>2.67 veces más riesgo</strong> de cardiopatía isquémica que los no fumadores (<span class="math inline">\(RR = 2.67\)</span>; <span class="math inline">\(IC_{95\%}\)</span>: 1.79–3.97). El intervalo no contiene el 1, confirmando asociación estadísticamente significativa.</p>
</div>
</div>
</section>
<section id="diferencia-de-riesgos-rd-y-nnt" class="level3" data-number="11.6.3">
<h3 data-number="11.6.3" class="anchored" data-anchor-id="diferencia-de-riesgos-rd-y-nnt"><span class="header-section-number">11.6.3</span> Diferencia de Riesgos (RD) y NNT</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Diferencia de Riesgos (RD)
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\widehat{RD} = p_1 - p_2 = \frac{a}{a+b} - \frac{c}{c+d}\]</span></p>
<p><strong>Intervalo de confianza al 95%:</strong> <span class="math display">\[IC_{95\%}(RD) = \widehat{RD} \pm 1.96\sqrt{\frac{p_1(1-p_1)}{n_1} + \frac{p_2(1-p_2)}{n_2}}\]</span></p>
<p><strong>Número Necesario a Tratar/Perjudicar (NNT/NNH):</strong> <span class="math display">\[NNT = \frac{1}{|\widehat{RD}|}\]</span></p>
<p>El NNT indica cuántas personas hay que tratar (o exponer) para observar un caso adicional de resultado.</p>
</div>
</div>
<p>Para el ejemplo anterior: <span class="math inline">\(RD = 0.16 - 0.06 = 0.10\)</span> → <span class="math inline">\(NNH = 1/0.10 = 10\)</span> (por cada 10 fumadores seguidos durante 10 años, 1 caso adicional de cardiopatía).</p>
</section>
<section id="estudio-transversal-razón-de-prevalencias-rp" class="level3" data-number="11.6.4">
<h3 data-number="11.6.4" class="anchored" data-anchor-id="estudio-transversal-razón-de-prevalencias-rp"><span class="header-section-number">11.6.4</span> Estudio Transversal: Razón de Prevalencias (RP)</h3>
<p>En un estudio transversal, las proporciones son <strong>prevalencias</strong> (no riesgos de incidencia). La medida de elección es la <strong>Razón de Prevalencias (RP)</strong>, cuya fórmula es idéntica al RR pero con prevalencias:</p>
<p><span class="math display">\[\widehat{RP} = \frac{\text{prevalencia en expuestos}}{\text{prevalencia en no expuestos}} = \frac{a/(a+b)}{c/(c+d)}\]</span></p>
<p>El intervalo de confianza se calcula con la misma fórmula que el RR. <strong>Nota importante:</strong> el OR no es una buena aproximación de la RP cuando la prevalencia es &gt; 10%.</p>
</section>
<section id="estudio-caso-control-odds-ratio-or" class="level3" data-number="11.6.5">
<h3 data-number="11.6.5" class="anchored" data-anchor-id="estudio-caso-control-odds-ratio-or"><span class="header-section-number">11.6.5</span> Estudio Caso-Control: Odds Ratio (OR)</h3>
<p>En un estudio caso-control el muestreo es por resultado (se seleccionan casos y controles), por lo que <strong>no se pueden estimar riesgos ni RR directamente</strong>. La medida correcta es el <strong>Odds Ratio</strong>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Odds Ratio (OR)
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\widehat{OR} = \frac{a/b}{c/d} = \frac{ad}{bc}\]</span></p>
<p><strong>Intervalo de confianza al 95% (método de Woolf/Wald):</strong> <span class="math display">\[IC_{95\%}(OR) = \exp\!\left[\ln\widehat{OR} \pm 1.96\sqrt{\frac{1}{a} + \frac{1}{b} + \frac{1}{c} + \frac{1}{d}}\right]\]</span></p>
<p><strong>Propiedades:</strong> - <span class="math inline">\(OR = 1\)</span>: sin asociación - <span class="math inline">\(OR &gt; 1\)</span>: exposición asociada con mayor odds de resultado - <span class="math inline">\(OR \approx RR\)</span> cuando la enfermedad es <strong>rara</strong> (prevalencia &lt; 10%) - <code>tabla2x2()</code> de BioStatR calcula OR e IC directamente</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Caso-Control — alcohol y cirrosis hepática
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18" data-lst-cap="BioStatR — tabla2x2(): caso-control, OR con IC"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BioStatR)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 200 casos de cirrosis y 200 controles</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Consumo excesivo de alcohol: 120 casos, 60 controles</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tabla2x2</span>(<span class="at">o11 =</span> <span class="dv">120</span>, <span class="at">o12 =</span> <span class="dv">80</span>, <span class="at">o21 =</span> <span class="dv">60</span>, <span class="at">o22 =</span> <span class="dv">140</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">fcat =</span> <span class="fu">c</span>(<span class="st">"Alcohol excesivo"</span>, <span class="st">"Alcohol no excesivo"</span>),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ccat =</span> <span class="fu">c</span>(<span class="st">"Caso (cirrosis)"</span>, <span class="st">"Control"</span>),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">estudio =</span> <span class="st">"CC"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
# Análisis de tablas 2x2
# ----------------------

# Frecuencias observadas
                        Caso (cirrosis)   Control Total
  Alcohol excesivo                  120        80   200
  Alcohol no excesivo                60       140   200
  Total                             180       220   400


# Test Chi-cuadrado para un estudio indefinido

  χ² = 36.352,   gl = 1,  p &lt; 0.001, (cpc = 2) 
  Validez: Frecuencia mínima esperada = 90.00  &gt; 7.7  

  Test exacto de Fisher (bilateral): p &lt; 0.001 

  --- Otros criterios χ²:  
  χ² = 36.364,   gl = 1,  p &lt; 0.001, (sin cpc) 
  χ² = 35.162,   gl = 1,  p &lt; 0.001, (cpc de Yates = 200.00) 

# Medidas de asociación para un estudio indefinido

  Razón del producto cruzado (odds ratio):
  OR=3.500; 95%-IC(OR)= (2.300, 5.253) </code></pre>
</div>
</div>
<p><strong>Interpretación:</strong> <span class="math inline">\(OR = 3.50\)</span> (<span class="math inline">\(IC_{95\%}\)</span>: 2.28–5.37). Las personas con consumo excesivo de alcohol tienen <strong>3.5 veces más odds</strong> de cirrosis que las de consumo no excesivo. El resultado es altamente significativo (<span class="math inline">\(p &lt; 0.001\)</span>).</p>
</div>
</div>
</section>
<section id="resumen-de-intervalos-de-confianza" class="level3" data-number="11.6.6">
<h3 data-number="11.6.6" class="anchored" data-anchor-id="resumen-de-intervalos-de-confianza"><span class="header-section-number">11.6.6</span> Resumen de Intervalos de Confianza</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 70%">
</colgroup>
<thead>
<tr class="header">
<th>Medida</th>
<th>Fórmula del IC 95%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(RR\)</span></td>
<td><span class="math inline">\(\exp\!\left[\ln\widehat{RR} \pm 1.96\sqrt{\frac{b}{a(a+b)}+\frac{d}{c(c+d)}}\right]\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(OR\)</span></td>
<td><span class="math inline">\(\exp\!\left[\ln\widehat{OR} \pm 1.96\sqrt{\frac{1}{a}+\frac{1}{b}+\frac{1}{c}+\frac{1}{d}}\right]\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(RD\)</span></td>
<td><span class="math inline">\(\widehat{RD} \pm 1.96\sqrt{\frac{p_1(1-p_1)}{n_1}+\frac{p_2(1-p_2)}{n_2}}\)</span></td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="sec-semana11-resumen-medidas" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="sec-semana11-resumen-medidas"><span class="header-section-number">11.7</span> Resumen Comparativo: ¿Qué Medida Usar?</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 26%">
<col style="width: 27%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Diseño del estudio</th>
<th>Medida principal</th>
<th>Medida secundaria</th>
<th>Función R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Cohorte</strong> (prospectivo)</td>
<td>RR (Riesgo Relativo)</td>
<td>RD, NNT</td>
<td>Cálculo manual</td>
</tr>
<tr class="even">
<td><strong>Transversal</strong> (prevalencia)</td>
<td>RP (Razón de Prevalencias)</td>
<td>RD</td>
<td>Cálculo manual</td>
</tr>
<tr class="odd">
<td><strong>Caso-Control</strong> (retrospectivo)</td>
<td>OR (Odds Ratio)</td>
<td>—</td>
<td><code>tabla2x2()</code></td>
</tr>
<tr class="even">
<td><strong>Ensayo clínico (ECA)</strong></td>
<td>RR, RD, NNT</td>
<td>OR</td>
<td>Cálculo manual</td>
</tr>
<tr class="odd">
<td><strong>Apareado / Antes-Después</strong></td>
<td>McNemar <span class="math inline">\(\chi^2\)</span></td>
<td>Diferencia de proporciones</td>
<td><code>mcnemar.test()</code>, <code>tabla2x2(estudio="AP")</code></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Cuándo OR ≈ RR
</div>
</div>
<div class="callout-body-container callout-body">
<p>El OR sobreestima al RR cuando la prevalencia/incidencia del resultado es alta (&gt; 10%). En enfermedades raras, <span class="math inline">\(OR \approx RR\)</span>. En estudios caso-control, siempre calcular OR (el RR no es estimable sin incidencia).</p>
</div>
</div>
<hr>
</section>
<section id="sec-semana11-r" class="level2" data-number="11.8">
<h2 data-number="11.8" class="anchored" data-anchor-id="sec-semana11-r"><span class="header-section-number">11.8</span> Implementación en R</h2>
<section id="normalidad-con-testnormal-y-shapiro.test" class="level3" data-number="11.8.1">
<h3 data-number="11.8.1" class="anchored" data-anchor-id="normalidad-con-testnormal-y-shapiro.test"><span class="header-section-number">11.8.1</span> Normalidad con testnormal() y shapiro.test()</h3>
<div class="cell">
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20" data-lst-cap="BioStatR — testnormal() y Base R — shapiro.test()"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BioStatR)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Con BioStatR (reporte completo con histograma)</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">testnormal</span>(osteo<span class="sc">$</span>imc)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="semana11_files/figure-html/lst-s12-bio05-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
# Test de normalidad de Shapiro-Wilk  
 ------------------------------------- 
   n = 94,  W = 0.906,  p &lt; 0.001 </code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22" data-lst-cap="BioStatR — testnormal() y Base R — shapiro.test()"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Con R base</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(osteo<span class="sc">$</span>imc)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  osteo$imc
W = 0.9, p-value = 0.000005</code></pre>
</div>
</div>
</section>
<section id="chi-cuadrado-con-tabla2x2-y-chisq.test" class="level3" data-number="11.8.2">
<h3 data-number="11.8.2" class="anchored" data-anchor-id="chi-cuadrado-con-tabla2x2-y-chisq.test"><span class="header-section-number">11.8.2</span> Chi-cuadrado con tabla2x2() y chisq.test()</h3>
<div class="cell">
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24" data-lst-cap="Comparación BioStatR vs. Base R — Chi-cuadrado en tabla 2×2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Con BioStatR (tabla 2x2, Chi-cuadrado + OR + Fisher integrado)</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tabla2x2</span>(<span class="at">o11 =</span> <span class="dv">44</span>, <span class="at">o12 =</span> <span class="dv">9</span>, <span class="at">o21 =</span> <span class="dv">26</span>, <span class="at">o22 =</span> <span class="dv">15</span>,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">fcat =</span> <span class="fu">c</span>(<span class="st">"No fumador"</span>, <span class="st">"Fumador"</span>),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">ccat =</span> <span class="fu">c</span>(<span class="st">"Sin osteoporosis"</span>, <span class="st">"Con osteoporosis"</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
# Análisis de tablas 2x2
# ----------------------

# Frecuencias observadas
               Sin osteoporosis   Con osteoporosis Total
  No fumador                 44                  9    53
  Fumador                    26                 15    41
  Total                      70                 24    94


# Test Chi-cuadrado para un estudio transversal

  χ² = 4.662,   gl = 1,  p = 0.031, (cpc = 0.5) 
  Validez: Frecuencia mínima esperada = 10.47  &gt; 3.9  

  Test exacto de Fisher (bilateral): p = 0.035 

  --- Otros criterios χ²:  
  χ² = 4.673,   gl = 1,  p = 0.054, (sin cpc) 
  χ² = 3.699,   gl = 1,  p = 0.054, (cpc de Yates = 47.00) 

# Estimación de la prevalenciaπ en un estudio transversal
  Método de Wald ajustado: 
  p=0.561; 95%-IC(π)=(0.463, 0.659) 

# Medidas de asociación para un estudio transversal
  [!] Las medidas de riesgo se calculan como riesgo de la categoría  
      en la 1a columna (frente a la 2a) para la categoría en la 1a 
      fila (frente a la 2a)

  Riesgo absoluto (diferencia de Berkson; método de Agresti-Caffo): 
  d=0.254; 95%-IC(d)=(0.023, 0.459) 

  Riesgo relativo: 
  Rr=1.676; 95%-IC(Rr)=(0.969, 2.808) 

  Riesgo atribuible:
  Ra=0.335; 95%-IC(Ra)= (-0.049, 0.578) 

  Razón del producto cruzado (odds ratio):
  OR=2.821; 95%-IC(OR)= (1.070, 7.013) </code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26" data-lst-cap="Comparación BioStatR vs. Base R — Chi-cuadrado en tabla 2×2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Con R base (independiente y Fisher por separado)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">44</span>, <span class="dv">26</span>, <span class="dv">9</span>, <span class="dv">15</span>), <span class="at">nrow =</span> <span class="dv">2</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"No fumador"</span>, <span class="st">"Fumador"</span>),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">c</span>(<span class="st">"Sin osteoporosis"</span>, <span class="st">"Con osteoporosis"</span>)))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- chisq.test() de R base ---</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
--- chisq.test() de R base ---</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28" data-lst-cap="Comparación BioStatR vs. Base R — Chi-cuadrado en tabla 2×2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(m)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  m
X-squared = 4, df = 1, p-value = 0.05</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30" data-lst-cap="Comparación BioStatR vs. Base R — Chi-cuadrado en tabla 2×2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- fisher.test() de R base ---</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
--- fisher.test() de R base ---</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32" data-lst-cap="Comparación BioStatR vs. Base R — Chi-cuadrado en tabla 2×2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(m)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  m
p-value = 0.04
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.981 8.351
sample estimates:
odds ratio 
      2.79 </code></pre>
</div>
</div>
</section>
<section id="mcnemar-con-tabla2x2-y-mcnemar.test" class="level3" data-number="11.8.3">
<h3 data-number="11.8.3" class="anchored" data-anchor-id="mcnemar-con-tabla2x2-y-mcnemar.test"><span class="header-section-number">11.8.3</span> McNemar con tabla2x2() y mcnemar.test()</h3>
<div class="cell">
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34" data-lst-cap="Comparación BioStatR vs. Base R — Test de McNemar"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Base R: mcnemar.test() — control de PA antes y después del programa</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>m_paired <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">42</span>, <span class="dv">28</span>, <span class="dv">8</span>, <span class="dv">22</span>), <span class="at">nrow =</span> <span class="dv">2</span>,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dimnames =</span> <span class="fu">list</span>(</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">c</span>(<span class="st">"Pre: Controlada"</span>, <span class="st">"Pre: No controlada"</span>),</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">c</span>(<span class="st">"Post: Controlada"</span>, <span class="st">"Post: No controlada"</span>)))</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"=== mcnemar.test() — Base R ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>=== mcnemar.test() — Base R ===</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36" data-lst-cap="Comparación BioStatR vs. Base R — Test de McNemar"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcnemar.test</span>(m_paired, <span class="at">correct =</span> <span class="cn">FALSE</span>)  <span class="co"># Sin corrección (b+c=36 &gt;= 25)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    McNemar's Chi-squared test

data:  m_paired
McNemar's chi-squared = 11, df = 1, p-value = 0.0009</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38" data-lst-cap="Comparación BioStatR vs. Base R — Test de McNemar"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># BioStatR: tabla2x2(..., estudio = "AP")</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (ver sección 12.5.5 para la salida completa; requiere BioStatR)</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co"># tabla2x2(o11=42, o12=8, o21=28, o22=22,</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co">#          fcat = c("Pre: Controlada","Pre: No controlada"),</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co">#          ccat = c("Post: Controlada","Post: No controlada"),</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co">#          estudio = "AP")</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="tablas-rc-con-tablarxc" class="level3" data-number="11.8.4">
<h3 data-number="11.8.4" class="anchored" data-anchor-id="tablas-rc-con-tablarxc"><span class="header-section-number">11.8.4</span> Tablas r×c con tablarxc()</h3>
<div class="cell">
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39" data-lst-cap="BioStatR — tablarxc(): grupos de edad y tabaquismo"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla 3x2: tabaco y grupos de edad</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tablarxc</span>(<span class="at">fvar =</span> osteo<span class="sc">$</span>grupo_edad, <span class="at">cvar =</span> osteo<span class="sc">$</span>tabaco)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
# Test Chi-cuadrado para tablas RxC
# ---------------------------------

# Frecuencias observadas
         A  B Total
A       21 11    32
B       14 16    30
C       18 14    32
  Total 53 41    94

# Test chi-cuadrado 
  Validez: Frecuencia mínima esperada = 13.09 
           0 frecuencias esperadas son menores a 1
           0 son menores a 5 (el 0% de la tabla) 
  χ²(2 gl) = 2.263, p = 0.323 </code></pre>
</div>
</div>
</section>
<section id="cálculo-manual-de-rr-rd-y-or" class="level3" data-number="11.8.5">
<h3 data-number="11.8.5" class="anchored" data-anchor-id="cálculo-manual-de-rr-rd-y-or"><span class="header-section-number">11.8.5</span> Cálculo Manual de RR, RD y OR</h3>
<div class="cell">
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41" data-lst-cap="Base R — Función completa para RR, OR, RD e IC 95%"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Función para RR, RD, OR con IC (diseños no apareados)</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>calcular_medidas <span class="ot">&lt;-</span> <span class="cf">function</span>(a, b, c, d, <span class="at">conf =</span> <span class="fl">0.95</span>) {</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  z  <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> conf)<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  n1 <span class="ot">&lt;-</span> a <span class="sc">+</span> b; n2 <span class="ot">&lt;-</span> c <span class="sc">+</span> d</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  p1 <span class="ot">&lt;-</span> a<span class="sc">/</span>n1;  p2 <span class="ot">&lt;-</span> c<span class="sc">/</span>n2</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  RR    <span class="ot">&lt;-</span> p1<span class="sc">/</span>p2</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  IC_RR <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">log</span>(RR) <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">*</span> z <span class="sc">*</span> <span class="fu">sqrt</span>(b<span class="sc">/</span>(a<span class="sc">*</span>n1) <span class="sc">+</span> d<span class="sc">/</span>(c<span class="sc">*</span>n2)))</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  OR    <span class="ot">&lt;-</span> (a<span class="sc">*</span>d)<span class="sc">/</span>(b<span class="sc">*</span>c)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  IC_OR <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">log</span>(OR) <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">*</span> z <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span>a <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>b <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>c <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>d))</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>  RD    <span class="ot">&lt;-</span> p1 <span class="sc">-</span> p2</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  IC_RD <span class="ot">&lt;-</span> RD <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">*</span> z <span class="sc">*</span> <span class="fu">sqrt</span>(p1<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p1)<span class="sc">/</span>n1 <span class="sc">+</span> p2<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p2)<span class="sc">/</span>n2)</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"RR  = %.3f  IC%d%%: [%.3f, %.3f]</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>              RR, <span class="fu">round</span>(conf<span class="sc">*</span><span class="dv">100</span>), IC_RR[<span class="dv">1</span>], IC_RR[<span class="dv">2</span>]))</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"OR  = %.3f  IC%d%%: [%.3f, %.3f]</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>              OR, <span class="fu">round</span>(conf<span class="sc">*</span><span class="dv">100</span>), IC_OR[<span class="dv">1</span>], IC_OR[<span class="dv">2</span>]))</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"RD  = %.3f  IC%d%%: [%.3f, %.3f]</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>              RD, <span class="fu">round</span>(conf<span class="sc">*</span><span class="dv">100</span>), IC_RD[<span class="dv">1</span>], IC_RD[<span class="dv">2</span>]))</span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"NNT/NNH = %.1f</span><span class="sc">\n</span><span class="st">"</span>, <span class="dv">1</span><span class="sc">/</span><span class="fu">abs</span>(RD)))</span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohorte: tabaquismo y cardiopatía isquémica</span></span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"=== Cohorte: tabaquismo y cardiopatía ===</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>=== Cohorte: tabaquismo y cardiopatía ===</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43" data-lst-cap="Base R — Función completa para RR, OR, RD e IC 95%"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calcular_medidas</span>(<span class="at">a=</span><span class="dv">80</span>, <span class="at">b=</span><span class="dv">420</span>, <span class="at">c=</span><span class="dv">30</span>, <span class="at">d=</span><span class="dv">470</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>RR  = 2.667  IC95%: [1.786, 3.982]
OR  = 2.984  IC95%: [1.922, 4.632]
RD  = 0.100  IC95%: [0.062, 0.138]
NNT/NNH = 10.0</code></pre>
</div>
</div>
</section>
<section id="ejemplo-integrado-con-dataset-osteo" class="level3" data-number="11.8.6">
<h3 data-number="11.8.6" class="anchored" data-anchor-id="ejemplo-integrado-con-dataset-osteo"><span class="header-section-number">11.8.6</span> Ejemplo Integrado con Dataset osteo</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: Análisis completo — datos osteo UGR
</div>
</div>
<div class="callout-body-container callout-body">
<p>El dataset <code>osteo</code> contiene datos de 94 pacientes diabéticos atendidos en la Facultad de Medicina de la UGR (Pedro Femia et al.). Realizamos un análisis completo de la asociación entre tabaquismo y osteoporosis.</p>
<div class="cell">
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45" data-lst-cap="BioStatR — Análisis completo: osteo dataset UGR"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BioStatR)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Normalidad del IMC</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">testnormal</span>(osteo<span class="sc">$</span>imc)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="semana11_files/figure-html/lst-s12-bio07-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
# Test de normalidad de Shapiro-Wilk  
 ------------------------------------- 
   n = 94,  W = 0.906,  p &lt; 0.001 </code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47" data-lst-cap="BioStatR — Análisis completo: osteo dataset UGR"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Tabla de contingencia y prueba Chi-cuadrado: tabaquismo × osteoporosis</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tabla2x2</span>(<span class="at">fvar =</span> osteo<span class="sc">$</span>tabaco, <span class="at">cvar =</span> osteo<span class="sc">$</span>osteo_cue,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">fcat =</span> <span class="fu">c</span>(<span class="st">"No fumador"</span>, <span class="st">"Fumador"</span>),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">ccat =</span> <span class="fu">c</span>(<span class="st">"Sin osteoporosis"</span>, <span class="st">"Con osteoporosis"</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
# Análisis de tablas 2x2
# ----------------------

# Frecuencias observadas
               Sin osteoporosis   Con osteoporosis Total
  No fumador                 44                  9    53
  Fumador                    26                 15    41
  Total                      70                 24    94


# Test Chi-cuadrado para un estudio transversal

  χ² = 4.662,   gl = 1,  p = 0.031, (cpc = 0.5) 
  Validez: Frecuencia mínima esperada = 10.47  &gt; 3.9  

  Test exacto de Fisher (bilateral): p = 0.035 

  --- Otros criterios χ²:  
  χ² = 4.673,   gl = 1,  p = 0.054, (sin cpc) 
  χ² = 3.699,   gl = 1,  p = 0.054, (cpc de Yates = 47.00) 

# Estimación de la prevalenciaπ en un estudio transversal
  Método de Wald ajustado: 
  p=0.561; 95%-IC(π)=(0.463, 0.659) 

# Medidas de asociación para un estudio transversal
  [!] Las medidas de riesgo se calculan como riesgo de la categoría  
      en la 1a columna (frente a la 2a) para la categoría en la 1a 
      fila (frente a la 2a)

  Riesgo absoluto (diferencia de Berkson; método de Agresti-Caffo): 
  d=0.254; 95%-IC(d)=(0.023, 0.459) 

  Riesgo relativo: 
  Rr=1.676; 95%-IC(Rr)=(0.969, 2.808) 

  Riesgo atribuible:
  Ra=0.335; 95%-IC(Ra)= (-0.049, 0.578) 

  Razón del producto cruzado (odds ratio):
  OR=2.821; 95%-IC(OR)= (1.070, 7.013) </code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49" data-lst-cap="BioStatR — Análisis completo: osteo dataset UGR"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Tabla de 3 grupos: grupo_edad × tabaco</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tablarxc</span>(<span class="at">fvar =</span> osteo<span class="sc">$</span>grupo_edad, <span class="at">cvar =</span> osteo<span class="sc">$</span>tabaco)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
# Test Chi-cuadrado para tablas RxC
# ---------------------------------

# Frecuencias observadas
         A  B Total
A       21 11    32
B       14 16    30
C       18 14    32
  Total 53 41    94

# Test chi-cuadrado 
  Validez: Frecuencia mínima esperada = 13.09 
           0 frecuencias esperadas son menores a 1
           0 son menores a 5 (el 0% de la tabla) 
  χ²(2 gl) = 2.263, p = 0.323 </code></pre>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="ajuste-por-confusión-el-estimador-de-mantel-haenszel" class="level2" data-number="11.9">
<h2 data-number="11.9" class="anchored" data-anchor-id="ajuste-por-confusión-el-estimador-de-mantel-haenszel"><span class="header-section-number">11.9</span> Ajuste por Confusión: El Estimador de Mantel-Haenszel</h2>
<p>En estudios epidemiológicos, a menudo observamos una asociación entre una exposición y una enfermedad que parece variar según los niveles de una tercera variable, llamada <strong>variable de confusión</strong> (o <em>confounder</em>). Si no controlamos esta variable, podemos llegar a conclusiones erróneas —incluso observar una <strong>Paradoja de Simpson</strong>, donde una asociación aparente en el total desaparece o se invierte al estratificar por la variable de confusión.</p>
<section id="el-estimador-de-mantel-haenszel-mh" class="level3" data-number="11.9.1">
<h3 data-number="11.9.1" class="anchored" data-anchor-id="el-estimador-de-mantel-haenszel-mh"><span class="header-section-number">11.9.1</span> El Estimador de Mantel-Haenszel (MH)</h3>
<p>El estimador de Mantel-Haenszel es una técnica clásica para combinar los odds ratios (OR) obtenidos de varios estratos (<span class="math inline">\(k\)</span>) de una variable de confusión, proporcionando un OR ajustado global. Se calcula como:</p>
<p><span class="math display">\[OR_{MH} = \frac{\sum_{i=1}^{k} \frac{a_i d_i}{n_i}}{\sum_{i=1}^{k} \frac{b_i c_i}{n_i}}\]</span></p>
<p>Donde para el estrato <span class="math inline">\(i\)</span>: - <span class="math inline">\(a_i, b_i, c_i, d_i\)</span>: celdas de la tabla 2×2. - <span class="math inline">\(n_i\)</span>: total de individuos en el estrato.</p>
<p><strong>Criterio del 10%:</strong> Para evaluar si una variable es un confounder clínicamente relevante, comparamos el OR crudo (total) con el OR ajustado (MH). Si la diferencia entre ambos es <span class="math inline">\(\geq 10\%\)</span>, se concluye que existe una confusión sustancial, y el OR ajustado por Mantel-Haenszel debe utilizarse como la medida de asociación más precisa.</p>
</section>
<section id="ejemplo-numérico-en-r-evaluación-de-confounding" class="level3" data-number="11.9.2">
<h3 data-number="11.9.2" class="anchored" data-anchor-id="ejemplo-numérico-en-r-evaluación-de-confounding"><span class="header-section-number">11.9.2</span> Ejemplo Numérico en R: Evaluación de Confounding</h3>
<p>Supongamos un estudio sobre el efecto de un nuevo fármaco (Fármaco A) en la recuperación de una enfermedad respiratoria, estratificado por la gravedad del paciente (Leve vs.&nbsp;Grave).</p>
<div class="cell">
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51" data-lst-cap="Cálculo del OR de Mantel-Haenszel en R"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epitools)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Estrato 1: Leve</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fármaco A (expuesto), recuperación (caso)</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>a1 <span class="ot">&lt;-</span> <span class="dv">40</span>; b1 <span class="ot">&lt;-</span> <span class="dv">10</span>; c1 <span class="ot">&lt;-</span> <span class="dv">10</span>; d1 <span class="ot">&lt;-</span> <span class="dv">40</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(a1, b1, c1, d1), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Tabla estrato 1 (Leve):</span><span class="sc">\n</span><span class="st">"</span>)); <span class="fu">print</span>(table1)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Tabla estrato 1 (Leve):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]   40   10
[2,]   10   40</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54" data-lst-cap="Cálculo del OR de Mantel-Haenszel en R"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>or1 <span class="ot">&lt;-</span> (a1 <span class="sc">*</span> d1) <span class="sc">/</span> (b1 <span class="sc">*</span> c1)  <span class="co"># OR estrato </span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">sprintf</span>(<span class="st">"OR estrato 1 (Leve) = %.3f"</span>, or1))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "OR estrato 1 (Leve) = 16.000"</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56" data-lst-cap="Cálculo del OR de Mantel-Haenszel en R"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estrato 2: Grave</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>a2 <span class="ot">&lt;-</span> <span class="dv">10</span>; b2 <span class="ot">&lt;-</span> <span class="dv">40</span>; c2 <span class="ot">&lt;-</span> <span class="dv">5</span>; d2 <span class="ot">&lt;-</span> <span class="dv">45</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>table2 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(a2, b2, c2, d2), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>or2 <span class="ot">&lt;-</span> (a2 <span class="sc">*</span> d2) <span class="sc">/</span> (b2 <span class="sc">*</span> c2)  <span class="co"># OR estrato</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Tabla estrato 2 (Grave):</span><span class="sc">\n</span><span class="st">"</span>)); <span class="fu">print</span>(table2)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Tabla estrato 2 (Grave):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]   10   40
[2,]    5   45</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59" data-lst-cap="Cálculo del OR de Mantel-Haenszel en R"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">sprintf</span>(<span class="st">"OR estrato 2 (Grave) = %.3f"</span>, or2))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "OR estrato 2 (Grave) = 2.250"</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61" data-lst-cap="Cálculo del OR de Mantel-Haenszel en R"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Array de tablas (estratificación)</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>tables <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="fu">c</span>(a1, b1, c1, d1, a2, b2, c2, d2), <span class="at">dim =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>tables <span class="ot">&lt;-</span> <span class="fu">aperm</span>(tables, <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">3</span>))  <span class="co"># Reordenar dimensiones para epitools</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. OR Crudo (sumamos los estratos)</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>total_table <span class="ot">&lt;-</span> table1 <span class="sc">+</span> table2</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>or_crudo <span class="ot">&lt;-</span> (total_table[<span class="dv">1</span>,<span class="dv">1</span>] <span class="sc">*</span> total_table[<span class="dv">2</span>,<span class="dv">2</span>]) <span class="sc">/</span> (total_table[<span class="dv">1</span>,<span class="dv">2</span>] <span class="sc">*</span> total_table[<span class="dv">2</span>,<span class="dv">1</span>])</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Tabla total:</span><span class="sc">\n</span><span class="st">"</span>)); <span class="fu">print</span>(total_table)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Tabla total:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]   50   50
[2,]   15   85</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64" data-lst-cap="Cálculo del OR de Mantel-Haenszel en R"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. OR Ajustado por Mantel-Haenszel</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>mh <span class="ot">&lt;-</span> <span class="fu">mantelhaen.test</span>(tables, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>or_mh <span class="ot">&lt;-</span> mh<span class="sc">$</span>estimate</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"OR Crudo: %.3f</span><span class="sc">\n</span><span class="st">"</span>, or_crudo))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>OR Crudo: 5.667</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66" data-lst-cap="Cálculo del OR de Mantel-Haenszel en R"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"OR Mantel-Haenszel: %.3f</span><span class="sc">\n</span><span class="st">"</span>, or_mh))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>OR Mantel-Haenszel: 6.833</code></pre>
</div>
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68" data-lst-cap="Cálculo del OR de Mantel-Haenszel en R"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Aplicación de la regla del 10%</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>diff_pct <span class="ot">&lt;-</span> <span class="fu">abs</span>(or_crudo <span class="sc">-</span> or_mh) <span class="sc">/</span> or_crudo <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Diferencia relativa: %.1f%%</span><span class="sc">\n</span><span class="st">"</span>, diff_pct))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Diferencia relativa: 20.6%</code></pre>
</div>
</div>
<p><strong>Interpretación Epidemiológica:</strong> En este estudio, el OR crudo (total) es 5.67, mientras que el OR ajustado (MH) es 6.83. La diferencia relativa es de 20.6%. Al ser mayor del 10%, existe un efecto de confusión sustancial provocado por la “gravedad”.</p>
<p>La gravedad actúa como un factor de confusión ya que está asociada tanto a la probabilidad de recibir el Fármaco A (sesgo de indicación) como a la probabilidad de recuperación (pronóstico). El OR crudo subestima (o sobreestima) el efecto real al mezclar el impacto del fármaco con la mayor o menor gravedad basal de los pacientes. Al ajustar por MH, eliminamos esta confusión.</p>
<p>Sin embargo, es crucial notar que existe una <strong>interacción</strong> (modificación del efecto): el fármaco parece ser más eficaz en pacientes leves que en pacientes graves. En presencia de una interacción tan marcada, la mejor recomendación epidemiológica es presentar los <strong>resultados estratificados</strong>, ya que un único OR ajustado (MH) ocultaría esta heterogeneidad clínicamente relevante.</p>
<p>Por último, para superar las limitaciones de los métodos tradicionales, la generalización de la estandarización mediante la <strong>g-formula</strong> (Robins, 1987) representa hoy en día una alternativa avanzada y robusta para ajustar el efecto del fármaco. Para aquellos interesados en introducirse en la inferencia causal desde una perspectiva tanto histórica como computacional, se recomienda como punto de partida el tutorial <em>Computational Causal Inference</em> (Smith &amp; Luque-Fernandez, 2020, publicado en <em>Statistics in Medicine</em>), el cual ofrece una excelente guía con ejemplos prácticos implementados en <strong>R, Python y Stata</strong>.</p>
</section>
<section id="sec-semana11-rlogitm" class="level3" data-number="11.9.3">
<h3 data-number="11.9.3" class="anchored" data-anchor-id="sec-semana11-rlogitm"><span class="header-section-number">11.9.3</span> Control multivariable de la confusión: regresión logística múltiple con <code>rlogitm()</code></h3>
<p>El estimador de Mantel–Haenszel es elegante y didácticamente potente, pero presenta dos limitaciones operativas importantes:</p>
<ol type="1">
<li><strong>Sólo permite controlar por una variable de confusión categórica</strong> (la que define los estratos). Si necesitamos ajustar simultáneamente por edad, IMC, tabaquismo y tiempo de evolución, la estratificación produce demasiados estratos con frecuencias muy pequeñas en cada uno.</li>
<li><strong>Asume homogeneidad del OR a través de los estratos</strong>. Cuando esa hipótesis se rompe (interacción, como en el ejemplo previo), el OR de M–H promedia efectos heterogéneos y oculta la modificación del efecto.</li>
</ol>
<p>La <strong>regresión logística múltiple</strong> generaliza el ajuste por confusión: permite incluir un número arbitrario de covariables (continuas o categóricas) simultáneamente, estima un OR ajustado para cada predictor manteniendo constantes las demás, y proporciona una medida global de capacidad discriminante mediante el <strong>área bajo la curva ROC</strong> (AUC). El paquete <code>BioStatR</code> integra todo este flujo en la función <code>rlogitm()</code> (ver <a href="#sec-apendiceB" class="quarto-xref"><span class="quarto-unresolved-ref">sec-apendiceB</span></a>), que devuelve:</p>
<ul>
<li>Estimación de los coeficientes con sus odds ratios e intervalos de confianza.</li>
<li>Bondad de ajuste mediante el <strong>test de Hosmer–Lemeshow</strong>.</li>
<li>Pseudo-<span class="math inline">\(R^2\)</span> de <strong>Nagelkerke</strong>.</li>
<li><strong>AUC</strong> con su intervalo de confianza al 95 %.</li>
<li>Curva ROC (opcional, con <code>grf = TRUE</code>).</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo: osteoporosis del cuello femoral ajustada por múltiples factores
</div>
</div>
<div class="callout-body-container callout-body">
<p>Volvamos al estudio observacional de la sección de tablas de contingencia, donde habíamos detectado una asociación entre tabaquismo y osteoporosis del cuello femoral (<code>osteo_cue</code>) en 94 pacientes diabéticos. La pregunta clínica relevante es: <strong>¿persiste la asociación tras controlar simultáneamente por edad, índice de masa corporal y tiempo de evolución de la diabetes?</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70" data-lst-cap="BioStatR — rlogitm(): regresión logística múltiple sobre el dataset osteo"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BioStatR)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(osteo)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo: osteoporosis del cuello femoral ajustada por tabaco + edad + IMC + tevol</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rlogitm</span>(osteo_cue <span class="sc">~</span> tabaco <span class="sc">+</span> edad <span class="sc">+</span> imc <span class="sc">+</span> tevol,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> osteo,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">grf  =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Regresión logística  multivariable
----------------------------------------------------------------
# Información muestral --- 

   Tamaño muestral (N inicial) :  94 
   Tamaño muestral tras eliminar valores perdidos (Casos completos) :  94 
   Mínima frecuencia de eventos (n efectivo) :  24 

# Distribución de la variable respuesta (osteo_cue) ---

  Categoria  n Porcentaje
1        No 70       74.5
2        Sí 24       25.5

# Modelo logístico ---  --- 

   Modelo :  osteo_cue ~ tabaco + edad + imc + tevol 
  Devianza residual:  92  (Nula:  107 )
  AIC:  102 
  R² de Nagelkerke:  0.214 

   Test de bondad de ajuste de Hosmer-Lemeshow :
  X² =  2.07 , gl =  8 ,   = 0.979 

   Capacidad discriminante :
   AUC (Area bajo la curva ROC)  =  0.74 

   Coeficientes del modelo :

      Termino Estimacion Error_Std  z_exp      sig     OR OR_inf   OR_sup
1 (Intercept)      2.893     2.269  1.275  = 0.202 18.045  0.275 2237.565
2    tabacoSí      0.865     0.549  1.575  = 0.115  2.376  0.821    7.218
3        edad     -0.004     0.037 -0.105  = 0.917  0.996  0.925    1.072
4         imc     -0.224     0.105 -2.140  = 0.032  0.799  0.638    0.965
5       tevol      0.071     0.035  2.020  = 0.043  1.074  1.004    1.154</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="semana11_files/figure-html/lst-s11-rlogitm-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretación epidemiológica:</strong></p>
<ul>
<li><p><strong>Tabaquismo (variable de exposición principal):</strong> tras ajustar por edad, IMC y tiempo de evolución, los fumadores presentan un OR ajustado <span class="math inline">\(\approx 2.4\)</span> (IC 95 %: 0.82 – 7.22) frente a los no fumadores. La asociación cruda obtenida en la tabla 2×2 (OR <span class="math inline">\(\approx 2.8\)</span>, <span class="math inline">\(p = 0.031\)</span>) se atenúa ligeramente al ajustar por las demás covariables y pierde significación estadística al 5 %, lo que sugiere que parte del efecto observado podría estar mediado o confundido por la edad y el IMC. Este es un ejemplo clásico de cómo el <strong>OR ajustado por regresión multivariable</strong> difiere del OR crudo y, también, del OR de Mantel–Haenszel restringido a un único estratificador.</p></li>
<li><p><strong>IMC:</strong> muestra una asociación inversa estadísticamente significativa (<span class="math inline">\(\text{OR} \approx 0.80\)</span>, <span class="math inline">\(p \approx 0.03\)</span>). Cada unidad adicional de IMC reduce las odds de osteoporosis del cuello femoral aproximadamente un 20 %, en consonancia con la literatura sobre el efecto protector de la masa corporal sobre la densidad ósea.</p></li>
<li><p><strong>Tiempo de evolución de la diabetes (<code>tevol</code>):</strong> asociación positiva significativa (<span class="math inline">\(\text{OR} \approx 1.07\)</span>, <span class="math inline">\(p \approx 0.04\)</span>). Cada año adicional de evolución incrementa las odds de osteoporosis del cuello femoral en torno a un 7 %.</p></li>
<li><p><strong>Edad:</strong> no aporta información independiente del resto de predictores (<span class="math inline">\(p \approx 0.92\)</span>), probablemente porque su efecto está capturado por <code>tevol</code> (variable altamente correlacionada con la edad en pacientes diabéticos).</p></li>
</ul>
<p><strong>Bondad de ajuste y discriminación:</strong></p>
<ul>
<li>El test de Hosmer–Lemeshow no rechaza el ajuste del modelo (<span class="math inline">\(\chi^2 \approx 2.07\)</span>, <span class="math inline">\(p \approx 0.98\)</span>): las probabilidades predichas son coherentes con las frecuencias observadas en deciles de riesgo.</li>
<li>El pseudo-<span class="math inline">\(R^2\)</span> de Nagelkerke alcanza <span class="math inline">\(\approx 0.21\)</span>, un valor moderado para datos observacionales en bioestadística clínica.</li>
<li>El AUC de la curva ROC es <span class="math inline">\(\approx 0.74\)</span>, indicando una <strong>capacidad discriminante aceptable</strong>: en términos prácticos, si tomamos al azar a un paciente con osteoporosis y a otro sin osteoporosis, la probabilidad predicha de osteoporosis es mayor en el primero el 74 % de las veces.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Mantel–Haenszel vs.&nbsp;regresión logística múltiple
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 29%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Criterio</th>
<th style="text-align: center;">Mantel–Haenszel</th>
<th style="text-align: center;">Regresión logística múltiple</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nº de covariables de ajuste</td>
<td style="text-align: center;">1 (categórica, define estratos)</td>
<td style="text-align: center;">Arbitrario (continuas y categóricas)</td>
</tr>
<tr class="even">
<td>Supuesto sobre OR</td>
<td style="text-align: center;">Homogeneidad entre estratos</td>
<td style="text-align: center;">Linealidad en el log-odds; no interacción salvo que se modelice</td>
</tr>
<tr class="odd">
<td>Output principal</td>
<td style="text-align: center;">OR ajustado único</td>
<td style="text-align: center;">OR ajustado por covariable + bondad de ajuste + AUC</td>
</tr>
<tr class="even">
<td>Detección de interacción</td>
<td style="text-align: center;">Test de Breslow–Day</td>
<td style="text-align: center;">Términos producto en la fórmula</td>
</tr>
<tr class="odd">
<td>Cuando elegirlo</td>
<td style="text-align: center;">Análisis exploratorio rápido, una sola covariable de confusión</td>
<td style="text-align: center;">Análisis confirmatorio, múltiples confusores, predicción</td>
</tr>
</tbody>
</table>
<p>En la práctica epidemiológica moderna ambas técnicas se utilizan de forma complementaria: M–H ofrece una <strong>lectura rápida y transparente</strong> del efecto de una variable de exposición estratificada, mientras que la <strong>regresión logística múltiple</strong> proporciona el modelo de ajuste definitivo con todas las covariables relevantes y una medida global de discriminación (AUC).</p>
</div>
</div>
</section>
</section>
<section id="ejercicios-del-tema" class="level2" data-number="11.10">
<h2 data-number="11.10" class="anchored" data-anchor-id="ejercicios-del-tema"><span class="header-section-number">11.10</span> Ejercicios del tema</h2>
<p><strong>Ejercicio 11.1:</strong> En un estudio sobre el consumo de alcohol y diabetes tipo 2 se obtiene la siguiente tabla 2×2:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Diabetes</th>
<th style="text-align: center;">Sin diabetes</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bebedor habitual</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">105</td>
<td style="text-align: center;">150</td>
</tr>
<tr class="even">
<td>No bebedor</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">130</td>
<td style="text-align: center;">150</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Calcule las frecuencias esperadas bajo <span class="math inline">\(H_0\)</span>. b) Calcule el estadístico <span class="math inline">\(\chi^2\)</span> manualmente. c) ¿Existe asociación con <span class="math inline">\(\alpha = 0.05\)</span>?</li>
</ol>
<p><strong>Ejercicio 11.2:</strong> Un ensayo clínico compara tres tratamientos para la hipertensión: A (control), B (dosis baja), C (dosis alta). Los resultados son:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tratamiento</th>
<th style="text-align: center;">Controlada</th>
<th style="text-align: center;">No controlada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">35</td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">20</td>
</tr>
<tr class="odd">
<td>C</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">15</td>
</tr>
</tbody>
</table>
<p>Usando la prueba <span class="math inline">\(\chi^2\)</span> de homogeneidad con <span class="math inline">\(\alpha = 0.05\)</span>, ¿difieren los tratamientos en su eficacia? (<span class="math inline">\(gl = 2\)</span>, <span class="math inline">\(\chi^2_{0.05} = 5.99\)</span>).</p>
<p><strong>Ejercicio 11.3:</strong> Una tabla 2×2 tiene celdas <span class="math inline">\((3, 12, 8, 7)\)</span>. a) Compruebe si se cumple la condición de aplicación del <span class="math inline">\(\chi^2\)</span>. b) ¿Qué alternativa utilizaría? c) Aplique la alternativa e interprete.</p>
<p><strong>Ejercicio 11.4 (McNemar):</strong> En un estudio de concordancia diagnóstica, 80 pacientes con sospecha de infección por <em>Helicobacter pylori</em> son evaluados con dos pruebas: test de aliento con urea (TAU) y serología (SERO). Los resultados son:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;"><strong>SERO: +</strong></th>
<th style="text-align: center;"><strong>SERO: −</strong></th>
<th style="text-align: center;"><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>TAU: +</strong></td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">50</td>
</tr>
<tr class="even">
<td><strong>TAU: −</strong></td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">30</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">80</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>¿Por qué es incorrecto aplicar el test <span class="math inline">\(\chi^2\)</span> de independencia aquí?</li>
<li>Identifique los pares discordantes (<span class="math inline">\(b\)</span> y <span class="math inline">\(c\)</span>) e indique cuántos son.</li>
<li>Calcule el estadístico de McNemar (con y sin corrección de Yates).</li>
<li>¿Difieren significativamente las dos pruebas diagnósticas en su tasa de positividad? ¿Cuál detecta más casos?</li>
</ol>
<p><strong>Ejercicio 11.5:</strong> Un estudio de cohortes sigue a 1000 trabajadores expuestos a un contaminante y 1000 no expuestos durante 5 años. Se observan 60 casos de enfermedad pulmonar en expuestos y 20 en no expuestos. a) Calcule el RR e interprete. b) Calcule el IC 95%. c) Calcule el RD y el NNH.</p>
<p><strong>Ejercicio 11.6:</strong> En un estudio caso-control sobre infarto de miocardio, se estudia la asociación con hipertensión. Se reclutan 200 casos (infartos) y 200 controles. De los casos, 120 son hipertensos; de los controles, 80. a) Construya la tabla 2×2. b) Calcule el OR. c) Calcule el IC 95% del OR. d) ¿Por qué no es adecuado calcular el RR en este diseño?</p>
<p><strong>Ejercicio 11.7:</strong> En un estudio transversal sobre la prevalencia de diabetes y obesidad en 800 adultos, 200 son obesos (IMC <span class="math inline">\(\geq 30\)</span>) y 600 no obesos. Entre los obesos, 60 tienen diabetes; entre los no obesos, 40 tienen diabetes. a) Calcule la RP. b) Calcule el OR. c) ¿Cuál es la medida más apropiada? d) ¿Son similares los resultados? Explique por qué.</p>
<hr>
</section>
<section id="sec-semana11-respuestas" class="level2" data-number="11.11">
<h2 data-number="11.11" class="anchored" data-anchor-id="sec-semana11-respuestas"><span class="header-section-number">11.11</span> Respuestas a los Ejercicios</h2>
<p><strong>Ejercicio 11.1:</strong> a) <span class="math inline">\(E_{11} = 150 \times 65/300 = 32.5\)</span>; <span class="math inline">\(E_{12} = 150 \times 235/300 = 117.5\)</span>; <span class="math inline">\(E_{21} = 32.5\)</span>; <span class="math inline">\(E_{22} = 117.5\)</span>. b) <span class="math inline">\(\chi^2 = (45-32.5)^2/32.5 + (105-117.5)^2/117.5 + (20-32.5)^2/32.5 + (130-117.5)^2/117.5 \approx 4.81 + 1.33 + 4.81 + 1.33 = 12.28\)</span>. c) <span class="math inline">\(\chi^2_{0.05, 1} = 3.84\)</span>. Como <span class="math inline">\(12.28 &gt; 3.84\)</span> (<span class="math inline">\(p &lt; 0.001\)</span>), rechazamos <span class="math inline">\(H_0\)</span>: existe asociación significativa entre consumo de alcohol y diabetes tipo 2.</p>
<p><strong>Ejercicio 11.2:</strong> Frecuencias esperadas: <span class="math inline">\(n = 180\)</span>, marginales columna: 110 controladas, 70 no controladas. <span class="math inline">\(E_{A,ctrl} = 60 \times 110/180 = 36.67\)</span>; calculando todos: <span class="math inline">\(\chi^2 \approx 15.2 &gt; 5.99\)</span>, <span class="math inline">\(gl = 2\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>. Los tres tratamientos tienen eficacias significativamente diferentes. La dosis alta (75% controlados) es la más eficaz.</p>
<p><strong>Ejercicio 11.3:</strong> a) <span class="math inline">\(E_{11} = 11 \times 11/30 = 4.03 &lt; 5\)</span>; condición NO cumplida. b) Usar <strong>prueba exacta de Fisher</strong>. c) Con <span class="math inline">\(n = 30\)</span> y celdas <span class="math inline">\((3, 12, 8, 7)\)</span>: <span class="math inline">\(OR = 3 \times 7/(12 \times 8) = 0.22\)</span>. La prueba exacta de Fisher daría <span class="math inline">\(p \approx 0.07\)</span>, no significativo al 5%.</p>
<p><strong>Ejercicio 11.4 (McNemar):</strong> a) Las dos pruebas se aplican al mismo paciente, por lo que las observaciones son dependientes entre sí. El test <span class="math inline">\(\chi^2\)</span> de independencia requiere que todas las observaciones sean independientes; violarlo inflaría artificialmente el tamaño de muestra efectivo. b) Pares discordantes: <span class="math inline">\(b = 12\)</span> (TAU+/SERO−) y <span class="math inline">\(c = 5\)</span> (TAU−/SERO+). Total: <span class="math inline">\(b + c = 17\)</span>. c) Como <span class="math inline">\(b + c = 17 &lt; 25\)</span>, se recomienda la corrección de Yates: - Sin corrección: <span class="math inline">\(\chi^2 = (12-5)^2/17 = 49/17 = 2.88\)</span> - Con corrección (Yates): <span class="math inline">\(\chi^2 = (|12-5|-1)^2/17 = 36/17 = 2.12\)</span> d) Sin corrección: <span class="math inline">\(\chi^2 = 2.88\)</span>, <span class="math inline">\(p \approx 0.090\)</span>. Con corrección de Yates: <span class="math inline">\(\chi^2 = 2.12\)</span>, <span class="math inline">\(p \approx 0.145\)</span>. Con <span class="math inline">\(\alpha = 0.05\)</span>, <strong>no rechazamos</strong> <span class="math inline">\(H_0\)</span> en ningún caso: no hay evidencia suficiente de que las dos pruebas difieran significativamente en su tasa de positividad. No obstante, el TAU detecta más positivos que la serología (<span class="math inline">\(b = 12 &gt; c = 5\)</span>), lo que sugiere una tendencia a mayor sensibilidad del TAU, aunque no alcanza significancia estadística con esta muestra.</p>
<p><strong>Ejercicio 11.5:</strong> a) <span class="math inline">\(RR = (60/1000)/(20/1000) = 3.0\)</span>. Los expuestos tienen <strong>3 veces más riesgo</strong> de enfermedad pulmonar. b) <span class="math inline">\(SE_{\ln RR} = \sqrt{940/(60 \times 1000) + 980/(20 \times 1000)} = \sqrt{0.01567 + 0.049} = 0.256\)</span>; <span class="math inline">\(IC_{95\%} = \exp(\ln3 \pm 0.501) = [1.50, 5.99]\)</span>. c) <span class="math inline">\(RD = 0.060 - 0.020 = 0.040\)</span>; <span class="math inline">\(NNH = 1/0.040 = 25\)</span> (por cada 25 trabajadores expuestos durante 5 años, 1 caso adicional de enfermedad pulmonar).</p>
<p><strong>Ejercicio 11.6:</strong> a) Tabla: hipertensos <span class="math inline">\((120, 80, 200)\)</span>; normotensos <span class="math inline">\((80, 120, 200)\)</span>; totales <span class="math inline">\((200, 200, 400)\)</span>. b) <span class="math inline">\(OR = (120 \times 120)/(80 \times 80) = 14400/6400 = 2.25\)</span>. c) <span class="math inline">\(IC_{95\%}: \exp(\ln 2.25 \pm 1.96\sqrt{1/120 + 1/80 + 1/80 + 1/120}) = \exp(0.811 \pm 0.369) = [1.44, 3.51]\)</span>. d) En un estudio caso-control, el muestreo es por resultado (se seleccionan casos y controles), por lo que los totales de fila son fijados por el investigador y no reflejan la incidencia real → no se puede estimar el riesgo ni el RR directamente.</p>
<p><strong>Ejercicio 11.7:</strong> a) <span class="math inline">\(RP = (60/200)/(40/600) = 0.30/0.067 = 4.50\)</span>. Los obesos tienen 4.5 veces la prevalencia de diabetes. b) <span class="math inline">\(OR = (60 \times 560)/(140 \times 40) = 33600/5600 = 6.0\)</span>. c) La medida apropiada en un estudio transversal es la <strong>RP</strong>, no el OR. d) Los resultados difieren notablemente (<span class="math inline">\(RP = 4.5\)</span> vs <span class="math inline">\(OR = 6.0\)</span>) porque la prevalencia de diabetes no es rara (50% en obesos): el OR sobreestima la RP cuando la prevalencia es alta (&gt; 10%). Usar siempre RP en estudios transversales.</p>
<hr>
</section>
<section id="sec-semana11-avanzados" class="level2" data-number="11.12">
<h2 data-number="11.12" class="anchored" data-anchor-id="sec-semana11-avanzados"><span class="header-section-number">11.12</span> Recomendaciones de Métodos Avanzados</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para profundizar en estos temas, se recomienda consultar textos especializados como <em>Categorical Data Analysis</em> de Alan Agresti o literatura específica en bioestadística avanzada enfocada en inferencia causal.</p>
<p>Para ampliar los contenidos de este capítulo con técnicas estadísticas avanzadas, visita:</p>
<p><strong><a href="https://migariane.github.io/Bioestadistica">→ Bioestadística Avanzada — M.A.&nbsp;Luque Fernández</a></strong></p>
</div>
</div>
<hr>
</section>
<section id="sec-semana11-resources" class="level2" data-number="11.13">
<h2 data-number="11.13" class="anchored" data-anchor-id="sec-semana11-resources"><span class="header-section-number">11.13</span> Lecturas Recomendadas Adicionales</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 22%">
<col style="width: 64%">
</colgroup>
<thead>
<tr class="header">
<th>Tema</th>
<th>Referencia</th>
<th>Relevancia para este capítulo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Datos categóricos</td>
<td><span class="citation" data-cites="Agresti2013">Agresti (<a href="#ref-Agresti2013" role="doc-biblioref">2013</a>)</span></td>
<td>Tablas de contingencia, χ², modelos log-lineales</td>
</tr>
<tr class="even">
<td>Datos apareados</td>
<td><span class="citation" data-cites="McNemar1947">McNemar (<a href="#ref-McNemar1947" role="doc-biblioref">1947</a>)</span></td>
<td>Artículo original de la prueba de McNemar</td>
</tr>
<tr class="odd">
<td>Tasas y proporciones</td>
<td><span class="citation" data-cites="Fleiss2003">Fleiss et&nbsp;al. (<a href="#ref-Fleiss2003" role="doc-biblioref">2003</a>)</span></td>
<td>IC exactos, OR, RR y prueba de McNemar</td>
</tr>
<tr class="even">
<td>Estadística médica</td>
<td><span class="citation" data-cites="Altman1991">Altman (<a href="#ref-Altman1991" role="doc-biblioref">1991</a>)</span></td>
<td>Tablas 2×2 y medidas de asociación</td>
</tr>
<tr class="odd">
<td>Epidemiología</td>
<td><span class="citation" data-cites="Rothman2008">Rothman et&nbsp;al. (<a href="#ref-Rothman2008" role="doc-biblioref">2008</a>)</span></td>
<td>RR, OR, diseños cohorte/caso-control</td>
</tr>
<tr class="even">
<td>Inferencia Causal</td>
<td><span class="citation" data-cites="Robins1987">Robins (<a href="#ref-Robins1987" role="doc-biblioref">1987</a>)</span></td>
<td>G-formula para estandarización</td>
</tr>
<tr class="odd">
<td>Inferencia Causal</td>
<td><span class="citation" data-cites="Smith2020">Smith &amp; al. (<a href="#ref-Smith2020" role="doc-biblioref">2020</a>)</span></td>
<td>Tutorial de inferencia causal computacional (R, Python, Stata)</td>
</tr>
<tr class="even">
<td>Epidemiología analítica</td>
<td><span class="citation" data-cites="Szklo2007">Szklo &amp; Nieto (<a href="#ref-Szklo2007" role="doc-biblioref">2007</a>)</span></td>
<td>Medidas de efecto y diseños epidemiológicos</td>
</tr>
<tr class="odd">
<td>Introducción estadística</td>
<td><span class="citation" data-cites="OpenIntro2019">Diez et&nbsp;al. (<a href="#ref-OpenIntro2019" role="doc-biblioref">2019</a>)</span></td>
<td>Inferencia sobre proporciones</td>
</tr>
</tbody>
</table>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Agresti2013" class="csl-entry" role="listitem">
Agresti, A. (2013). <em>Categorical Data Analysis</em> (3rd ed.). Wiley.
</div>
<div id="ref-Altman1991" class="csl-entry" role="listitem">
Altman, D. G. (1991). <em>Practical Statistics for Medical Research</em>. Chapman; Hall/CRC.
</div>
<div id="ref-OpenIntro2019" class="csl-entry" role="listitem">
Diez, D. M., Barr, C. D., &amp; Cetinkaya-Rundel, M. (2019). <em>OpenIntro Statistics</em> (4th ed.). OpenIntro Inc. <a href="https://www.openintro.org">https://www.openintro.org</a>
</div>
<div id="ref-Fleiss2003" class="csl-entry" role="listitem">
Fleiss, J. L., Levin, B., &amp; Paik, M. C. (2003). <em>Statistical Methods for Rates and Proportions</em> (3rd ed.). Wiley.
</div>
<div id="ref-MartinAndresLuna2004" class="csl-entry" role="listitem">
Martı́n Andrés, A., &amp; Luna del Castillo, J. de D. (2004). <em>Bioestad<span>ı́</span>stica para las Ciencias de la Salud</em> (5th ed.). Norma-Capitel.
</div>
<div id="ref-MartinAndres1994" class="csl-entry" role="listitem">
Martı́n Andrés, A., &amp; Silva Mato, A. (1994). Choosing the optimal unconditional test for comparing two independent proportions. <em>Computational Statistics &amp; Data Analysis</em>, <em>17</em>(5), 555-574. <a href="https://doi.org/10.1016/0167-9473(94)90148-1">https://doi.org/10.1016/0167-9473(94)90148-1</a>
</div>
<div id="ref-McNemar1947" class="csl-entry" role="listitem">
McNemar, Q. (1947). Note on the Sampling Error of the Difference between Correlated Proportions or Percentages. <em>Psychometrika</em>, <em>12</em>(2), 153-157. <a href="https://doi.org/10.1007/BF02295996">https://doi.org/10.1007/BF02295996</a>
</div>
<div id="ref-Robins1987" class="csl-entry" role="listitem">
Robins, J. M. (1987). A new approach to causal inference in mortality studies with a sustained exposure period—application to control of the healthy worker survivor effect. <em>Mathematical Modelling</em>, <em>7</em>(5-8), 1393-1512. <a href="https://doi.org/10.1016/0270-0255(86)90088-6">https://doi.org/10.1016/0270-0255(86)90088-6</a>
</div>
<div id="ref-Rothman2008" class="csl-entry" role="listitem">
Rothman, K. J., Greenland, S., &amp; Lash, T. L. (2008). <em>Modern Epidemiology</em> (3rd ed.). Lippincott Williams; Wilkins.
</div>
<div id="ref-Smith2020" class="csl-entry" role="listitem">
Smith, M., &amp; al., et. (2020). Computational causal inference. <em>Statistics in Medicine</em>, <em>39</em>(1), 1-35. <a href="https://doi.org/10.1002/sim.9234">https://doi.org/10.1002/sim.9234</a>
</div>
<div id="ref-Szklo2007" class="csl-entry" role="listitem">
Szklo, M., &amp; Nieto, F. J. (2007). <em>Epidemiology: Beyond the Basics</em> (2nd ed.). Jones; Bartlett.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/semana10.html" class="pagination-link" aria-label="Semana 10 — Regresión Lineal Múltiple">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Semana 10 — Regresión Lineal Múltiple</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../references.html" class="pagination-link" aria-label="Referencias">
        <span class="nav-page-text">Referencias</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Matemáticas para la Estadística Médica con R, por Miguel Ángel Luque Fernández</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/edit/main/chapters/semana11.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/blob/main/chapters/semana11.qmd" class="toc-action"><i class="bi empty"></i>Ver el código</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>© 2026 Universidad de Granada · <a href="https://www.ugr.es">ugr.es</a></p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>