<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Material docence de Matemáticas para la Estadística Médica con R (Bioestadística) desarrollados por el autor en el Departamento de Estadística e Investigación Operativa, Unidad Docente de Bioestadística de la Universidad de Granada.">

<title>3&nbsp; Semana 3 — Fundamentos de la Teoría de la Probabilidad – Matemáticas para la Estadística Médica con R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/semana04.html" rel="next">
<link href="../chapters/semana02.html" rel="prev">
<link href="../figures/ugr-logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-b6a8276bf55561bdbc268162d41bd1f7.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-95edd58b3b27b9774827898c46d4f452.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script>
MathJax = {
  tex: {
    macros: {
      btheta: "\\boldsymbol{\\theta}",
      bbeta: "\\boldsymbol{\\beta}",
      bmu: "\\boldsymbol{\\mu}",
      bSigma: "\\boldsymbol{\\Sigma}",
      bx: "\\mathbf{x}",
      bX: "\\mathbf{X}",
      by: "\\mathbf{y}",
      bY: "\\mathbf{Y}",
      bU: "\\mathbf{U}",
      E: "\\mathbb{E}",
      Var: ["\\operatorname{Var}"],
      Cov: ["\\operatorname{Cov}"],
      Corr: ["\\operatorname{Corr}"],
      iid: "\\stackrel{\\text{i.i.d.}}{\\sim}",
      tendD: "\\stackrel{\\mathcal{D}}{\\longrightarrow}",
      reals: "\\mathbb{R}",
      PP: "\\mathbb{P}"
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/semana03.html">Parte II: Probabilidad y Variables Aleatorias</a></li><li class="breadcrumb-item"><a href="../chapters/semana03.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Semana 3 — Fundamentos de la Teoría de la Probabilidad</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Matemáticas para la Estadística Médica con R</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Matemáticas-para-la-Estadística-Médica-con-R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte I: Análisis Exploratorio de Datos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Semana 1 — Análisis Exploratorio de Datos (Parte I)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Semana 2 — Análisis Exploratorio de Datos (Parte II)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte II: Probabilidad y Variables Aleatorias</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana03.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Semana 3 — Fundamentos de la Teoría de la Probabilidad</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Semana 4 — Variables Aleatorias y Distribuciones de Probabilidad</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Semana 5 — Muestreo y Distribuciones Muestrales</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte III: Inferencia Estadística</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Semana 6 — Estimación de Parámetros</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Semana 7 — Contrastes de Hipótesis (Parte I)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Semana 8 — Contrastes de Hipótesis (Parte II)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte IV: Regresión Lineal</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Semana 9 — Regresión Lineal Simple</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Semana 10 — Regresión Lineal Múltiple</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte V: Análisis de Datos Categóricos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/semana11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Semana 11 — Análisis de Datos Categóricos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Apéndice A: Repaso Matemático Riguroso</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceB.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Apéndice B: El Paquete <code>BioEstatR</code> — Guía de Referencia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Apéndice C: Guía de R para Estadística Médica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/apendiceD.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Apéndice D: Investigación Reproducible con Git, GitHub y RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/examen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Examen Final</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenidos</h2>
   
  <ul>
  <li><a href="#introduccion" id="toc-introduccion" class="nav-link active" data-scroll-target="#introduccion"><span class="header-section-number">3.1</span> Introducción</a></li>
  <li><a href="#sec-semana03-s1" id="toc-sec-semana03-s1" class="nav-link" data-scroll-target="#sec-semana03-s1"><span class="header-section-number">3.2</span> Experimentos Aleatorios y Eventos</a>
  <ul class="collapse">
  <li><a href="#experimento-aleatorio" id="toc-experimento-aleatorio" class="nav-link" data-scroll-target="#experimento-aleatorio"><span class="header-section-number">3.2.1</span> Experimento Aleatorio</a></li>
  <li><a href="#evento-elemental-y-particion" id="toc-evento-elemental-y-particion" class="nav-link" data-scroll-target="#evento-elemental-y-particion"><span class="header-section-number">3.2.2</span> Evento Elemental y Partición</a></li>
  </ul></li>
  <li><a href="#sec-semana03-s2" id="toc-sec-semana03-s2" class="nav-link" data-scroll-target="#sec-semana03-s2"><span class="header-section-number">3.3</span> Álgebra de Conjuntos</a>
  <ul class="collapse">
  <li><a href="#relaciones-y-operaciones-de-eventos" id="toc-relaciones-y-operaciones-de-eventos" class="nav-link" data-scroll-target="#relaciones-y-operaciones-de-eventos"><span class="header-section-number">3.3.1</span> Relaciones y Operaciones de Eventos</a></li>
  <li><a href="#diagramas-de-venn" id="toc-diagramas-de-venn" class="nav-link" data-scroll-target="#diagramas-de-venn"><span class="header-section-number">3.3.2</span> Diagramas de Venn</a></li>
  <li><a href="#leyes-de-de-morgan" id="toc-leyes-de-de-morgan" class="nav-link" data-scroll-target="#leyes-de-de-morgan"><span class="header-section-number">3.3.3</span> Leyes de De Morgan</a></li>
  </ul></li>
  <li><a href="#sec-semana03-s3" id="toc-sec-semana03-s3" class="nav-link" data-scroll-target="#sec-semana03-s3"><span class="header-section-number">3.4</span> Definiciones de Probabilidad</a>
  <ul class="collapse">
  <li><a href="#probabilidad-clasica-laplace" id="toc-probabilidad-clasica-laplace" class="nav-link" data-scroll-target="#probabilidad-clasica-laplace"><span class="header-section-number">3.4.1</span> Probabilidad Clásica (Laplace)</a></li>
  <li><a href="#probabilidad-frecuentista-von-mises" id="toc-probabilidad-frecuentista-von-mises" class="nav-link" data-scroll-target="#probabilidad-frecuentista-von-mises"><span class="header-section-number">3.4.2</span> Probabilidad Frecuentista (von Mises)</a></li>
  <li><a href="#probabilidad-axiomatica-kolmogorov" id="toc-probabilidad-axiomatica-kolmogorov" class="nav-link" data-scroll-target="#probabilidad-axiomatica-kolmogorov"><span class="header-section-number">3.4.3</span> Probabilidad Axiomática (Kolmogorov)</a></li>
  </ul></li>
  <li><a href="#sec-semana03-s4" id="toc-sec-semana03-s4" class="nav-link" data-scroll-target="#sec-semana03-s4"><span class="header-section-number">3.5</span> Propiedades de la Probabilidad</a></li>
  <li><a href="#sec-semana03-s5" id="toc-sec-semana03-s5" class="nav-link" data-scroll-target="#sec-semana03-s5"><span class="header-section-number">3.6</span> Teorema de la Suma (Inclusión-Exclusión)</a></li>
  <li><a href="#sec-semana03-s6" id="toc-sec-semana03-s6" class="nav-link" data-scroll-target="#sec-semana03-s6"><span class="header-section-number">3.7</span> Probabilidad Condicional</a>
  <ul class="collapse">
  <li><a href="#teorema-de-la-multiplicacion" id="toc-teorema-de-la-multiplicacion" class="nav-link" data-scroll-target="#teorema-de-la-multiplicacion"><span class="header-section-number">3.7.1</span> Teorema de la Multiplicación</a></li>
  </ul></li>
  <li><a href="#sec-semana03-s7" id="toc-sec-semana03-s7" class="nav-link" data-scroll-target="#sec-semana03-s7"><span class="header-section-number">3.8</span> Independencia de Eventos</a>
  <ul class="collapse">
  <li><a href="#independencia-de-multiples-eventos" id="toc-independencia-de-multiples-eventos" class="nav-link" data-scroll-target="#independencia-de-multiples-eventos"><span class="header-section-number">3.8.1</span> Independencia de Múltiples Eventos</a></li>
  </ul></li>
  <li><a href="#sec-semana03-s8" id="toc-sec-semana03-s8" class="nav-link" data-scroll-target="#sec-semana03-s8"><span class="header-section-number">3.9</span> Ley de la Probabilidad Total</a></li>
  <li><a href="#sec-semana03-s9" id="toc-sec-semana03-s9" class="nav-link" data-scroll-target="#sec-semana03-s9"><span class="header-section-number">3.10</span> Teorema de Bayes</a>
  <ul class="collapse">
  <li><a href="#forma-simple-del-teorema-de-bayes" id="toc-forma-simple-del-teorema-de-bayes" class="nav-link" data-scroll-target="#forma-simple-del-teorema-de-bayes"><span class="header-section-number">3.10.1</span> Forma Simple del Teorema de Bayes</a></li>
  <li><a href="#forma-general-con-particion" id="toc-forma-general-con-particion" class="nav-link" data-scroll-target="#forma-general-con-particion"><span class="header-section-number">3.10.2</span> Forma General con Partición</a></li>
  <li><a href="#ejemplo-prueba-diagnostica" id="toc-ejemplo-prueba-diagnostica" class="nav-link" data-scroll-target="#ejemplo-prueba-diagnostica"><span class="header-section-number">3.10.3</span> Ejemplo: Prueba Diagnóstica</a></li>
  <li><a href="#ejemplo-clasificacion-de-pacientse" id="toc-ejemplo-clasificacion-de-pacientse" class="nav-link" data-scroll-target="#ejemplo-clasificacion-de-pacientse"><span class="header-section-number">3.10.4</span> Ejemplo: Clasificación de pacientse</a></li>
  </ul></li>
  <li><a href="#sec-semana03-resumen" id="toc-sec-semana03-resumen" class="nav-link" data-scroll-target="#sec-semana03-resumen"><span class="header-section-number">3.11</span> Resumen</a>
  <ul class="collapse">
  <li><a href="#conceptos-clave" id="toc-conceptos-clave" class="nav-link" data-scroll-target="#conceptos-clave"><span class="header-section-number">3.11.1</span> Conceptos Clave</a></li>
  <li><a href="#definiciones-de-probabilidad" id="toc-definiciones-de-probabilidad" class="nav-link" data-scroll-target="#definiciones-de-probabilidad"><span class="header-section-number">3.11.2</span> Definiciones de Probabilidad</a></li>
  <li><a href="#formulas-importantes" id="toc-formulas-importantes" class="nav-link" data-scroll-target="#formulas-importantes"><span class="header-section-number">3.11.3</span> Fórmulas Importantes</a></li>
  </ul></li>
  <li><a href="#sec-semana03-ejercicios" id="toc-sec-semana03-ejercicios" class="nav-link" data-scroll-target="#sec-semana03-ejercicios"><span class="header-section-number">3.12</span> Ejercicios</a></li>
  <li><a href="#sec-semana03-respuestas" id="toc-sec-semana03-respuestas" class="nav-link" data-scroll-target="#sec-semana03-respuestas"><span class="header-section-number">3.13</span> Respuestas a los Ejercicios</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/edit/main/chapters/semana03.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/blob/main/chapters/semana03.qmd" class="toc-action"><i class="bi empty"></i>Ver el código</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/semana03.html">Parte II: Probabilidad y Variables Aleatorias</a></li><li class="breadcrumb-item"><a href="../chapters/semana03.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Semana 3 — Fundamentos de la Teoría de la Probabilidad</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-semana03" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Semana 3 — Fundamentos de la Teoría de la Probabilidad</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduccion" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="introduccion"><span class="header-section-number">3.1</span> Introducción</h2>
<p>La probabilidad es el fundamento del razonamiento estadístico. Esta semana cubriremos los conceptos básicos de la teoría de la probabilidad: experimentos aleatorios, espacios muestrales, eventos, y las herramientas matemáticas para cuantificar la incertidumbre. Aprenderemos los axiomas de Kolmogorov, el Teorema de Bayes, y cómo actualizar nuestras creencias con nueva información.</p>
<hr>
</section>
<section id="sec-semana03-s1" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-semana03-s1"><span class="header-section-number">3.2</span> Experimentos Aleatorios y Eventos</h2>
<section id="experimento-aleatorio" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="experimento-aleatorio"><span class="header-section-number">3.2.1</span> Experimento Aleatorio</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Experimento Aleatorio
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un <strong>experimento aleatorio</strong> es un proceso que:</p>
<ul>
<li>Puede repetirse bajo condiciones idénticas</li>
<li>Tiene al menos dos resultados posibles diferentes</li>
<li>Se realiza de una manera claramente especificada</li>
<li>Tiene un resultado que no puede predecirse con certeza antes de realizarse</li>
</ul>
<p>El <strong>espacio muestral</strong> <span class="math inline">\(\Omega\)</span> (o <span class="math inline">\(S\)</span>) es el conjunto de todos los resultados posibles del experimento.</p>
<p>Un <strong>evento</strong> <span class="math inline">\(A\)</span> es un subconjunto del espacio muestral. Decimos que un evento “ocurre” si el resultado del experimento es un elemento de <span class="math inline">\(A\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.1: Aleatorización en Ensayo Clínico
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Experimento:</strong> Aleatorización de un paciente a un grupo de tratamiento (<span class="math inline">\(T\)</span>) o control (<span class="math inline">\(C\)</span>) mediante el lanzamiento de una moneda.</p>
<p><strong>Espacio muestral:</strong> <span class="math display">\[\Omega = \{T, C\}\]</span></p>
<p><strong>Eventos posibles:</strong> - Evento <span class="math inline">\(A\)</span>: “el paciente es asignado al grupo de tratamiento” → <span class="math inline">\(A = \{T\}\)</span> - Evento <span class="math inline">\(B\)</span>: “el paciente es asignado al grupo control” → <span class="math inline">\(B = \{C\}\)</span></p>
</div>
</div>
</section>
<section id="evento-elemental-y-particion" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="evento-elemental-y-particion"><span class="header-section-number">3.2.2</span> Evento Elemental y Partición</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Evento Elemental
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un <strong>evento elemental</strong> es un evento que contiene exactamente un resultado del experimento. Por ejemplo, <span class="math inline">\(\{2\}\)</span> es un evento elemental en el experimento de lanzar un dado.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Partición Completa
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los eventos <span class="math inline">\(A_1, A_2, \ldots, A_n\)</span> forman una <strong>partición completa</strong> del espacio muestral <span class="math inline">\(\Omega\)</span> si:</p>
<ol type="1">
<li><span class="math inline">\(A_i \cap A_j = \emptyset\)</span> para todo <span class="math inline">\(i \neq j\)</span> (son mutuamente disjuntos)</li>
<li><span class="math inline">\(A_1 \cup A_2 \cup \ldots \cup A_n = \Omega\)</span> (cubren todo el espacio)</li>
<li><span class="math inline">\(\mathbb{P}(A_i) &gt; 0\)</span> para cada <span class="math inline">\(i\)</span> (cada uno tiene probabilidad positiva)</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana03-s2" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-semana03-s2"><span class="header-section-number">3.3</span> Álgebra de Conjuntos</h2>
<p>Los eventos se pueden combinar usando operaciones de conjuntos. A continuación presentamos las operaciones fundamentales:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Operaciones Básicas de Conjuntos
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Conjunto vacío:</strong> <span class="math inline">\(\emptyset\)</span> es el conjunto sin elementos. En términos de eventos, <span class="math inline">\(A = \emptyset\)</span> significa que el evento es imposible.</p>
<p><strong>Subconjunto:</strong> <span class="math inline">\(A \subseteq B\)</span> significa que cada elemento de <span class="math inline">\(A\)</span> está también en <span class="math inline">\(B\)</span>. En términos de eventos: “si <span class="math inline">\(A\)</span> ocurre, entonces <span class="math inline">\(B\)</span> ocurre”.</p>
<p><strong>Intersección:</strong> <span class="math inline">\(A \cap B\)</span> es el conjunto de elementos que están en ambos <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span>. En términos de eventos: “tanto <span class="math inline">\(A\)</span> como <span class="math inline">\(B\)</span> ocurren”.</p>
<p><strong>Unión:</strong> <span class="math inline">\(A \cup B\)</span> es el conjunto de elementos que están en <span class="math inline">\(A\)</span> o en <span class="math inline">\(B\)</span> (o en ambos). En términos de eventos: “al menos uno de <span class="math inline">\(A\)</span> o <span class="math inline">\(B\)</span> ocurre”.</p>
<p><strong>Complemento:</strong> <span class="math inline">\(\overline{A}\)</span> (o <span class="math inline">\(A^c\)</span>) es el conjunto de elementos en <span class="math inline">\(\Omega\)</span> que no están en <span class="math inline">\(A\)</span>. En términos de eventos: “<span class="math inline">\(A\)</span> no ocurre”.</p>
<p><strong>Diferencia:</strong> <span class="math inline">\(A - B\)</span> (o <span class="math inline">\(A - B\)</span>) es el conjunto de elementos en <span class="math inline">\(A\)</span> pero no en <span class="math inline">\(B\)</span>. En términos de eventos: “<span class="math inline">\(A\)</span> ocurre pero <span class="math inline">\(B\)</span> no ocurre”.</p>
</div>
</div>
<section id="relaciones-y-operaciones-de-eventos" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="relaciones-y-operaciones-de-eventos"><span class="header-section-number">3.3.1</span> Relaciones y Operaciones de Eventos</h3>
<p>La siguiente tabla resume las correspondencias entre descripciones de eventos y notación de conjuntos:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Descripción</th>
<th>Notación</th>
<th>Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(A\)</span> ocurre con certeza</td>
<td><span class="math inline">\(A = \Omega\)</span></td>
<td>evento seguro</td>
</tr>
<tr class="even">
<td><span class="math inline">\(A\)</span> es imposible</td>
<td><span class="math inline">\(A = \emptyset\)</span></td>
<td>evento imposible</td>
</tr>
<tr class="odd">
<td>Si <span class="math inline">\(A\)</span> ocurre, entonces <span class="math inline">\(B\)</span> ocurre</td>
<td><span class="math inline">\(A \subseteq B\)</span></td>
<td><span class="math inline">\(A\)</span> es subconjunto de <span class="math inline">\(B\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> nunca ocurren juntos</td>
<td><span class="math inline">\(A \cap B = \emptyset\)</span></td>
<td>eventos disjuntos</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> son complementarios</td>
<td><span class="math inline">\(B = \overline{A}\)</span></td>
<td><span class="math inline">\(B\)</span> ocurre si y solo si <span class="math inline">\(A\)</span> no ocurre</td>
</tr>
<tr class="even">
<td>Al menos uno de los <span class="math inline">\(A_i\)</span> ocurre</td>
<td><span class="math inline">\(A = \bigcup_{i} A_i\)</span></td>
<td>unión de eventos</td>
</tr>
<tr class="odd">
<td>Todos los <span class="math inline">\(A_i\)</span> ocurren</td>
<td><span class="math inline">\(A = \bigcap_{i} A_i\)</span></td>
<td>intersección de eventos</td>
</tr>
</tbody>
</table>
</section>
<section id="diagramas-de-venn" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="diagramas-de-venn"><span class="header-section-number">3.3.2</span> Diagramas de Venn</h3>
<p>Los diagramas de Venn proporcionan representaciones visuales de operaciones entre conjuntos. A continuación se muestran las operaciones fundamentales:</p>
<div style="text-align: center; margin: 20px 0;">
<figure class="figure">
<svg width="600" height="320" xmlns="http://www.w3.org/2000/svg">
  <!-- Fila 1 -->
  <!-- Subset -->
  <g transform="translate(0,0)">
    <ellipse cx="80" cy="75" rx="50" ry="50" fill="none" stroke="blue" stroke-width="2"></ellipse>
    <ellipse cx="80" cy="75" rx="25" ry="30" fill="lightblue" stroke="blue" stroke-width="2"></ellipse>
    <text x="75" y="80" font-size="14">A</text>
    <text x="110" y="50" font-size="14">B</text>
    <text x="80" y="145" font-size="12" text-anchor="middle">A ⊆ B (Subconjunto)</text>
  </g>

  <!-- Union -->
  <g transform="translate(200,0)">
    <ellipse cx="60" cy="75" rx="45" ry="45" fill="lightblue" fill-opacity="0.6" stroke="blue" stroke-width="2"></ellipse>
    <ellipse cx="100" cy="75" rx="45" ry="45" fill="lightblue" fill-opacity="0.6" stroke="blue" stroke-width="2"></ellipse>
    <text x="40" y="75" font-size="14">A</text>
    <text x="120" y="75" font-size="14">B</text>
    <text x="80" y="145" font-size="12" text-anchor="middle">A ∪ B (Unión)</text>
  </g>

  <!-- Intersection -->
  <g transform="translate(400,0)">
    <ellipse cx="60" cy="75" rx="45" ry="45" fill="none" stroke="blue" stroke-width="2"></ellipse>
    <ellipse cx="100" cy="75" rx="45" ry="45" fill="none" stroke="blue" stroke-width="2"></ellipse>
    <clippath id="inter">
      <ellipse cx="60" cy="75" rx="45" ry="45"></ellipse>
    </clippath>
    <ellipse cx="100" cy="75" rx="45" ry="45" fill="lightblue" clip-path="url(#inter)"></ellipse>
    <text x="40" y="75" font-size="14">A</text>
    <text x="120" y="75" font-size="14">B</text>
    <text x="80" y="145" font-size="12" text-anchor="middle">A ∩ B (Intersección)</text>
  </g>

  <!-- Fila 2 -->
  <!-- Complement -->
  <g transform="translate(0,160)">
    <rect x="20" y="25" width="120" height="100" fill="lightblue" fill-opacity="0.4" stroke="blue" stroke-width="2"></rect>
    <ellipse cx="80" cy="75" rx="35" ry="35" fill="white" stroke="blue" stroke-width="2"></ellipse>
    <text x="75" y="80" font-size="14">A</text>
    <text x="125" y="45" font-size="14">Ā</text>
    <text x="80" y="145" font-size="12" text-anchor="middle">Ā (Complemento)</text>
  </g>

  <!-- Disjoint -->
  <g transform="translate(200,160)">
    <ellipse cx="50" cy="75" rx="35" ry="35" fill="lightblue" stroke="blue" stroke-width="2"></ellipse>
    <ellipse cx="110" cy="75" rx="35" ry="35" fill="#e8f0f8" stroke="#0052a3" stroke-width="2"></ellipse>
    <text x="45" y="80" font-size="14">A</text>
    <text x="105" y="80" font-size="14">B</text>
    <text x="80" y="145" font-size="12" text-anchor="middle">A ∩ B = ∅ (Disjuntos)</text>
  </g>

  <!-- Difference -->
  <g transform="translate(400,160)">
    <ellipse cx="100" cy="75" rx="45" ry="45" fill="none" stroke="blue" stroke-width="2"></ellipse>
    <clippath id="diff">
      <rect x="0" y="0" width="160" height="150"></rect>
    </clippath>
    <mask id="mask1">
      <rect x="0" y="0" width="160" height="150" fill="white"></rect>
      <ellipse cx="100" cy="75" rx="45" ry="45" fill="black"></ellipse>
    </mask>
    <ellipse cx="60" cy="75" rx="45" ry="45" fill="lightblue" mask="url(#mask1)" stroke="blue" stroke-width="2"></ellipse>
    <text x="40" y="75" font-size="14">A</text>
    <text x="120" y="75" font-size="14">B</text>
    <text x="80" y="145" font-size="12" text-anchor="middle">A \ B (Diferencia)</text>
  </g>
</svg>
</figure>
</div>
</section>
<section id="leyes-de-de-morgan" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="leyes-de-de-morgan"><span class="header-section-number">3.3.3</span> Leyes de De Morgan</h3>
<p>Las Leyes de De Morgan son reglas fundamentales que relacionan la unión, la intersección y el complemento de conjuntos. Son extremadamente útiles para simplificar expresiones probabilísticas complejas.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Leyes de De Morgan
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cualquier par de eventos <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span>:</p>
<ol type="1">
<li><p><strong>Complemento de la unión:</strong> El complemento de la unión de dos conjuntos es la intersección de sus complementos. <span class="math display">\[\overline{A \cup B} = \overline{A} \cap \overline{B}\]</span> <em>Significado:</em> “Ni A ni B ocurren” es lo mismo que “A no ocurre Y B no ocurre”.</p></li>
<li><p><strong>Complemento de la intersección:</strong> El complemento de la intersección de dos conjuntos es la unión de sus complementos. <span class="math display">\[\overline{A \cap B} = \overline{A} \cup \overline{B}\]</span> <em>Significado:</em> “No ocurre que ambos A y B ocurran” es lo mismo que “A no ocurre O B no ocurre”.</p></li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.2: Visualización de De Morgan
</div>
</div>
<div class="callout-body-container callout-body">
<p>Representación de <span class="math inline">\(\overline{A \cup B} = \overline{A} \cap \overline{B}\)</span>:</p>
<div style="text-align: center; margin: 20px 0;">
<svg width="400" height="200" xmlns="http://www.w3.org/2000/svg">
  <rect x="50" y="20" width="300" height="150" fill="#f8f9fa" stroke="#dee2e6" stroke-width="2"></rect>
  <rect x="50" y="20" width="300" height="150" fill="#e8f0f8" fill-opacity="0.5"></rect>
  <ellipse cx="170" cy="95" rx="60" ry="60" fill="white" stroke="blue" stroke-width="2"></ellipse>
  <ellipse cx="230" cy="95" rx="60" ry="60" fill="white" stroke="blue" stroke-width="2"></ellipse>
  <text x="140" y="95" font-size="16">A</text>
  <text x="250" y="95" font-size="16">B</text>
  <text x="60" y="40" font-size="14" font-weight="bold">Ω (Espacio Muestral)</text>
  <text x="200" y="190" font-size="14" text-anchor="middle">Zona azul clara: (A ∪ B)ᶜ = Ā ∩ B̄</text>
</svg>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.3: Aplicación Práctica con 3 Conjuntos
</div>
</div>
<div class="callout-body-container callout-body">
<p>En estudios epidemiológicos es común analizar la comorbilidad de tres condiciones (A, B, C). Un diagrama de Venn de 3 conjuntos permite visualizar todas las posibles intersecciones:</p>
<div style="text-align: center; margin: 20px 0;">
<svg width="300" height="300" xmlns="http://www.w3.org/2000/svg">
  <!-- Conjuntos -->
  <circle cx="110" cy="110" r="80" fill="rgba(0, 48, 135, 0.1)" stroke="#003087" stroke-width="2"></circle>
  <circle cx="190" cy="110" r="80" fill="rgba(0, 82, 163, 0.1)" stroke="#0052a3" stroke-width="2"></circle>
  <circle cx="150" cy="190" r="80" fill="rgba(77, 148, 255, 0.1)" stroke="#4d94ff" stroke-width="2"></circle>
  
  <!-- Etiquetas -->
  <text x="60" y="80" font-size="16" fill="#003087" font-weight="bold">A</text>
  <text x="230" y="80" font-size="16" fill="#0052a3" font-weight="bold">B</text>
  <text x="145" y="260" font-size="16" fill="#4d94ff" font-weight="bold">C</text>
  
  <!-- Intersección triple -->
  <text x="150" y="145" font-size="10" text-anchor="middle" font-weight="bold">A∩B∩C</text>
</svg>
</div>
<p><strong>Problema:</strong> En una muestra de 100 pacientes: - 40 tienen Hipertensión (A) - 30 tienen Diabetes (B) - 20 tienen Obesidad (C) - 10 tienen A y B - 8 tienen A y C - 5 tienen B y C - 3 tienen las tres condiciones</p>
<p>¿Cuántos pacientes tienen <strong>al menos una</strong> condición? Usando el principio de Inclusión-Exclusión: <span class="math inline">\(|A \cup B \cup C| = 40 + 30 + 20 - (10 + 8 + 5) + 3 = 90 - 23 + 3 = 70 \text{ pacientes}.\)</span></p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana03-s3" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-semana03-s3"><span class="header-section-number">3.4</span> Definiciones de Probabilidad</h2>
<p>Existen varias formas de formalizar el concepto de probabilidad, cada una reflejando una filosofía diferente sobre cómo interpretamos la “probabilidad”.</p>
<section id="probabilidad-clasica-laplace" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="probabilidad-clasica-laplace"><span class="header-section-number">3.4.1</span> Probabilidad Clásica (Laplace)</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Probabilidad Clásica de Laplace
</div>
</div>
<div class="callout-body-container callout-body">
<p>La probabilidad clásica se define como:</p>
<p><span class="math display">\[\mathbb{P}(A) = \frac{\text{Número de resultados favorables a } A}{\text{Número total de resultados posibles}} = \frac{|A|}{|\Omega|}\]</span></p>
<p><strong>Supuestos:</strong> - Hay al menos dos resultados elementales posibles - Exactamente uno de los resultados posibles ocurre en cada experimento - El número de resultados elementales es finito - Cada resultado elemental ocurre con la misma probabilidad (equiprobabilidad)</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.4: Moneda justa en Aleatorización
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Experimento:</strong> Lanzar una moneda para decidir el grupo de tratamiento de un paciente.</p>
<p><strong>Evento <span class="math inline">\(A\)</span>:</strong> “el paciente es asignado al grupo de tratamiento (<span class="math inline">\(T\)</span>)”</p>
<p><strong>Resultados favorables a <span class="math inline">\(A\)</span>:</strong> <span class="math inline">\(\{T\}\)</span> → 1 resultado</p>
<p><strong>Resultados totales:</strong> <span class="math inline">\(\{T, C\}\)</span> → 2 resultados</p>
<p><span class="math display">\[\mathbb{P}(A) = \frac{1}{2} = 0.5\]</span></p>
</div>
</div>
</section>
<section id="probabilidad-frecuentista-von-mises" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="probabilidad-frecuentista-von-mises"><span class="header-section-number">3.4.2</span> Probabilidad Frecuentista (von Mises)</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Probabilidad Frecuentista
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sea <span class="math inline">\(n\)</span> el número de repeticiones de un experimento y <span class="math inline">\(f_n(A)\)</span> el número de veces que ocurre el evento <span class="math inline">\(A\)</span>. La <strong>frecuencia relativa</strong> es:</p>
<p><span class="math display">\[\text{Frecuencia relativa} = \frac{f_n(A)}{n}\]</span></p>
<p>La <strong>probabilidad frecuentista</strong> de <span class="math inline">\(A\)</span> se define como el límite de la frecuencia relativa cuando <span class="math inline">\(n \to \infty\)</span>:</p>
<p><span class="math display">\[\mathbb{P}(A) = \lim_{n \to \infty} \frac{f_n(A)}{n}\]</span></p>
<p>Esta definición requiere: - Una secuencia de muestras independientes - Bajo condiciones idénticas - Repetibles arbitrariamente</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.5: Simulación de aleatorización
</div>
</div>
<div class="callout-body-container callout-body">
<p>Simulamos asignar <span class="math inline">\(n\)</span> pacientes a un grupo de tratamiento:</p>
<div class="cell">
<div id="lst-semana03-1" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana03-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;3.1: Código R
</figcaption>
<div aria-describedby="lst-semana03-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>asignacion <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fl">0.5</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>prop_10 <span class="ot">&lt;-</span> <span class="fu">sum</span>(asignacion) <span class="sc">/</span> n</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"n ="</span>, n, <span class="st">": proporción asignada a tratamiento ="</span>, prop_10, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>n = 10 : proporción asignada a tratamiento = 0.6 </code></pre>
</div>
<div id="lst-semana03-1" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana03-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;3.2: Código R
</figcaption>
<div aria-describedby="lst-semana03-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>asignacion <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fl">0.5</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>prop_100 <span class="ot">&lt;-</span> <span class="fu">sum</span>(asignacion) <span class="sc">/</span> n</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"n ="</span>, n, <span class="st">": proporción asignada a tratamiento ="</span>, prop_100, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>n = 100 : proporción asignada a tratamiento = 0.46 </code></pre>
</div>
<div id="lst-semana03-1" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana03-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;3.3: Código R
</figcaption>
<div aria-describedby="lst-semana03-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>asignacion <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fl">0.5</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>prop_1000 <span class="ot">&lt;-</span> <span class="fu">sum</span>(asignacion) <span class="sc">/</span> n</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"n ="</span>, n, <span class="st">": proporción asignada a tratamiento ="</span>, prop_1000, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>n = 1000 : proporción asignada a tratamiento = 0.497 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<p>La simulación ilustra la <strong>Ley de los Grandes Números</strong>: conforme incrementamos el tamaño muestral de 10 a 1,000 pacientes, la proporción observada de asignados al tratamiento converge hacia la probabilidad teórica de 0.5. Con apenas 10 pacientes observamos fluctuaciones notables (prop_10 = 0.60), con 100 ya se acerca al valor esperado (prop_100 = 0.46), y con 1,000 pacientes la proporción se estabiliza muy cerca de 0.5 (prop_1000 = 0.497). Esto demuestra empíricamente por qué los estudios clínicos requieren tamaños muestrales adecuados: garantizan que la frecuencia relativa refleje la probabilidad verdadera subyacente en la aleatorización.</p>
</div>
</div>
<p>A medida que <span class="math inline">\(n\)</span> aumenta, la proporción de pacientes en el grupo de tratamiento se acerca a 0.5.</p>
</div>
</div>
</section>
<section id="probabilidad-axiomatica-kolmogorov" class="level3" data-number="3.4.3">
<h3 data-number="3.4.3" class="anchored" data-anchor-id="probabilidad-axiomatica-kolmogorov"><span class="header-section-number">3.4.3</span> Probabilidad Axiomática (Kolmogorov)</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Axiomas de Kolmogorov
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una función <span class="math inline">\(\mathbb{P}: \mathcal{F} \to [0,1]\)</span> que asigna un número a cada evento en <span class="math inline">\(\Omega\)</span> es una <strong>medida de probabilidad</strong> si satisface los siguientes axiomas:</p>
<p><strong>Axioma 1 (No negatividad):</strong> <span class="math display">\[\mathbb{P}(A) \geq 0 \text{ para todo evento } A\]</span></p>
<p><strong>Axioma 2 (Normalización):</strong> <span class="math display">\[\mathbb{P}(\Omega) = 1\]</span></p>
<p><strong>Axioma 3 (Aditividad contable):</strong> Si <span class="math inline">\(A_1, A_2, A_3, \ldots\)</span> son eventos mutuamente disjuntos (es decir, <span class="math inline">\(A_i \cap A_j = \emptyset\)</span> para <span class="math inline">\(i \neq j\)</span>), entonces:</p>
<p><span class="math display">\[\mathbb{P}\left(\bigcup_{i=1}^{\infty} A_i\right) = \sum_{i=1}^{\infty} \mathbb{P}(A_i)\]</span></p>
<p><strong>Componentes de un espacio de probabilidad:</strong> 1. Un espacio muestral <span class="math inline">\(\Omega\)</span> (el conjunto de todos los resultados posibles) 2. Una <span class="math inline">\(\sigma\)</span>-álgebra <span class="math inline">\(\mathcal{F}\)</span> (una colección de eventos) 3. Una medida de probabilidad <span class="math inline">\(\mathbb{P}\)</span> (que satisface los axiomas anteriores)</p>
</div>
</div>
<p>La definición axiomática de Kolmogorov es la más general y es la base de toda la teoría moderna de la probabilidad.</p>
<hr>
</section>
</section>
<section id="sec-semana03-s4" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-semana03-s4"><span class="header-section-number">3.5</span> Propiedades de la Probabilidad</h2>
<p>De los axiomas de Kolmogorov se derivan varias propiedades útiles:</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Teorema: Propiedades Fundamentales de la Probabilidad
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sea <span class="math inline">\(A, B, A_1, A_2, \ldots\)</span> eventos en un espacio de probabilidad. Entonces:</p>
<p><strong>Propiedad 1: Probabilidad del complemento</strong></p>
<p><span class="math display">\[\mathbb{P}(\overline{A}) = 1 - \mathbb{P}(A)\]</span></p>
<p><em>Prueba:</em> Note que <span class="math inline">\(A \cup \overline{A} = \Omega\)</span> y <span class="math inline">\(A \cap \overline{A} = \emptyset\)</span>. Por el Axioma 3:</p>
<p><span class="math display">\[\mathbb{P}(\Omega) = \mathbb{P}(A) + \mathbb{P}(\overline{A}) = 1\]</span></p>
<p><strong>Propiedad 2: Probabilidad del conjunto vacío</strong></p>
<p><span class="math display">\[\mathbb{P}(\emptyset) = 0\]</span></p>
<p><em>Prueba:</em> <span class="math inline">\(\emptyset = \overline{\Omega}\)</span>, así que <span class="math inline">\(\mathbb{P}(\emptyset) = 1 - \mathbb{P}(\Omega) = 1 - 1 = 0\)</span>.</p>
<p><strong>Propiedad 3: Monotonía</strong></p>
<p>Si <span class="math inline">\(A \subseteq B\)</span>, entonces <span class="math inline">\(\mathbb{P}(A) \leq \mathbb{P}(B)\)</span></p>
<p><em>Prueba:</em> Si <span class="math inline">\(A \subseteq B\)</span>, entonces <span class="math inline">\(B = A \cup (B - A)\)</span> donde <span class="math inline">\(A\)</span> y <span class="math inline">\(B - A\)</span> son disjuntos. Por el Axioma 3:</p>
<p><span class="math display">\[\mathbb{P}(B) = \mathbb{P}(A) + \mathbb{P}(B - A) \geq \mathbb{P}(A)\]</span></p>
<p><strong>Propiedad 4: Acotamiento</strong></p>
<p><span class="math display">\[0 \leq \mathbb{P}(A) \leq 1\]</span></p>
<p>Se sigue de los Axiomas 1 y 2.</p>
<p><strong>Propiedad 5: Regla de la suma (Inclusión-Exclusión)</strong></p>
<p><span class="math display">\[\mathbb{P}(A \cup B) = \mathbb{P}(A) + \mathbb{P}(B) - \mathbb{P}(A \cap B)\]</span></p>
<p><em>Prueba:</em> Observe que <span class="math inline">\(A \cup B = A \cup (B - A)\)</span> donde estos son disjuntos, y <span class="math inline">\(B = (A \cap B) \cup (B - A)\)</span>.</p>
<p><strong>Propiedad 6: Aditividad para eventos disjuntos</strong></p>
<p>Si <span class="math inline">\(A \cap B = \emptyset\)</span>, entonces:</p>
<p><span class="math display">\[\mathbb{P}(A \cup B) = \mathbb{P}(A) + \mathbb{P}(B)\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.6: Aplicación de propiedades
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Problema:</strong> En una consulta médica, el 30% de los pacientes tienen hipertensión (<span class="math inline">\(H\)</span>). Entre los pacientes hipertensos, el 80% también presenta obesidad. ¿Cuál es la probabilidad de que un paciente NO tenga hipertensión?</p>
<p><strong>Solución:</strong> Sea <span class="math inline">\(H\)</span> = “tener hipertensión”. Entonces <span class="math inline">\(\mathbb{P}(H) = 0.30\)</span>.</p>
<p>Por la Propiedad 1: <span class="math display">\[\mathbb{P}(\text{sin hipertensión}) = \mathbb{P}(\overline{H}) = 1 - 0.30 = 0.70\]</span></p>
</div>
</div>
<hr>
</section>
<section id="sec-semana03-s5" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="sec-semana03-s5"><span class="header-section-number">3.6</span> Teorema de la Suma (Inclusión-Exclusión)</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Teorema: Regla de la Suma (Inclusión-Exclusión)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para dos eventos arbitrarios <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span>:</p>
<p><span class="math display">\[\mathbb{P}(A \cup B) = \mathbb{P}(A) + \mathbb{P}(B) - \mathbb{P}(A \cap B)\]</span></p>
<p>Para tres eventos <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, y <span class="math inline">\(C\)</span>:</p>
<p><span class="math display">\[\mathbb{P}(A \cup B \cup C) = \mathbb{P}(A) + \mathbb{P}(B) + \mathbb{P}(C)\]</span></p>
<p><span class="math display">\[- \mathbb{P}(A \cap B) - \mathbb{P}(A \cap C) - \mathbb{P}(B \cap C)\]</span></p>
<p><span class="math display">\[+ \mathbb{P}(A \cap B \cap C)\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.7: Comorbilidad de pacientes
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Problema:</strong> En una muestra de 52 pacientes, ¿cuál es la probabilidad de que un paciente tenga Hipertensión (A) O Diabetes (B)?</p>
<p><strong>Definición de eventos:</strong> - <span class="math inline">\(A\)</span> = “paciente con Hipertensión” → 4 pacientes - <span class="math inline">\(B\)</span> = “paciente con Diabetes” → 13 pacientes - <span class="math inline">\(A \cap B\)</span> = “paciente con ambas enfermedades” → 1 paciente</p>
<p><strong>Cálculo de probabilidades individuales:</strong> <span class="math display">\[\mathbb{P}(A) = \frac{4}{52}, \quad \mathbb{P}(B) = \frac{13}{52}, \quad \mathbb{P}(A \cap B) = \frac{1}{52}\]</span></p>
<p><strong>Aplicación del Teorema de la Suma:</strong> <span class="math display">\[\mathbb{P}(A \cup B) = \frac{4}{52} + \frac{13}{52} - \frac{1}{52} = \frac{16}{52} \approx 0.308\]</span></p>
</div>
</div>
<hr>
</section>
<section id="sec-semana03-s6" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="sec-semana03-s6"><span class="header-section-number">3.7</span> Probabilidad Condicional</h2>
<p>La probabilidad condicional permite actualizar nuestras creencias sobre un evento cuando tenemos información adicional.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Probabilidad Condicional
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dados dos eventos <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> con <span class="math inline">\(\mathbb{P}(B) &gt; 0\)</span>, la <strong>probabilidad condicional</strong> de <span class="math inline">\(A\)</span> dado que <span class="math inline">\(B\)</span> ha ocurrido es:</p>
<p><span class="math display">\[\mathbb{P}(A|B) = \frac{\mathbb{P}(A \cap B)}{\mathbb{P}(B)}\]</span></p>
<p><strong>Interpretación:</strong> Es la probabilidad de que ocurra <span class="math inline">\(A\)</span> cuando ya sabemos que <span class="math inline">\(B\)</span> ocurrió. Formalmente, es la fracción de casos en que <span class="math inline">\(B\)</span> ocurre que también incluyen la ocurrencia de <span class="math inline">\(A\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.8: Probabilidad condicional en aleatorización
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Experimento:</strong> Asignación de dos pacientes consecutivos a grupos de tratamiento.</p>
<p><strong>Eventos:</strong> - <span class="math inline">\(A\)</span> = “el segundo paciente es asignado al grupo de tratamiento (<span class="math inline">\(T_2\)</span>)” - <span class="math inline">\(B\)</span> = “el primer paciente fue asignado al grupo de tratamiento (<span class="math inline">\(T_1\)</span>)”</p>
<p><strong>Cálculo:</strong> Si la asignación es aleatoria e independiente, <span class="math inline">\(\mathbb{P}(T_1) = 0.5\)</span>, <span class="math inline">\(\mathbb{P}(T_2) = 0.5\)</span>. La probabilidad condicional <span class="math inline">\(\mathbb{P}(T_2|T_1) = \mathbb{P}(T_2) = 0.5\)</span> (por independencia).</p>
</div>
</div>
<section id="teorema-de-la-multiplicacion" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="teorema-de-la-multiplicacion"><span class="header-section-number">3.7.1</span> Teorema de la Multiplicación</h3>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Teorema: Regla de la Multiplicación
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para dos eventos <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span>:</p>
<p><span class="math display">\[\mathbb{P}(A \cap B) = \mathbb{P}(A) \cdot \mathbb{P}(B|A) = \mathbb{P}(B) \cdot \mathbb{P}(A|B)\]</span></p>
<p>Para tres eventos <span class="math inline">\(A_1, A_2, A_3\)</span>:</p>
<p><span class="math display">\[\mathbb{P}(A_1 \cap A_2 \cap A_3) = \mathbb{P}(A_1) \cdot \mathbb{P}(A_2|A_1) \cdot \mathbb{P}(A_3|A_1 \cap A_2)\]</span></p>
<p>Para <span class="math inline">\(n\)</span> eventos:</p>
<p><span class="math display">\[\mathbb{P}(A_1 \cap \ldots \cap A_n) = \mathbb{P}(A_1) \cdot \mathbb{P}(A_2|A_1) \cdot \mathbb{P}(A_3|A_1 \cap A_2) \cdots \mathbb{P}(A_n|A_1 \cap \ldots \cap A_{n-1})\]</span></p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana03-s7" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="sec-semana03-s7"><span class="header-section-number">3.8</span> Independencia de Eventos</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Independencia de Eventos
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dos eventos <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> son <strong>independientes</strong> si la ocurrencia de uno no afecta la probabilidad del otro:</p>
<p><span class="math display">\[\mathbb{P}(A \cap B) = \mathbb{P}(A) \cdot \mathbb{P}(B)\]</span></p>
<p>Equivalentemente: <span class="math display">\[\mathbb{P}(A|B) = \mathbb{P}(A) \quad \text{(si } \mathbb{P}(B) &gt; 0\text{)}\]</span> <span class="math display">\[\mathbb{P}(B|A) = \mathbb{P}(B) \quad \text{(si } \mathbb{P}(A) &gt; 0\text{)}\]</span></p>
<p><strong>Nota importante:</strong> Independencia es diferente de “disjuntos” (mutuamente excluyentes). Dos eventos disjuntos tienen <span class="math inline">\(\mathbb{P}(A \cap B) = 0\)</span>, lo cual es diferente de independencia.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.9: Aleatorización independiente
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Experimento:</strong> Asignar dos pacientes consecutivos al grupo de tratamiento (<span class="math inline">\(T\)</span>) o control (<span class="math inline">\(C\)</span>).</p>
<p><strong>Eventos:</strong> - <span class="math inline">\(A\)</span> = “primer paciente asignado al grupo <span class="math inline">\(T\)</span>” - <span class="math inline">\(B\)</span> = “segundo paciente asignado al grupo <span class="math inline">\(T\)</span>”</p>
<p><strong>Análisis:</strong> <span class="math display">\[\mathbb{P}(A) = 0.5, \quad \mathbb{P}(B) = 0.5\]</span> <span class="math display">\[\mathbb{P}(A \cap B) = 0.25\]</span></p>
<p><strong>Verificación de independencia:</strong> <span class="math display">\[\mathbb{P}(A) \cdot \mathbb{P}(B) = 0.5 \times 0.5 = 0.25 = \mathbb{P}(A \cap B)\]</span></p>
<p>Por lo tanto, <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> son independientes.</p>
</div>
</div>
<section id="independencia-de-multiples-eventos" class="level3" data-number="3.8.1">
<h3 data-number="3.8.1" class="anchored" data-anchor-id="independencia-de-multiples-eventos"><span class="header-section-number">3.8.1</span> Independencia de Múltiples Eventos</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Definición: Independencia Mutua
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los eventos <span class="math inline">\(A_1, A_2, \ldots, A_n\)</span> son <strong>mutuamente independientes</strong> si para cualquier subconjunto <span class="math inline">\(\{i_1, i_2, \ldots, i_k\}\)</span> de índices:</p>
<p><span class="math display">\[\mathbb{P}(A_{i_1} \cap A_{i_2} \cap \ldots \cap A_{i_k}) = \mathbb{P}(A_{i_1}) \cdot \mathbb{P}(A_{i_2}) \cdots \mathbb{P}(A_{i_k})\]</span></p>
<p>Esta condición debe cumplirse para todo subconjunto posible, no solo para pares de eventos.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana03-s8" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="sec-semana03-s8"><span class="header-section-number">3.9</span> Ley de la Probabilidad Total</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Teorema: Ley de la Probabilidad Total
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sea <span class="math inline">\(\{A_1, A_2, \ldots, A_n\}\)</span> una partición completa del espacio muestral <span class="math inline">\(\Omega\)</span>. Entonces, para cualquier evento <span class="math inline">\(B\)</span>:</p>
<p><span class="math display">\[\mathbb{P}(B) = \sum_{i=1}^{n} \mathbb{P}(B|A_i) \cdot \mathbb{P}(A_i)\]</span></p>
<p><strong>Interpretación:</strong> La probabilidad de <span class="math inline">\(B\)</span> se puede calcular como una suma ponderada de las probabilidades condicionales de <span class="math inline">\(B\)</span> bajo cada posibilidad en la partición, ponderadas por las probabilidades de cada parte.</p>
</div>
</div>
<div style="text-align: center; margin: 20px 0;">
<svg width="400" height="200" xmlns="http://www.w3.org/2000/svg">
  <rect x="50" y="20" width="300" height="150" fill="#f8f9fa" stroke="#003087" stroke-width="2"></rect>
  <line x1="150" y1="20" x2="150" y2="170" stroke="#003087" stroke-width="2"></line>
  <line x1="250" y1="20" x2="250" y2="170" stroke="#003087" stroke-width="2"></line>
  <ellipse cx="200" cy="100" rx="120" ry="50" fill="rgba(77, 148, 255, 0.3)" stroke="#4d94ff" stroke-width="2" stroke-dasharray="5,5"></ellipse>
  <text x="100" y="50" font-size="14">A1</text>
  <text x="200" y="50" font-size="14">A2</text>
  <text x="300" y="50" font-size="14">A3</text>
  <text x="200" y="100" font-size="16" font-weight="bold" fill="#003087">B</text>
  <text x="200" y="190" font-size="14" text-anchor="middle">Visualización: Partición del espacio y evento B</text>
</svg>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.10: Diagnóstico de una enfermedad (Ley de Probabilidad Total)
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Escenario:</strong> Una enfermedad se distribuye en una población según tres grupos de riesgo: - Grupo 1 (Bajo riesgo): 60% de la población, tasa de enfermedad = 2% - Grupo 2 (Riesgo moderado): 30% de la población, tasa de enfermedad = 10% - Grupo 3 (Alto riesgo): 10% de la población, tasa de enfermedad = 25%</p>
<p><strong>Probabilidades a priori:</strong> - <span class="math inline">\(\mathbb{P}(A_1) = 0.60\)</span> - <span class="math inline">\(\mathbb{P}(A_2) = 0.30\)</span> - <span class="math inline">\(\mathbb{P}(A_3) = 0.10\)</span></p>
<p><strong>Probabilidades condicionales de enfermedad (<span class="math inline">\(B\)</span>):</strong> - <span class="math inline">\(\mathbb{P}(B|A_1) = 0.02\)</span> - <span class="math inline">\(\mathbb{P}(B|A_2) = 0.10\)</span> - <span class="math inline">\(\mathbb{P}(B|A_3) = 0.25\)</span></p>
<p><strong>Aplicación de la Ley de la Probabilidad Total:</strong> <span class="math display">\[\mathbb{P}(B) = \mathbb{P}(B|A_1) \cdot \mathbb{P}(A_1) + \mathbb{P}(B|A_2) \cdot \mathbb{P}(A_2) + \mathbb{P}(B|A_3) \cdot \mathbb{P}(A_3)\]</span> <span class="math display">\[= 0.02 \times 0.60 + 0.10 \times 0.30 + 0.25 \times 0.10\]</span> <span class="math display">\[= 0.012 + 0.03 + 0.025 = 0.067\]</span></p>
<p><strong>Interpretación:</strong> La probabilidad global de padecer la enfermedad en esta población es del 6.7%.</p>
</div>
</div>
<hr>
</section>
<section id="sec-semana03-s9" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="sec-semana03-s9"><span class="header-section-number">3.10</span> Teorema de Bayes</h2>
<p>El Teorema de Bayes es uno de los resultados más importantes de la teoría de la probabilidad y es fundamental en estadística moderna y aprendizaje automático.</p>
<div style="text-align: center; margin: 20px 0;">
<svg width="400" height="200" xmlns="http://www.w3.org/2000/svg">
  <!-- Prior -->
  <rect x="50" y="50" width="100" height="100" fill="#e8f0f8" stroke="#003087" stroke-width="2"></rect>
  <text x="100" y="100" text-anchor="middle">Prior P(A)</text>

  <!-- Likelihood + Evidence -->
  <rect x="250" y="50" width="100" height="100" fill="#f8f9fa" stroke="#4d94ff" stroke-width="2"></rect>
  <text x="300" y="100" text-anchor="middle">Posterior P(A|B)</text>

  <path d="M 160 100 L 240 100" stroke="black" stroke-width="2" marker-end="url(#arrowhead)"></path>
  <defs>
    <marker id="arrowhead" markerwidth="10" markerheight="7" refx="9" refy="3.5" orient="auto">
      <polygon points="0 0, 10 3.5, 0 7"></polygon>
    </marker>
  </defs>
  <text x="200" y="90" text-anchor="middle">Evidencia B</text>
  <text x="200" y="190" font-size="14" text-anchor="middle">Actualización Bayesiana: Prior → Posterior</text>
</svg>
</div>
<section id="forma-simple-del-teorema-de-bayes" class="level3" data-number="3.10.1">
<h3 data-number="3.10.1" class="anchored" data-anchor-id="forma-simple-del-teorema-de-bayes"><span class="header-section-number">3.10.1</span> Forma Simple del Teorema de Bayes</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span><strong>Teorema: Teorema de Bayes (Forma Simple)</strong>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para dos eventos <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> con <span class="math inline">\(\mathbb{P}(B) &gt; 0\)</span>:</p>
<p><span class="math display">\[\mathbb{P}(A|B) = \frac{\mathbb{P}(B|A) \cdot \mathbb{P}(A)}{\mathbb{P}(B)}\]</span></p>
<p><strong>Terminología:</strong> - <span class="math inline">\(\mathbb{P}(A|B)\)</span> = probabilidad <strong>a posteriori</strong> (después de observar <span class="math inline">\(B\)</span>)<br>
- <span class="math inline">\(\mathbb{P}(A)\)</span> = probabilidad <strong>a priori</strong> (antes de observar <span class="math inline">\(B\)</span>)<br>
- <span class="math inline">\(\mathbb{P}(B|A)\)</span> = <strong>verosimilitud</strong> (probabilidad de la evidencia bajo el supuesto)<br>
- <span class="math inline">\(\mathbb{P}(B)\)</span> = probabilidad <strong>marginal</strong> de la evidencia</p>
</div>
</div>
</section>
<section id="forma-general-con-particion" class="level3" data-number="3.10.2">
<h3 data-number="3.10.2" class="anchored" data-anchor-id="forma-general-con-particion"><span class="header-section-number">3.10.2</span> Forma General con Partición</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Teorema: Teorema de Bayes (Forma General)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sea <span class="math inline">\(\{A_1, A_2, \ldots, A_n\}\)</span> una partición completa del espacio muestral. Para un evento <span class="math inline">\(B\)</span> con <span class="math inline">\(\mathbb{P}(B) &gt; 0\)</span>:</p>
<p><span class="math display">\[\mathbb{P}(A_j|B) = \frac{\mathbb{P}(B|A_j) \cdot \mathbb{P}(A_j)}{\sum_{i=1}^{n} \mathbb{P}(B|A_i) \cdot \mathbb{P}(A_i)}\]</span></p>
<p>para cada <span class="math inline">\(j = 1, 2, \ldots, n\)</span>.</p>
</div>
</div>
</section>
<section id="ejemplo-prueba-diagnostica" class="level3" data-number="3.10.3">
<h3 data-number="3.10.3" class="anchored" data-anchor-id="ejemplo-prueba-diagnostica"><span class="header-section-number">3.10.3</span> Ejemplo: Prueba Diagnóstica</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.11: Prueba diagnóstica médica
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Escenario:</strong> Un test de diagnóstico para una enfermedad con: - Prevalencia de la enfermedad: <span class="math inline">\(\mathbb{P}(E) = 0.05\)</span> (5% de la población) - Sensibilidad: <span class="math inline">\(\mathbb{P}(+|E) = 0.95\)</span> (95% de enfermos dan positivo) - Especificidad: <span class="math inline">\(\mathbb{P}(-|\overline{E}) = 0.90\)</span> (90% de sanos dan negativo)</p>
<p><strong>Pregunta:</strong> Si una persona da positivo, ¿cuál es la probabilidad de que realmente este enferma?</p>
<p><strong>Solución:</strong></p>
<p>Primero, calculamos <span class="math inline">\(\mathbb{P}(+) = \mathbb{P}(+|E) \cdot \mathbb{P}(E) + \mathbb{P}(+|\overline{E}) \cdot \mathbb{P}(\overline{E})\)</span></p>
<p>donde <span class="math inline">\(\mathbb{P}(+|\overline{E}) = 1 - \mathbb{P}(-|\overline{E}) = 1 - 0.90 = 0.10\)</span></p>
<p><span class="math display">\[\mathbb{P}(+) = 0.95 \times 0.05 + 0.10 \times 0.95 = 0.0475 + 0.095 = 0.1425\]</span></p>
<p>Ahora aplicamos el Teorema de Bayes:</p>
<p><span class="math display">\[\mathbb{P}(E|+) = \frac{\mathbb{P}(+|E) \cdot \mathbb{P}(E)}{\mathbb{P}(+)} = \frac{0.95 \times 0.05}{0.1425} = \frac{0.0475}{0.1425} \approx 0.333\]</span></p>
<p><strong>Interpretación:</strong> Aunque el test tiene 95% de sensibilidad, si una persona da positivo, la probabilidad de que realmente esté enferma es solo de aproximadamente 33%. Esto sucede porque la enfermedad es rara (baja prevalencia) y hay muchos falsos positivos.</p>
</div>
</div>
<div class="cell">
<div id="lst-semana03-2" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana03-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;3.4: Código R
</figcaption>
<div aria-describedby="lst-semana03-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>prev <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>sens <span class="ot">&lt;-</span> <span class="fl">0.95</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>spec <span class="ot">&lt;-</span> <span class="fl">0.90</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>falso_pos_rate <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> spec</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>p_positivo <span class="ot">&lt;-</span> sens <span class="sc">*</span> prev <span class="sc">+</span> falso_pos_rate <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> prev)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>vpp <span class="ot">&lt;-</span> (sens <span class="sc">*</span> prev) <span class="sc">/</span> p_positivo</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Prevalencia:"</span>, prev, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Prevalencia: 0.05 </code></pre>
</div>
<div id="lst-semana03-2" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana03-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;3.5: Código R
</figcaption>
<div aria-describedby="lst-semana03-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Sensibilidad:"</span>, sens, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Sensibilidad: 0.95 </code></pre>
</div>
<div id="lst-semana03-2" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana03-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;3.6: Código R
</figcaption>
<div aria-describedby="lst-semana03-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Especificidad:"</span>, spec, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Especificidad: 0.9 </code></pre>
</div>
<div id="lst-semana03-2" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana03-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;3.7: Código R
</figcaption>
<div aria-describedby="lst-semana03-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(+):"</span>, p_positivo, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>P(+): 0.1425 </code></pre>
</div>
<div id="lst-semana03-2" class="r cell-code listing quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-lst figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-lst" id="lst-semana03-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Cuadro&nbsp;3.8: Código R
</figcaption>
<div aria-describedby="lst-semana03-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<details open="" class="code-fold">
<summary>Mostrar el código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Valor Predictivo Positivo (VPP):"</span>, <span class="fu">round</span>(vpp, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</figure>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Valor Predictivo Positivo (VPP): 0.333 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<p>Este cálculo implementa el <strong>Teorema de Bayes</strong> en contexto diagnóstico: aunque la prueba posee 95% de sensibilidad (detecta enfermedad cuando existe), el Valor Predictivo Positivo (VPP ≈ 0.333) es sustancialmente menor debido a la baja prevalencia (5%). Con una enfermedad rara, la mayoría de resultados positivos son falsos positivos. En la consulta clínica, este resultado orienta decisiones: ante test positivo con baja prevalencia, es prudente confirmar con prueba adicional antes de iniciar tratamiento, ilustrando cómo la probabilidad a priori (prevalencia) moldea la interpretación clínica de la evidencia.</p>
</div>
</div>
<p>:::</p>
</section>
<section id="ejemplo-clasificacion-de-pacientse" class="level3" data-number="3.10.4">
<h3 data-number="3.10.4" class="anchored" data-anchor-id="ejemplo-clasificacion-de-pacientse"><span class="header-section-number">3.10.4</span> Ejemplo: Clasificación de pacientse</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ejemplo 3.12: Clasificación de pacientes (Bayes)
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Escenario:</strong> Un médico quiere clasificar a un paciente como de alto riesgo o bajo riesgo de sufrir una patología cardíaca basándose en tres factores de riesgo (ej. hipertensión <span class="math inline">\(W_1\)</span>, tabaquismo <span class="math inline">\(W_2\)</span>, obesidad <span class="math inline">\(W_3\)</span>).</p>
<p><strong>Información disponible:</strong> - <span class="math inline">\(\mathbb{P}(E)\)</span> = probabilidad a priori de tener la patología - <span class="math inline">\(\mathbb{P}(W_i|E)\)</span> = probabilidad de que el factor <span class="math inline">\(W_i\)</span> aparezca en pacientes enfermos - <span class="math inline">\(\mathbb{P}(W_i|\overline{E})\)</span> = probabilidad de que el factor <span class="math inline">\(W_i\)</span> aparezca en pacientes sanos</p>
<p><strong>Problema:</strong> Clasificar a un paciente que presenta los factores <span class="math inline">\(W_1, W_2, W_3\)</span>.</p>
<p><strong>Solución usando Bayes:</strong></p>
<p>Se clasifica como de “Alto Riesgo” si la probabilidad a posteriori es alta: <span class="math display">\[\frac{\mathbb{P}(E|W_1 \cap W_2 \cap W_3)}{\mathbb{P}(\overline{E}|W_1 \cap W_2 \cap W_3)} &gt; c\]</span></p>
<p>donde <span class="math inline">\(c\)</span> es un umbral clínico.</p>
<p>Asumiendo independencia condicional de los factores:</p>
<p><span class="math display">\[\frac{\mathbb{P}(E|W_1 \cap W_2 \cap W_3)}{\mathbb{P}(\overline{E}|W_1 \cap W_2 \cap W_3)} \approx \frac{\mathbb{P}(E)}{\mathbb{P}(\overline{E})} \cdot \prod_{i=1}^{3} \frac{\mathbb{P}(W_i|E)}{\mathbb{P}(W_i|\overline{E})}\]</span></p>
<p><strong>Aplicación clínica:</strong> - Permite integrar múltiples biomarcadores o factores de riesgo de manera eficiente. - Proporciona una medida de riesgo individualizada (probabilidad a posteriori). - Ayuda en la toma de decisiones clínicas para el cribado o tratamiento preventivo.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="sec-semana03-resumen" class="level2" data-number="3.11">
<h2 data-number="3.11" class="anchored" data-anchor-id="sec-semana03-resumen"><span class="header-section-number">3.11</span> Resumen</h2>
<section id="conceptos-clave" class="level3" data-number="3.11.1">
<h3 data-number="3.11.1" class="anchored" data-anchor-id="conceptos-clave"><span class="header-section-number">3.11.1</span> Conceptos Clave</h3>
<ul>
<li><strong>Experimento aleatorio:</strong> Un proceso con resultado incierto pero repetible</li>
<li><strong>Espacio muestral <span class="math inline">\(\Omega\)</span>:</strong> El conjunto de todos los resultados posibles</li>
<li><strong>Evento:</strong> Un subconjunto del espacio muestral</li>
<li><strong>Partición:</strong> Una división del espacio muestral en eventos mutuamente disjuntos</li>
</ul>
</section>
<section id="definiciones-de-probabilidad" class="level3" data-number="3.11.2">
<h3 data-number="3.11.2" class="anchored" data-anchor-id="definiciones-de-probabilidad"><span class="header-section-number">3.11.2</span> Definiciones de Probabilidad</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Definición</th>
<th>Ventajas</th>
<th>Limitaciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Clásica (Laplace)</strong></td>
<td>Simple, intuitiva</td>
<td>Requiere equiprobabilidad</td>
</tr>
<tr class="even">
<td><strong>Frecuentista (von Mises)</strong></td>
<td>Empírica, práctica</td>
<td>Requiere infinitas repeticiones</td>
</tr>
<tr class="odd">
<td><strong>Axiomática (Kolmogorov)</strong></td>
<td>General, rigurosa</td>
<td>Abstracta</td>
</tr>
</tbody>
</table>
</section>
<section id="formulas-importantes" class="level3" data-number="3.11.3">
<h3 data-number="3.11.3" class="anchored" data-anchor-id="formulas-importantes"><span class="header-section-number">3.11.3</span> Fórmulas Importantes</h3>
<p><strong>Propiedades básicas:</strong> <span class="math display">\[\mathbb{P}(\overline{A}) = 1 - \mathbb{P}(A), \quad \mathbb{P}(\emptyset) = 0, \quad \mathbb{P}(\Omega) = 1\]</span></p>
<p><strong>Regla de la suma:</strong> <span class="math display">\[\mathbb{P}(A \cup B) = \mathbb{P}(A) + \mathbb{P}(B) - \mathbb{P}(A \cap B)\]</span></p>
<p><strong>Probabilidad condicional:</strong> <span class="math display">\[\mathbb{P}(A|B) = \frac{\mathbb{P}(A \cap B)}{\mathbb{P}(B)}\]</span></p>
<p><strong>Regla de la multiplicación:</strong> <span class="math display">\[\mathbb{P}(A \cap B) = \mathbb{P}(A) \cdot \mathbb{P}(B|A)\]</span></p>
<p><strong>Independencia:</strong> <span class="math display">\[\mathbb{P}(A \cap B) = \mathbb{P}(A) \cdot \mathbb{P}(B) \text{ si y solo si } A \text{ y } B \text{ son independientes}\]</span></p>
<p><strong>Ley de la probabilidad total:</strong> <span class="math display">\[\mathbb{P}(B) = \sum_{i=1}^{n} \mathbb{P}(B|A_i) \cdot \mathbb{P}(A_i)\]</span></p>
<p><strong>Teorema de Bayes:</strong> <span class="math display">\[\mathbb{P}(A|B) = \frac{\mathbb{P}(B|A) \cdot \mathbb{P}(A)}{\mathbb{P}(B)}\]</span></p>
<p><span class="math display">\[\mathbb{P}(A_j|B) = \frac{\mathbb{P}(B|A_j) \cdot \mathbb{P}(A_j)}{\sum_{i=1}^{n} \mathbb{P}(B|A_i) \cdot \mathbb{P}(A_i)}\]</span></p>
<hr>
</section>
</section>
<section id="sec-semana03-ejercicios" class="level2" data-number="3.12">
<h2 data-number="3.12" class="anchored" data-anchor-id="sec-semana03-ejercicios"><span class="header-section-number">3.12</span> Ejercicios</h2>
<p><strong>Ejercicio 3.1:</strong> En una clase hay 30 estudiantes de doctorado asistiendo a un seminario de Bioestadística avanzada en Medicina. De ellos, 18 se graduaron en Medicina, 15 tienen un grado en Estadistica y 10 estudiantes estudiaron ambos grados. Si seleccionamos un estudiante al azar:</p>
<ol type="a">
<li>¿Cuál es la probabilidad de que se graduado en Medicina o estadística?</li>
<li>¿Cuál es la probabilidad de que haya estudiado solo Medicina?</li>
<li>¿Cuál es la probabilidad de que no hay estudiado ninguna de las dos?</li>
</ol>
<p><strong>Ejercicio 3.2:</strong> Un médico tiene dos opciones terapeúticas de antibióticos de primera línea (A o B) y tres de segunda línea de administración conjunta al tratamiento principal (1, 2, o 3) para el tratamiento de una enfermedad infecciosa y todas las opciones terapeúticas son igualmente eficaces. Si todas las opciones se eligen al azar:</p>
<ol type="a">
<li>¿Cuál es el espacio muestral?</li>
<li>¿Cuál es la probabilidad de elegir el antibiotico de primera línea A?</li>
<li>¿Cuál es la probabilidad de elegir el antibiotico de primera línea B y el de segunda línea 2?</li>
</ol>
<p><strong>Ejercicio 3.3:</strong> En un hospital, la probabilidad de que un paciente ingrese por fractura de cadera en un día es 0.1. Si evaluamos tres días independientemente:</p>
<ol type="a">
<li>¿Cuál es la probabilidad de que no ingrese ningún paciente?</li>
<li>¿Cuál es la probabilidad de que exactamente ingrese uno?</li>
</ol>
<p><strong>Ejercicio 3.4:</strong> Se sabe que: - El 60% de los pacientes de una consulta son mujeres - El 40% de las mujeres tinen menos de 30 años - El 30% de los hombres tienen menos de 30 años</p>
<p>Si seleccionamos un cliente al azar:</p>
<ol type="a">
<li>¿Cuál es la probabilidad de que un paciente tenga menos de 30 años?</li>
<li>Si un paciente tiene 30 años, ¿cuál es la probabilidad de que sea mujer?</li>
</ol>
<p><strong>Ejercicio 3.5:</strong> Un test para detectar una enfermedad rara tiene: - 98% de sensibilidad (detecta la enfermedad cuando está presente) - 95% de especificidad (identifica correctamente a personas sanas) - La enfermedad afecta al 0.5% de la población</p>
<ol type="a">
<li>Si una persona da positivo en el test, ¿cuál es la probabilidad de que realmente esté enferma?</li>
<li>Interprete el resultado. ¿Por qué la probabilidad no es más alta?</li>
</ol>
<p><strong>Ejercicio 3.6:</strong> Una empresa privada vende ecografos a tres hospitales en tres ciudades distintas: Madrid (40% de ventas), Barcelona (35%) y Valencia (25%). La probabilidad de cumplir la cuota de ventas es: - Madrid: 0.8 - Barcelona: 0.85 - Valencia: 0.7</p>
<p>Si se selecciona un mes al azar:</p>
<ol type="a">
<li>¿Cuál es la probabilidad de que se cumpla la cuota?</li>
<li>Si se cumplió la cuota, ¿cuál es la probabilidad de que haya sido en Barcelona?</li>
</ol>
</section>
<section id="sec-semana03-respuestas" class="level2" data-number="3.13">
<h2 data-number="3.13" class="anchored" data-anchor-id="sec-semana03-respuestas"><span class="header-section-number">3.13</span> Respuestas a los Ejercicios</h2>
<p><strong>Ejercicio 3.1:</strong> Diagramas de Venn<br>
- a) P(M ∪ E) = P(M) + P(E) - P(M ∩ E) = (18+15-10)/30 = 23/30 ≈ 0.767<br>
- b) P(Solo M) = (18-10)/30 = 8/30 ≈ 0.267<br>
- c) P(Ninguna) = 1 - 23/30 = 7/30 ≈ 0.233</p>
<p><strong>Ejercicio 3.2:</strong> Espacio Muestral y Probabilidad<br>
- a) Ω = {A1, A2, A3, B1, B2, B3}, |Ω| = 6<br>
- b) P(A) = 3/6 = 0.5<br>
- c) P(B y 2) = 1/6 ≈ 0.167</p>
<p><strong>Ejercicio 3.3:</strong> Independencia<br>
- a) P(Ningún ingreso) = (0.9)³ = 0.729<br>
- b) P(exactamente 1 ingreso) = C(3,1)×(0.1)¹×(0.9)² = 3×0.1×0.81 = 0.243<br>
- Nota: Más adelante veremos como caalcular esta probabilidad usando la fórmula de la distribución Binomial (n, p).</p>
<p><strong>Ejercicio 3.4:</strong> Probabilidad Total y Teorema de Bayes<br>
- a) P(Menos de 30 años) = 0.6×0.4 + 0.4×0.3 = 0.24 + 0.12 = 0.36<br>
- b) P(Mujer|Menos de 30 años) = (0.6x0.4)/0.36 = 0.24/0.36 = 2/3 ≈ 0.667</p>
<p><strong>Ejercicio 3.5:</strong> Test Diagnóstico (Bayes)<br>
- a) P(Enfermedad|Positivo) = (0.98×0.005)/(0.98×0.005 + 0.05×0.995) = 0.0049/(0.0049+0.04975) ≈ 0.090<br>
- b) Aunque el test es muy preciso (98% sensibilidad), como la enfermedad es rara (0.5%), la mayoría de positivos son falsos positivos.</p>
<p><strong>Ejercicio 3.6:</strong> Probabilidad Total y Bayes (Hospitales)<br>
- a) P(Cuota) = 0.4×0.8 + 0.35×0.85 + 0.25×0.7 = 0.32 + 0.2975 + 0.175 = 0.7925<br>
- b) P(Barcelona|Cuota) = (0.35×0.85)/0.7925 = 0.2975/0.7925 ≈ 0.375</p>
<hr>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Métodos Avanzados
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para ampliar los contenidos de este capítulo con técnicas estadísticas avanzadas, visita:</p>
<p><strong><a href="https://migariane.github.io/Bioestadistica">→ Bioestadística Avanzada — M.A.&nbsp;Luque Fernández</a></strong></p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/semana02.html" class="pagination-link" aria-label="Semana 2 — Análisis Exploratorio de Datos (Parte II)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Semana 2 — Análisis Exploratorio de Datos (Parte II)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/semana04.html" class="pagination-link" aria-label="Semana 4 — Variables Aleatorias y Distribuciones de Probabilidad">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Semana 4 — Variables Aleatorias y Distribuciones de Probabilidad</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Matemáticas para la Estadística Médica con R, por Miguel Ángel Luque Fernández</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/edit/main/chapters/semana03.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li><li><a href="https://github.com/migariane/MatematicaEstadisticaMedicinaR/blob/main/chapters/semana03.qmd" class="toc-action"><i class="bi empty"></i>Ver el código</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>© 2026 Universidad de Granada · <a href="https://www.ugr.es">ugr.es</a></p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>